package tools

import (
	"context"
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/whyrusleeping/gollama"
	"github.com/whyrusleeping/ycc/internal/sandbox"
)

// TestMain dispatches the sandbox helper when this test binary is re-executed
// with sandbox.HelperArg (the reviewer Bash landlock path re-execs os.Executable,
// which is this test binary). Otherwise it runs the suite normally.
func TestMain(m *testing.M) {
	sandbox.MaybeHelper()
	os.Exit(m.Run())
}

func reviewerReg(root string) *Registry {
	reg := New()
	reg.Add(Reviewer(&Workspace{Root: root})...)
	return reg
}

func TestInspectToolsetsIncludeAdvertisedOutputRetrieval(t *testing.T) {
	ws := &Workspace{Root: t.TempDir()}
	for name, toolset := range map[string][]*gollama.Tool{
		"inspect":           Inspect(ws),
		"read-only inspect": ReadOnlyInspect(ws),
		"reviewer":          Reviewer(ws),
	} {
		found := false
		for _, tool := range toolset {
			if tool.Name == "tool_output" {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("%s toolset advertises retained Bash captures but lacks tool_output", name)
		}
	}
}

// TestReviewerBashCannotWriteWorkspace verifies the reviewer Bash tool cannot
// create a file in the workspace while the worker Bash tool still can. Skipped
// when no sandbox mechanism is available (reviewer Bash then fails closed).
func TestReviewerBashCannotWriteWorkspace(t *testing.T) {
	if runtime.GOOS != "linux" || sandbox.Available() == sandbox.None {
		t.Skip("no sandbox mechanism available; reviewer Bash fails closed")
	}
	// Keep the workspace out of the temp dir so the write allowlist (which
	// includes os.TempDir()) does not overlap it.
	base := t.TempDir()
	root := filepath.Join(base, "ws")
	scratch := filepath.Join(base, "scratch")
	for _, d := range []string{root, scratch} {
		if err := os.MkdirAll(d, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	t.Setenv("TMPDIR", scratch)

	// Worker Bash can write.
	wreg := workerReg(root)
	if res := dispatch(t, wreg, "Bash", `{"command":"touch worker.txt"}`); res.IsError {
		t.Fatalf("worker bash: %s", res.Content)
	}
	if _, err := os.Stat(filepath.Join(root, "worker.txt")); err != nil {
		t.Fatalf("worker bash should have created the file: %v", err)
	}

	// Reviewer Bash cannot write to the workspace.
	rreg := reviewerReg(root)
	dispatch(t, rreg, "Bash", `{"command":"touch reviewer.txt"}`)
	if _, err := os.Stat(filepath.Join(root, "reviewer.txt")); !os.IsNotExist(err) {
		t.Fatalf("reviewer bash created a file in the workspace despite the sandbox: err=%v", err)
	}

	// Read-only inspection through reviewer Bash still works.
	if res := dispatch(t, rreg, "Bash", `{"command":"ls"}`); res.IsError {
		t.Fatalf("reviewer bash ls failed: %s", res.Content)
	}
}

func TestReviewerBashFailsClosedWithoutSandbox(t *testing.T) {
	if sandbox.Available() != sandbox.None {
		t.Skip("secure reviewer sandbox is available")
	}
	root := t.TempDir()
	res := dispatch(t, reviewerReg(root), "Bash", `{"command":"touch escaped"}`)
	if !res.IsError || !strings.Contains(res.Content, "reviewer shell unavailable") {
		t.Fatalf("reviewer Bash did not fail closed: %+v", res)
	}
	if _, err := os.Stat(filepath.Join(root, "escaped")); !os.IsNotExist(err) {
		t.Fatalf("unavailable reviewer sandbox executed mutation: %v", err)
	}
}

func TestReviewerBashCargoUsesFreshPrivateScratch(t *testing.T) {
	if runtime.GOOS != "linux" || sandbox.Available() == sandbox.None {
		t.Skip("no production reviewer sandbox available")
	}
	if !sandbox.BuildCapable() {
		reg := reviewerReg(t.TempDir())
		res := dispatch(t, reg, "Bash", `{"command":"cargo test","source_bound":true}`)
		if !res.IsError || !strings.Contains(res.Content, "source-bound verification unavailable") {
			t.Fatalf("non-build-capable sandbox did not report unavailable: %+v", res)
		}
		return
	}
	for _, tool := range []string{"cargo", "rustc", "git", "tar"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("%s is not installed", tool)
		}
	}

	root := filepath.Join(t.TempDir(), "rust-fixture")
	files := map[string]string{
		"Cargo.toml": `[package]
name = "review_fixture"
version = "0.1.0"
edition = "2021"
build = "build.rs"
`,
		"Cargo.lock": `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "review_fixture"
version = "0.1.0"
`,
		"build.rs": `fn main() {
    let out = std::env::var("OUT_DIR").unwrap();
    std::fs::write(std::path::Path::new(&out).join("built.txt"), "fresh").unwrap();
}
`,
		"src/lib.rs": `pub fn current() -> &'static str { "fresh-source" }
#[cfg(test)] mod tests {
    #[test] fn current_source_was_built() { assert_eq!(super::current(), "fresh-source"); }
    #[test] #[ignore] fn intentional_failure() { assert!(false); }
}
`,
		"unrelated.txt":      "preserve unrelated work\n",
		".gitignore":         "/target/\n",
		".gitattributes":     "export-ignored.txt export-ignore\nsubst.txt export-subst\nfiltered.txt filter=review-smudge\n",
		"filtered.txt":       "original-filter-bytes\n",
		"export-ignored.txt": "must remain in exact tree\n",
		"subst.txt":          "$Format:%H$\n",
	}
	for name, content := range files {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.Symlink("src/lib.rs", filepath.Join(root, "source-link")); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(root, "unrelated.txt"), filepath.Join(root, "escape-link")); err != nil {
		t.Fatal(err)
	}
	// A plausible stale workspace artifact must not be reused: the reviewer sets
	// CARGO_TARGET_DIR to a newly-created empty directory for every command.
	stale := filepath.Join(root, "target", "debug", "stale-sentinel")
	if err := os.MkdirAll(filepath.Dir(stale), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(stale, []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
		t.Fatal(err)
	}

	git := exec.Command("git", "init", "-q")
	git.Dir = root
	if out, err := git.CombinedOutput(); err != nil {
		t.Fatalf("git init: %v (%s)", err, out)
	}
	for _, args := range [][]string{{"config", "user.email", "review@test"}, {"config", "user.name", "Review Test"}, {"add", "."}, {"commit", "-qm", "fixture"}} {
		cmd := exec.Command("git", args...)
		cmd.Dir = root
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v (%s)", args, err, out)
		}
	}
	// A mutable repository checkout filter must never run while the trusted tree
	// is materialized before confinement.
	smudgeMarker := filepath.Join(filepath.Dir(root), "smudge-ran")
	smudgeScript := filepath.Join(filepath.Dir(root), "smudge-filter.sh")
	smudgeBody := "#!/bin/sh\nprintf ran > " + shellQuoteArg(smudgeMarker) + "\nsed 's/original-filter-bytes/transformed/'\n"
	if err := os.WriteFile(smudgeScript, []byte(smudgeBody), 0o755); err != nil {
		t.Fatal(err)
	}
	configFilter := exec.Command("git", "config", "filter.review-smudge.smudge", shellQuoteArg(smudgeScript))
	configFilter.Dir = root
	if out, err := configFilter.CombinedOutput(); err != nil {
		t.Fatalf("configure malicious smudge filter: %v (%s)", err, out)
	}
	headCmd := exec.Command("git", "rev-parse", "HEAD")
	headCmd.Dir = root
	headOut, err := headCmd.Output()
	if err != nil {
		t.Fatal(err)
	}
	gitlink := exec.Command("git", "update-index", "--add", "--cacheinfo", "160000,"+strings.TrimSpace(string(headOut))+",vendor/gitlink")
	gitlink.Dir = root
	if out, err := gitlink.CombinedOutput(); err != nil {
		t.Fatalf("add fixture gitlink: %v (%s)", err, out)
	}
	treeCmd := exec.Command("git", "write-tree")
	treeCmd.Dir = root
	treeOut, err := treeCmd.Output()
	if err != nil {
		t.Fatal(err)
	}
	tree := strings.TrimSpace(string(treeOut))
	// Diverge the live worktree after capturing the assigned tree. A source-bound
	// verification must still compile the captured source, not this replacement.
	if err := os.WriteFile(filepath.Join(root, "src/lib.rs"), []byte("compile_error!(\"live worktree must not be built\");\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	ws := &Workspace{Root: root, ReviewSnapshot: "fixture-snapshot", ReviewTree: tree}
	reg := New()
	reg.Add(Reviewer(ws)...)
	args, _ := json.Marshal(map[string]any{"command": `test -f export-ignored.txt && test -L source-link && test -L escape-link && test -d vendor/gitlink && grep -F '$Format:%H$' subst.txt && grep -Fx 'original-filter-bytes' filtered.txt && cargo test --locked --quiet && printf 'SNAPSHOT=%s\nSCRATCH=%s\nTARGET=%s\n' "$YCC_REVIEW_SNAPSHOT_ID" "$YCC_REVIEW_SCRATCH" "$CARGO_TARGET_DIR"`, "source_bound": true, "timeout_s": 120})
	res := dispatch(t, reg, "Bash", string(args))
	if !strings.Contains(res.Content, "SNAPSHOT=fixture-snapshot") {
		t.Fatalf("cargo verification did not carry snapshot identity:\n%s", res.Content)
	}
	if !strings.Contains(res.Content, "test result: ok") {
		t.Fatalf("cargo fixture did not test captured source successfully:\n%s", res.Content)
	}
	if !strings.Contains(res.Content, "review source: exact Git tree "+tree+" for assigned snapshot fixture-snapshot") {
		t.Fatalf("source-bound receipt did not identify the captured tree:\n%s", res.Content)
	}
	if _, err := os.Stat(smudgeMarker); !os.IsNotExist(err) {
		t.Fatalf("checkout smudge filter ran during pre-confinement materialization: %v", err)
	}
	inspectArgs, _ := json.Marshal(map[string]any{"command": `grep -F 'live worktree must not be built' src/lib.rs`})
	inspection := dispatch(t, reg, "Bash", string(inspectArgs))
	if !strings.Contains(inspection.Content, "no source-bound verification claim") {
		t.Fatalf("live inspection was presented as snapshot verification:\n%s", inspection.Content)
	}
	var scratchPath, targetPath string
	for _, line := range strings.Split(res.Content, "\n") {
		if strings.HasPrefix(line, "SCRATCH=") {
			scratchPath = strings.TrimPrefix(line, "SCRATCH=")
		}
		if strings.HasPrefix(line, "TARGET=") {
			targetPath = strings.TrimPrefix(line, "TARGET=")
		}
	}
	if scratchPath == "" || targetPath == "" || !strings.HasPrefix(targetPath, scratchPath+string(filepath.Separator)) {
		t.Fatalf("Cargo target was not confined to private scratch: scratch=%q target=%q", scratchPath, targetPath)
	}
	if _, err := os.Stat(scratchPath); !os.IsNotExist(err) {
		t.Fatalf("private scratch was not cleaned: %v", err)
	}
	if got, err := os.ReadFile(stale); err != nil || string(got) != "#!/bin/sh\nexit 0\n" {
		t.Fatalf("stale workspace artifact changed or disappeared: %q, %v", got, err)
	}

	preserved := []string{"src/lib.rs", "Cargo.lock", ".git/index", "unrelated.txt"}
	before := make(map[string]string, len(preserved))
	beforeMode := make(map[string]os.FileMode, len(preserved))
	for _, name := range preserved {
		path := filepath.Join(root, name)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		info, err := os.Stat(path)
		if err != nil {
			t.Fatal(err)
		}
		before[name] = string(data)
		beforeMode[name] = info.Mode().Perm()
	}
	mutationArgs, _ := json.Marshal(map[string]any{"command": `: > src/lib.rs; : > Cargo.lock; : > .git/index; printf mutation > unrelated.txt; chmod 0777 src/lib.rs Cargo.lock .git/index unrelated.txt`})
	mutation := dispatch(t, reg, "Bash", string(mutationArgs))
	if !strings.Contains(mutation.Content, "exit") {
		t.Fatalf("source mutation did not report failure: %s", mutation.Content)
	}
	for _, name := range preserved {
		path := filepath.Join(root, name)
		after, err := os.ReadFile(path)
		if err != nil || string(after) != before[name] {
			t.Fatalf("%s bytes changed under reviewer sandbox: %v", name, err)
		}
		info, err := os.Stat(path)
		if err != nil {
			t.Fatalf("stat %s after reviewer command: %v", name, err)
		}
		if info.Mode().Perm() != beforeMode[name] {
			t.Fatalf("%s mode changed under reviewer sandbox: got %v want %v", name, info.Mode().Perm(), beforeMode[name])
		}
	}

	escapeArgs, _ := json.Marshal(map[string]any{"command": `printf escaped > escape-link`, "source_bound": true})
	escapeResult := dispatch(t, reg, "Bash", string(escapeArgs))
	if !strings.Contains(escapeResult.Content, "exit") {
		t.Fatalf("source symlink escape did not fail: %s", escapeResult.Content)
	}
	if got, err := os.ReadFile(filepath.Join(root, "unrelated.txt")); err != nil || string(got) != before["unrelated.txt"] {
		t.Fatalf("source symlink modified original workspace: %q, %v", got, err)
	}

	// A source-bound run receives a writable exact-tree materialization, supporting
	// projects whose build scripts genuinely require source-local writes without
	// relaxing protection on the original workspace.
	fallbackArgs, _ := json.Marshal(map[string]any{"command": `printf generated > source-local.txt && cargo test --locked --quiet`, "source_bound": true, "timeout_s": 120})
	fallback := dispatch(t, reg, "Bash", string(fallbackArgs))
	if !strings.Contains(fallback.Content, "test result: ok") {
		t.Fatalf("exact-tree writable source failed:\n%s", fallback.Content)
	}
	if _, err := os.Stat(filepath.Join(root, "source-local.txt")); !os.IsNotExist(err) {
		t.Fatalf("fallback wrote its source-local artifact to original workspace: %v", err)
	}

	// A prior successful source-bound command cannot authorize an unrelated stale
	// binary run from the live worktree.
	staleRun := dispatch(t, reg, "Bash", `{"command":"./target/debug/stale-sentinel"}`)
	if strings.Contains(staleRun.Content, "review execution receipt:") {
		t.Fatalf("unbound stale binary received a source-bound receipt:\n%s", staleRun.Content)
	}
	staleSubmit := dispatch(t, reg, "submit_review", `{
		"verdict":"accept","summary":"stale",
		"verification":[{"classification":"independently_rebuilt_and_executed","evidence":"./target/debug/stale-sentinel passed"}]
	}`)
	var staleReport struct {
		Verification []struct {
			Classification string `json:"classification"`
		} `json:"verification"`
	}
	if err := json.Unmarshal([]byte(staleSubmit.Structured.(*Control).Report), &staleReport); err != nil {
		t.Fatal(err)
	}
	if len(staleReport.Verification) != 1 || staleReport.Verification[0].Classification != "unavailable" {
		t.Fatalf("stale unbound binary borrowed source-bound provenance: %+v", staleReport.Verification)
	}

	// A source-bound test command that really executes but returns nonzero still
	// receives a trusted execution receipt and is classified as executed.
	failedArgs, _ := json.Marshal(map[string]any{"command": `cargo test --quiet intentional_failure -- --ignored`, "source_bound": true, "timeout_s": 120})
	failed := dispatch(t, reg, "Bash", string(failedArgs))
	failedReceipt := reviewReceiptID(failed.Content)
	if failedReceipt == "" || !strings.Contains(failed.Content, "result exit 101") {
		t.Fatalf("failing source-bound test lacked nonzero execution receipt:\n%s", failed.Content)
	}
	submitArgs, _ := json.Marshal(map[string]any{
		"verdict": "revise", "summary": "test failed",
		"verification": []map[string]any{{"classification": "independently_rebuilt_and_executed", "evidence": "failure", "receipt_id": failedReceipt}},
	})
	failedSubmit := dispatch(t, reg, "submit_review", string(submitArgs))
	var failedReport struct {
		Verification []struct {
			Classification string `json:"classification"`
			Evidence       string `json:"evidence"`
		} `json:"verification"`
	}
	if err := json.Unmarshal([]byte(failedSubmit.Structured.(*Control).Report), &failedReport); err != nil {
		t.Fatal(err)
	}
	if len(failedReport.Verification) != 1 || failedReport.Verification[0].Classification != "independently_rebuilt_and_executed" || !strings.Contains(failedReport.Verification[0].Evidence, "exit 101") {
		t.Fatalf("failing bound test was not reported as executed: %+v", failedReport.Verification)
	}

	cancelScratch, _, err := reviewerScratch(root)
	if err != nil {
		t.Fatal(err)
	}
	defer cleanupReviewerScratch(cancelScratch)
	cancelCtx, cancel := context.WithCancel(context.Background())
	cancel()
	if err := materializeReviewTree(cancelCtx, root, tree, cancelScratch); !errors.Is(err, context.Canceled) {
		t.Fatalf("canceled materialization error = %v, want context.Canceled", err)
	}
}

func reviewReceiptID(content string) string {
	const prefix = "[review execution receipt: "
	start := strings.Index(content, prefix)
	if start < 0 {
		return ""
	}
	start += len(prefix)
	end := strings.IndexByte(content[start:], ';')
	if end < 0 {
		return ""
	}
	return content[start : start+end]
}

// TestResolveSymlinkEscape verifies Write/Edit reject a path that resolves out of
// the workspace through an in-workspace symlink, while normal in-workspace paths
// still work. Runs on all platforms (no sandbox needed).
func TestResolveSymlinkEscape(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()

	// A symlinked directory inside the workspace pointing outside it.
	link := filepath.Join(root, "escape")
	if err := os.Symlink(outside, link); err != nil {
		t.Fatal(err)
	}
	reg := workerReg(root)

	// Write through the symlink must be rejected.
	res := dispatch(t, reg, "Write", `{"file_path":"escape/pwned.txt","content":"x"}`)
	if !res.IsError {
		t.Fatalf("Write through symlink escape should be rejected, got: %s", res.Content)
	}
	if _, err := os.Stat(filepath.Join(outside, "pwned.txt")); !os.IsNotExist(err) {
		t.Fatalf("file was written outside the workspace via symlink: err=%v", err)
	}

	// A normal relative in-workspace path still works.
	if res := dispatch(t, reg, "Write", `{"file_path":"ok.txt","content":"hi"}`); res.IsError {
		t.Fatalf("normal Write should succeed: %s", res.Content)
	}
	// An absolute in-workspace path still works.
	abs := filepath.Join(root, "ok2.txt")
	if res := dispatch(t, reg, "Write", `{"file_path":"`+abs+`","content":"hi"}`); res.IsError {
		t.Fatalf("absolute in-workspace Write should succeed: %s", res.Content)
	}

	// Edit through the symlink must also be rejected (create a target first).
	if err := os.WriteFile(filepath.Join(outside, "t.txt"), []byte("a"), 0o644); err != nil {
		t.Fatal(err)
	}
	res = dispatch(t, reg, "Edit", `{"file_path":"escape/t.txt","old_string":"a","new_string":"b"}`)
	if !res.IsError {
		t.Fatalf("Edit through symlink escape should be rejected, got: %s", res.Content)
	}
	if got, _ := os.ReadFile(filepath.Join(outside, "t.txt")); string(got) != "a" {
		t.Fatalf("Edit modified a file outside the workspace via symlink: %q", got)
	}
}
