import PhotosUI
import SwiftUI
import UIKit
import YccKit

/// Read-only-plus-interactive session transcript feed — the projection of the
/// event log (docs/design/ios-client.md §6 phase 1 steps 3–4). Live sessions
/// stream via `Subscribe`; persisted sessions load once via
/// `GetSessionTranscript`. The heavy lifting (folding, reconnect, actions) lives
/// in ``SessionViewModel``; this view is a thin renderer.
///
/// Interactions (task 0183): a sticky input bar (`SendInput`), an answer sheet
/// for `ask_user` (`AnswerQuestion`/`AnswerQuestions`), and an overflow menu for
/// interrupt/resume/stop. Chrome (banners) reflects the derived session phase.
struct SessionView: View {
    @Environment(AppModel.self) private var app
    @Environment(\.scenePhase) private var scenePhase

    @State private var model: SessionViewModel
    @FocusState private var composerFocused: Bool
    /// Whether new content should keep the feed pinned to its newest row. This is
    /// deliberately separate from `isAtBottom`: the bottom marker can disappear
    /// briefly when the keyboard/composer changes the viewport or a streaming row
    /// grows, neither of which is a user request to stop following.
    @State private var isFollowingLatest = true
    /// Whether the tail marker is currently inside the lazily rendered viewport.
    @State private var isAtBottom = true
    /// Suppresses marker-driven re-follow while the user is actively scrolling.
    @State private var isDraggingTranscript = false
    /// Current transcript viewport height. Keyboard and multiline-composer
    /// changes resize this even when the row data itself does not change.
    @State private var transcriptViewportHeight: CGFloat = 0
    /// Monotonic token used to coalesce the many scroll requests generated by a
    /// streaming turn into one post-layout jump, without overlapping animations.
    @State private var scrollRequest = 0
    /// Draft text and pictures in the input bar.
    @State private var draft = ""
    @State private var photoItems: [PhotosPickerItem] = []
    @State private var pictures: [DraftPicture] = []
    @State private var loadingPictures = false
    /// Whether the answer sheet is shown (decoupled from `pendingQuestion` so a
    /// swipe-dismiss can hide it while the pending gate persists — reopen via the
    /// banner).
    @State private var showQuestionSheet = false
    /// Whether the destructive stop confirmation is shown.
    @State private var showStopConfirm = false
    /// Whether the per-session settings sheet is shown.
    @State private var showSettings = false
    /// A commit to drill into via the diff viewer (set by tapping a commit row).
    @State private var commitTarget: CommitDiffTarget?

    private let client: YccClient
    private let project: String
    private let sessionID: String
    private let navigationTitle: String
    private static let bottomAnchor = "transcript-bottom"
    private static let maxPictures = 4
    private static let maxPictureBytes = 5 * 1_024 * 1_024

    private struct DraftPicture: Identifiable {
        let id = UUID()
        let image: MessageImage
        let preview: UIImage
    }

    init(client: YccClient, project: String = "", sessionID: String, live: Bool) {
        self.client = client
        self.project = project
        self.sessionID = sessionID
        _model = State(initialValue: SessionViewModel(
            source: client, project: project, sessionID: sessionID,
            mode: live ? .live : .persisted))
        self.navigationTitle = live ? "Live session" : "Session"
    }

    var body: some View {
        ScrollViewReader { proxy in
            ZStack(alignment: .bottom) {
                transcript
                if !isFollowingLatest {
                    jumpToLatestPill(proxy: proxy)
                        .padding(.bottom, 12)
                        .transition(.move(edge: .bottom).combined(with: .opacity))
                }
            }
            .animation(.default, value: isFollowingLatest)
            .onChange(of: model.rows) { _, _ in
                requestScrollToLatest()
            }
            .onChange(of: transcriptViewportHeight) { _, _ in
                requestScrollToLatest()
            }
            .onChange(of: composerFocused) { _, _ in
                requestScrollToLatest()
            }
            .onChange(of: scrollRequest) { _, request in
                guard isFollowingLatest else { return }
                Task { @MainActor in
                    // Let LazyVStack, the keyboard safe area, and the composer all
                    // finish the current layout pass. A newer request supersedes us.
                    await Task.yield()
                    guard request == scrollRequest, isFollowingLatest else { return }
                    proxy.scrollTo(Self.bottomAnchor, anchor: .bottom)
                    // Keyboard presentation is animated over several layout passes;
                    // settle once more after it reaches its final safe-area height.
                    if composerFocused {
                        try? await Task.sleep(nanoseconds: 300_000_000)
                        guard request == scrollRequest, isFollowingLatest else { return }
                        proxy.scrollTo(Self.bottomAnchor, anchor: .bottom)
                    }
                }
            }
        }
        .navigationTitle(navigationTitle)
        .navigationBarTitleDisplayMode(.inline)
        .toolbar { statusToolbar }
        .toolbar { if model.mode == .live { actionMenu } }
        .navigationDestination(item: $commitTarget) { target in
            DiffView(
                title: "Commit \(target.shortSha)",
                content: .commit(project: project, sha: target.sha))
        }
        .safeAreaInset(edge: .bottom) { bottomChrome }
        .sheet(isPresented: $showSettings) {
            SessionSettingsView(
                client: client,
                sessionID: sessionID,
                currentInteractionLevel: model.interactionLevel)
        }
        .sheet(isPresented: $showQuestionSheet) {
            if let pending = model.pendingQuestion {
                QuestionSheet(
                    pending: pending,
                    onAnswerSingle: { optionIndex, text in
                        if optionIndex >= 0 { await model.answer(optionIndex: optionIndex) }
                        else { await model.answer(text: text) }
                    },
                    onAnswerBatch: { answers in await model.answerBatch(answers) }
                )
            }
        }
        // Present/dismiss the sheet as the pending gate opens and clears — the
        // event stream is the source of truth (answering here or elsewhere emits
        // `question_answered`, which clears `pendingQuestion`).
        .onChange(of: model.pendingQuestion?.rowID) { _, rowID in
            showQuestionSheet = (rowID != nil)
        }
        .alert(
            "Action failed",
            isPresented: Binding(
                get: { model.actionError != nil },
                set: { if !$0 { model.actionError = nil } }
            ),
            presenting: model.actionError
        ) { _ in
            Button("OK", role: .cancel) { model.actionError = nil }
        } message: { message in
            Text(message)
        }
        .confirmationDialog(
            "Stop this session?",
            isPresented: $showStopConfirm,
            titleVisibility: .visible
        ) {
            Button("Stop session", role: .destructive) {
                Task { await model.stopSession() }
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("This hard-terminates the agent — there is no resume.")
        }
        .task { model.start() }
        .onDisappear { model.stop() }
        .onChange(of: scenePhase) { _, phase in
            if phase == .active { model.reconnect() }
        }
    }

    // MARK: - Bottom chrome (banner + input bar)

    @ViewBuilder
    private var bottomChrome: some View {
        VStack(spacing: 0) {
            if model.mode == .live {
                pendingQuestionBanner
                phaseBanner
            } else {
                banner(
                    "Reopen this session to continue the conversation",
                    systemImage: "clock.arrow.circlepath",
                    tint: .secondary
                )
            }
            inputBar
        }
        .background(.bar)
    }

    /// When a question is pending but the sheet was swipe-dismissed, offer a way
    /// back in (the transcript row also still shows it as waiting).
    @ViewBuilder
    private var pendingQuestionBanner: some View {
        if model.pendingQuestion != nil, !showQuestionSheet {
            banner(
                "A question is waiting",
                systemImage: "questionmark.bubble.fill",
                tint: .orange,
                action: ("Answer", { showQuestionSheet = true })
            )
        }
    }

    @ViewBuilder
    private var phaseBanner: some View {
        switch model.phase {
        case .paused:
            banner(
                "Paused — send a steer or Resume",
                systemImage: "pause.circle.fill",
                tint: .orange,
                action: ("Resume", { Task { await model.resumeSession() } })
            )
        case .idle:
            banner("Session idle", systemImage: "moon.zzz.fill", tint: .secondary)
        case .error(let message):
            banner(
                message.isEmpty ? "Session error" : "Error: \(message)",
                systemImage: "exclamationmark.triangle.fill",
                tint: .red
            )
        case .stopped:
            banner("Session stopped", systemImage: "stop.circle.fill", tint: .secondary)
        case .running:
            EmptyView()
        }
    }

    private func banner(
        _ text: String,
        systemImage: String,
        tint: Color,
        action: (title: String, run: () -> Void)? = nil
    ) -> some View {
        HStack(spacing: 8) {
            Image(systemName: systemImage).foregroundStyle(tint)
            Text(text).font(.caption).foregroundStyle(.secondary)
            Spacer()
            if let action {
                Button(action.title, action: action.run)
                    .font(.caption.weight(.semibold))
                    .buttonStyle(.bordered)
                    .controlSize(.small)
            }
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 6)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(tint.opacity(0.08))
    }

    private var inputBar: some View {
        VStack(alignment: .leading, spacing: 6) {
            if !pictures.isEmpty {
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack(spacing: 8) {
                        ForEach(pictures) { picture in
                            ZStack(alignment: .topTrailing) {
                                Image(uiImage: picture.preview)
                                    .resizable().scaledToFill()
                                    .frame(width: 64, height: 64).clipped()
                                    .clipShape(RoundedRectangle(cornerRadius: 8))
                                Button {
                                    pictures.removeAll { $0.id == picture.id }
                                } label: {
                                    Image(systemName: "xmark.circle.fill")
                                        .symbolRenderingMode(.palette)
                                        .foregroundStyle(.white, .black.opacity(0.7))
                                }
                                .offset(x: 5, y: -5)
                                .accessibilityLabel("Remove picture")
                            }
                        }
                    }
                    .padding(.top, 5)
                }
            }
            HStack(spacing: 8) {
                PhotosPicker(
                    selection: $photoItems,
                    maxSelectionCount: Self.maxPictures,
                    matching: .images
                ) {
                    Image(systemName: loadingPictures ? "hourglass" : "photo.on.rectangle")
                        .font(.title3)
                }
                .disabled(loadingPictures)
                .accessibilityLabel("Add pictures")
                .onChange(of: photoItems) { _, items in
                    Task { await loadPictures(items) }
                }
                TextField("Message…", text: $draft, axis: .vertical)
                    .textFieldStyle(.roundedBorder)
                    .lineLimit(1...5)
                    .focused($composerFocused)
                    .onSubmit(send)
                Button(action: send) {
                    Image(systemName: "arrow.up.circle.fill")
                        .font(.title2)
                }
                .disabled(
                    loadingPictures ||
                    (draft.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && pictures.isEmpty)
                )
            }
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 8)
    }

    @MainActor
    private func loadPictures(_ items: [PhotosPickerItem]) async {
        loadingPictures = true
        defer { loadingPictures = false; photoItems = [] }
        var loaded: [DraftPicture] = []
        do {
            for (index, item) in items.prefix(Self.maxPictures).enumerated() {
                guard let source = try await item.loadTransferable(type: Data.self),
                      let uiImage = UIImage(data: source) else {
                    throw PictureError.unreadable
                }
                // Normalize to JPEG so HEIC and other Photos formats have a
                // model-supported wire type, while preserving a useful preview.
                guard let data = uiImage.jpegData(compressionQuality: 0.85) else {
                    throw PictureError.unreadable
                }
                guard data.count <= Self.maxPictureBytes else {
                    throw PictureError.tooLarge
                }
                loaded.append(DraftPicture(
                    image: MessageImage(
                        data: data, mediaType: "image/jpeg", filename: "photo-\(index + 1).jpg"),
                    preview: uiImage))
            }
            pictures = loaded
        } catch {
            pictures = []
            model.actionError = error.localizedDescription
        }
    }

    private func send() {
        let text = draft
        let images = pictures.map(\.image)
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || !images.isEmpty else { return }
        draft = ""
        pictures = []
        Task { await model.send(text: text, images: images) }
    }

    private enum PictureError: LocalizedError {
        case unreadable, tooLarge
        var errorDescription: String? {
            switch self {
            case .unreadable: return "One of the selected pictures could not be read."
            case .tooLarge: return "A selected picture is larger than 5 MB after encoding."
            }
        }
    }

    private var transcript: some View {
        ScrollView {
            LazyVStack(alignment: .leading, spacing: 10) {
                if model.rows.isEmpty, model.state == .loading {
                    ProgressView().frame(maxWidth: .infinity).padding(.top, 40)
                }
                ForEach(model.rows) { row in
                    TranscriptRowView(row: row) { sha in
                        commitTarget = CommitDiffTarget(sha: sha)
                    }
                    .id(row.id)
                }
                // A small lazy-stack marker tells us when the latest content is
                // visible. Its disappearance alone does NOT disable following:
                // live-tail growth and keyboard/composer relayout also move it
                // out of view transiently. Only an actual drag does that.
                Color.clear
                    .frame(height: 1)
                    .id(Self.bottomAnchor)
                    .onAppear {
                        isAtBottom = true
                        if !isDraggingTranscript { isFollowingLatest = true }
                    }
                    .onDisappear {
                        isAtBottom = false
                        if isDraggingTranscript { isFollowingLatest = false }
                    }
            }
            .padding()
        }
        .simultaneousGesture(
            DragGesture(minimumDistance: 4)
                .onChanged { _ in isDraggingTranscript = true }
                .onEnded { _ in
                    // `onDisappear` normally disables following during the drag.
                    // Do not decide from the marker here: deceleration continues
                    // after this callback, so the marker may not have settled yet.
                    isDraggingTranscript = false
                }
        )
        .background {
            GeometryReader { geometry in
                Color.clear
                    .onAppear { transcriptViewportHeight = geometry.size.height }
                    .onChange(of: geometry.size.height) { _, height in
                        transcriptViewportHeight = height
                    }
            }
        }
        // Open at the newest row, like a chat. Subsequent pinning is explicit so
        // SwiftUI never has competing implicit anchoring and scroll animations.
        .defaultScrollAnchor(.bottom)
    }

    private func requestScrollToLatest() {
        guard isFollowingLatest else { return }
        scrollRequest &+= 1
    }

    private func jumpToLatestPill(proxy: ScrollViewProxy) -> some View {
        Button {
            isFollowingLatest = true
            proxy.scrollTo(Self.bottomAnchor, anchor: .bottom)
        } label: {
            Label("Jump to latest", systemImage: "arrow.down")
                .font(.subheadline.weight(.semibold))
                .padding(.horizontal, 14)
                .padding(.vertical, 8)
                .background(.thinMaterial, in: Capsule())
                .overlay(Capsule().strokeBorder(.quaternary))
        }
        .buttonStyle(.plain)
    }

    @ToolbarContentBuilder
    private var statusToolbar: some ToolbarContent {
        ToolbarItem(placement: .topBarTrailing) {
            switch model.state {
            case .streaming:
                Label("Live", systemImage: "dot.radiowaves.left.and.right")
                    .labelStyle(.iconOnly)
                    .foregroundStyle(.green)
            case .reconnecting, .loading:
                ProgressView()
            case .failed:
                Image(systemName: "exclamationmark.triangle.fill")
                    .foregroundStyle(.orange)
            case .idle, .finished:
                EmptyView()
            }
        }
    }

    @ToolbarContentBuilder
    private var actionMenu: some ToolbarContent {
        ToolbarItem(placement: .topBarTrailing) {
            Button {
                showSettings = true
            } label: {
                Image(systemName: "gearshape")
            }
        }
        ToolbarItem(placement: .topBarTrailing) {
            Menu {
                Button {
                    Task { await model.interrupt() }
                } label: {
                    Label("Interrupt", systemImage: "pause.circle")
                }
                Button {
                    Task { await model.resumeSession() }
                } label: {
                    Label("Resume", systemImage: "play.circle")
                }
                Divider()
                Button(role: .destructive) {
                    showStopConfirm = true
                } label: {
                    Label("Stop…", systemImage: "stop.circle")
                }
            } label: {
                Image(systemName: "ellipsis.circle")
            }
        }
    }
}

/// Renders a single ``TranscriptRow``. Bubbles for messages; collapsed,
/// tappable disclosure rows for thinking and tool calls; compact system rows.
private struct TranscriptRowView: View {
    let row: TranscriptRow
    /// Called with the commit sha when a `commit_made` row is tapped.
    var onOpenCommit: (String) -> Void = { _ in }

    var body: some View {
        switch row.kind {
        case .userMessage(let text):
            bubble(text: text, isUser: true)
        case .modelMessage(let text):
            bubble(text: text, isUser: false, actor: row.actor)
        case .finalReport(let text):
            finalReport(text)
        case .thinking(let text):
            ExpandableRow(
                title: "Thinking",
                systemImage: "brain",
                tint: .purple,
                detail: text
            )
        case .tool(let name, let status, let args, let output):
            ToolRowView(name: name, status: status, args: args, output: output)
        case .question(let prompt, let options, let answer):
            QuestionRowView(prompt: prompt, options: options, answer: answer)
        case .system(let text):
            systemRow(text)
        case .commit(let text, let sha):
            commitRow(text, sha: sha)
        case .liveTail(let text):
            liveTail(text)
        }
    }

    private func bubble(text: String, isUser: Bool, actor: String = "") -> some View {
        HStack {
            if isUser { Spacer(minLength: 40) }
            VStack(alignment: isUser ? .trailing : .leading, spacing: 2) {
                if !isUser, !actor.isEmpty {
                    Text(actor).font(.caption2).foregroundStyle(.secondary)
                }
                Group {
                    if isUser {
                        // User messages stay plain text — they were typed, not
                        // authored in markdown.
                        Text(text.isEmpty ? " " : text)
                    } else {
                        // Agent messages render as markdown (headings, lists,
                        // inline styles, fenced code blocks).
                        MarkdownText(text: text.isEmpty ? " " : text)
                    }
                }
                .textSelection(.enabled)
                .padding(.horizontal, 12)
                .padding(.vertical, 8)
                .background(
                    isUser ? Color.accentColor.opacity(0.85) : Color(.secondarySystemBackground),
                    in: RoundedRectangle(cornerRadius: 14)
                )
                .foregroundStyle(isUser ? .white : .primary)
            }
            if !isUser { Spacer(minLength: 40) }
        }
    }

    /// The finish message is the primary result of a session, not a lifecycle
    /// footnote: keep it always expanded, render its Markdown structure, and give
    /// it a distinct success card that remains easy to find in a long transcript.
    private func finalReport(_ text: String) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Label("Finished", systemImage: "checkmark.circle.fill")
                .font(.headline)
                .foregroundStyle(.green)
            MarkdownText(text: text)
                .textSelection(.enabled)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(14)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.green.opacity(0.09), in: RoundedRectangle(cornerRadius: 14))
        .overlay {
            RoundedRectangle(cornerRadius: 14)
                .stroke(Color.green.opacity(0.28), lineWidth: 1)
        }
        .accessibilityElement(children: .contain)
        .accessibilityLabel("Session finished")
    }

    private func systemRow(_ text: String) -> some View {
        HStack(spacing: 6) {
            Image(systemName: "circle.fill").font(.system(size: 4)).foregroundStyle(.tertiary)
            Text(text)
                .font(.caption)
                .foregroundStyle(.secondary)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    /// A commit row: like a system row, but tappable to drill into the commit's
    /// diff when a sha is present. Without a sha it degrades to a plain row.
    @ViewBuilder
    private func commitRow(_ text: String, sha: String) -> some View {
        if sha.isEmpty {
            systemRow(text)
        } else {
            Button {
                onOpenCommit(sha)
            } label: {
                HStack(spacing: 6) {
                    Image(systemName: "arrow.triangle.branch")
                        .font(.caption2)
                        .foregroundStyle(.blue)
                    Text(text)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .frame(maxWidth: .infinity, alignment: .leading)
                    Image(systemName: "chevron.right")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
            }
            .buttonStyle(.plain)
        }
    }

    private func liveTail(_ text: String) -> some View {
        HStack {
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 4) {
                    ProgressView().scaleEffect(0.6)
                    Text("streaming").font(.caption2).foregroundStyle(.secondary)
                }
                Text(text)
                    .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(Color(.secondarySystemBackground), in: RoundedRectangle(cornerRadius: 14))
                    .foregroundStyle(.primary)
            }
            Spacer(minLength: 40)
        }
    }
}

/// A collapsed one-liner that expands to reveal detail text on tap.
private struct ExpandableRow: View {
    let title: String
    let systemImage: String
    var tint: Color = .secondary
    let detail: String

    @State private var expanded = false

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Button {
                withAnimation(.snappy) { expanded.toggle() }
            } label: {
                HStack(spacing: 6) {
                    Image(systemName: systemImage).foregroundStyle(tint)
                    Text(title).font(.caption).foregroundStyle(.secondary)
                    Spacer()
                    Image(systemName: expanded ? "chevron.up" : "chevron.down")
                        .font(.caption2).foregroundStyle(.tertiary)
                }
            }
            .buttonStyle(.plain)

            if expanded {
                Text(detail)
                    .font(.callout)
                    .textSelection(.enabled)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .padding(10)
                    .background(Color(.tertiarySystemBackground), in: RoundedRectangle(cornerRadius: 10))
            }
        }
    }
}

/// A tool call collapsed to `name + status`, expandable to args and output.
private struct ToolRowView: View {
    let name: String
    let status: TranscriptRow.ToolStatus
    let args: String
    let output: String

    @State private var expanded = false

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Button {
                withAnimation(.snappy) { expanded.toggle() }
            } label: {
                HStack(spacing: 6) {
                    Image(systemName: "wrench.and.screwdriver").foregroundStyle(.blue)
                    Text(name).font(.caption.monospaced()).foregroundStyle(.primary)
                    statusBadge
                    Spacer()
                    Image(systemName: expanded ? "chevron.up" : "chevron.down")
                        .font(.caption2).foregroundStyle(.tertiary)
                }
            }
            .buttonStyle(.plain)

            if expanded {
                VStack(alignment: .leading, spacing: 8) {
                    if !args.isEmpty { detailBlock(label: "args", text: args) }
                    if !output.isEmpty { detailBlock(label: "output", text: output) }
                }
            }
        }
    }

    private var statusBadge: some View {
        Group {
            switch status {
            case .running:
                ProgressView().scaleEffect(0.6)
            case .ok:
                Image(systemName: "checkmark.circle.fill").foregroundStyle(.green)
            case .error:
                Image(systemName: "xmark.circle.fill").foregroundStyle(.red)
            }
        }
        .font(.caption2)
    }

    private func detailBlock(label: String, text: String) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(label).font(.caption2).foregroundStyle(.secondary)
            Text(text)
                .font(.caption.monospaced())
                .textSelection(.enabled)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(8)
                .background(Color(.tertiarySystemBackground), in: RoundedRectangle(cornerRadius: 8))
        }
    }
}

/// A pending or resolved `ask_user` question row.
private struct QuestionRowView: View {
    let prompt: String
    let options: [String]
    let answer: String?

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 6) {
                Image(systemName: "questionmark.bubble").foregroundStyle(.orange)
                Text(prompt).font(.callout.weight(.medium))
            }
            if !options.isEmpty {
                ForEach(Array(options.enumerated()), id: \.offset) { _, option in
                    Text("• \(option)").font(.caption).foregroundStyle(.secondary)
                }
            }
            if let answer, !answer.isEmpty {
                Text("Answered: \(answer)")
                    .font(.caption)
                    .foregroundStyle(.green)
            } else {
                Text("Waiting for an answer")
                    .font(.caption2)
                    .foregroundStyle(.orange)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(10)
        .background(Color.orange.opacity(0.08), in: RoundedRectangle(cornerRadius: 10))
        .overlay(RoundedRectangle(cornerRadius: 10).strokeBorder(Color.orange.opacity(0.3)))
    }
}

/// The answer sheet for a pending `ask_user` gate. A single question offers its
/// suggested options as buttons plus a free-text field (`AnswerQuestion`). A
/// batch renders one section per question and submits positionally
/// (`AnswerQuestions`, `answers[i]`). The sheet auto-dismisses when the gate
/// clears (answered here or from another client) via the parent's `onChange`.
private struct QuestionSheet: View {
    let pending: SessionProjection.PendingQuestion
    /// (optionIndex, text): optionIndex >= 0 selects an option, -1 sends text.
    let onAnswerSingle: (Int, String) async -> Void
    /// Positional batch answers.
    let onAnswerBatch: ([(text: String, optionIndex: Int)]) async -> Void

    @Environment(\.dismiss) private var dismiss
    /// Per-question free-text drafts.
    @State private var texts: [String]
    /// Per-question selected option index (-1 = none).
    @State private var selected: [Int]

    init(
        pending: SessionProjection.PendingQuestion,
        onAnswerSingle: @escaping (Int, String) async -> Void,
        onAnswerBatch: @escaping ([(text: String, optionIndex: Int)]) async -> Void
    ) {
        self.pending = pending
        self.onAnswerSingle = onAnswerSingle
        self.onAnswerBatch = onAnswerBatch
        _texts = State(initialValue: Array(repeating: "", count: pending.questions.count))
        _selected = State(initialValue: Array(repeating: -1, count: pending.questions.count))
    }

    var body: some View {
        NavigationStack {
            Form {
                ForEach(Array(pending.questions.enumerated()), id: \.offset) { index, question in
                    Section {
                        ForEach(Array(question.options.enumerated()), id: \.offset) { optIdx, option in
                            optionRow(index: index, optIdx: optIdx, option: option)
                        }
                        TextField("Type an answer…", text: binding(index), axis: .vertical)
                            .lineLimit(1...4)
                            .onChange(of: texts[index]) { _, newValue in
                                // Typing overrides a picked option.
                                if !newValue.isEmpty { selected[index] = -1 }
                            }
                        if !pending.isBatch {
                            singleSendSection
                        }
                    } header: {
                        Text(question.prompt)
                    }
                }
            }
            .navigationTitle(pending.isBatch ? "Answer questions" : "Answer")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                if pending.isBatch {
                    ToolbarItem(placement: .confirmationAction) {
                        Button("Submit") { submitBatch() }
                            .disabled(!allAnswered)
                    }
                }
            }
        }
    }

    private func optionRow(index: Int, optIdx: Int, option: String) -> some View {
        Button {
            if pending.isBatch {
                selected[index] = optIdx
                texts[index] = ""
            } else {
                // Single question: an option tap answers immediately.
                Task {
                    await onAnswerSingle(optIdx, "")
                    dismiss()
                }
            }
        } label: {
            HStack {
                Text(option)
                Spacer()
                if pending.isBatch, selected[index] == optIdx {
                    Image(systemName: "checkmark").foregroundStyle(.tint)
                }
            }
        }
    }

    /// A binding to a per-question text draft, with a trailing send button for
    /// the single-question case.
    private func binding(_ index: Int) -> Binding<String> {
        Binding(get: { texts[index] }, set: { texts[index] = $0 })
    }

    /// For a single question, provide an inline send action for free text.
    private var singleSendSection: some View {
        Button("Send") {
            Task {
                await onAnswerSingle(-1, texts[0])
                dismiss()
            }
        }
        .disabled(texts.first?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true)
    }

    private var allAnswered: Bool {
        for i in pending.questions.indices {
            let hasText = !texts[i].trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            if selected[i] < 0 && !hasText { return false }
        }
        return true
    }

    private func submitBatch() {
        let answers: [(text: String, optionIndex: Int)] = pending.questions.indices.map { i in
            if selected[i] >= 0 { return (text: "", optionIndex: selected[i]) }
            return (text: texts[i], optionIndex: -1)
        }
        Task {
            await onAnswerBatch(answers)
            dismiss()
        }
    }
}

/// A commit to drill into via the diff viewer, from a tapped `commit_made` row.
/// `Identifiable` drives `navigationDestination(item:)`.
private struct CommitDiffTarget: Identifiable, Hashable {
    let sha: String
    var id: String { sha }
    /// A short display sha for the nav title (first 8 chars).
    var shortSha: String { String(sha.prefix(8)) }
}
