import SwiftUI
import UIKit
import YccKit

/// Read-only-plus-interactive session transcript feed projected from the event
/// log. Live sessions
/// stream via `Subscribe`; persisted sessions load once via
/// `GetSessionTranscript`. The heavy lifting (folding, reconnect, actions) lives
/// in ``SessionViewModel``; this view is a thin renderer.
///
/// Interactions: a sticky input bar (`SendInput`), an answer sheet
/// for `ask_user` (`AnswerQuestion`/`AnswerQuestions`), and an overflow menu for
/// interrupt/resume/stop. Chrome (banners) reflects the derived session phase.
struct SessionView: View {
    @Environment(AppModel.self) private var app
    @Environment(HomeRouter.self) private var router
    @Environment(\.scenePhase) private var scenePhase

    @State private var model: SessionViewModel
    /// Focus mirror for the composer field (a plain Bool rather than
    /// `@FocusState` because the field is the UIKit-backed `ComposerTextField`,
    /// which exists so an image on the clipboard can be pasted in-field).
    @State private var composerFocused = false
    /// Keyboard overlap for manual avoidance of the bottom chrome — see
    /// KeyboardObserver for why the automatic keyboard safe area is not used.
    @StateObject private var keyboard = KeyboardObserver()
    /// Whether new content should keep the feed pinned to its newest row. The
    /// bottom marker can disappear briefly when the keyboard/composer changes the
    /// viewport or a streaming row grows, neither of which is a user request to
    /// stop following.
    @State private var isFollowingLatest = true
    /// User drags opt out of follow mode while the follow-state reconciler
    /// resumes it once the live edge is visible and dragging has gone quiet.
    /// Corrective scrolls keep a following transcript pinned through late layout.
    @State private var isDraggingTranscript = false
    /// Tracks scroll intent without invalidating the view on every movement. The
    /// raw drag flag can remain set when ScrollView swallows the gesture's
    /// `onEnded`; the reconciler treats it as stale after a short interval.
    /// `sawLiveEdge` preserves that the user reached the bottom if streaming growth
    /// moves the marker away before a quiet-period reconciler gets to run.
    private final class DragActivity {
        var last = Date.distantPast
        var watchdogScheduled = false
        var sawLiveEdge = false
        var lastTopY = CGFloat.nan
    }
    @State private var dragActivity = DragActivity()
    /// Whether the transcript's bottom marker is inside the viewport. This is
    /// measured geometrically: rows live in an eager VStack, so onAppear/onDisappear
    /// describes mounting, not viewport visibility.
    @State private var isLatestVisible = true
    /// Current transcript viewport height. Keyboard and multiline-composer
    /// changes resize this even when the row data itself does not change.
    @State private var transcriptViewportHeight: CGFloat = 0
    /// Monotonic token used to coalesce the many scroll requests generated by a
    /// streaming turn into one post-layout jump, without overlapping animations.
    /// A reference box rather than view state: the revision `onChange` fires
    /// once per streamed event — often several per frame — and writing view
    /// state there trips "onChange action tried to update multiple times per
    /// frame".
    private final class ScrollToken { var value = 0 }
    @State private var scrollToken = ScrollToken()
    /// Draft text and pictures in the input bar. The picker/thumbnail
    /// affordances themselves live in `PictureComposer.swift`, shared with the
    /// new-session composer.
    @State private var draft = ""
    @State private var pictures: [DraftPicture] = []
    @State private var loadingPictures = false
    /// Pulsed true for one runloop turn right after a send. UIKit commits a
    /// pending autocorrection *after* the send action returns and writes the
    /// corrected string back into the binding, which is why a composer that was
    /// just cleared sometimes still shows the message that was sent. Turning
    /// autocorrection off for a beat makes UIKit discard that pending correction
    /// instead of committing it (see `send()`).
    @State private var suppressAutocorrect = false
    /// Whether the answer sheet is shown (decoupled from `pendingQuestion` so a
    /// swipe-dismiss can hide it while the pending gate persists — reopen via the
    /// banner).
    @State private var showQuestionSheet = false
    /// Whether the destructive stop confirmation is shown.
    @State private var showStopConfirm = false
    /// Whether the per-session settings sheet is shown.
    @State private var showSettings = false
    /// Presents the per-session usage sheet.
    @State private var showSessionUsage = false
    /// A commit to drill into via the diff viewer (set by tapping a commit row).
    @State private var commitTarget: CommitDiffTarget?

    private let client: YccClient
    private let project: String
    private let sessionID: String
    /// The display name carried in from the list, so the pushed screen is
    /// identifiable before (or without) any event arriving.
    private let title: String
    private static let bottomAnchor = "transcript-bottom"
    private static let transcriptCoordinateSpace = "transcript-scroll"
    private static let dragQuietPeriod: TimeInterval = 0.35
    private static let dragActivityStalePeriod: TimeInterval = 1.0
    init(client: YccClient, project: String = "", sessionID: String, live: Bool, title: String = "") {
        self.client = client
        self.project = project
        self.sessionID = sessionID
        _model = State(initialValue: SessionViewModel(
            source: client, project: project, sessionID: sessionID,
            mode: live ? .live : .persisted))
        let trimmed = title.trimmingCharacters(in: .whitespacesAndNewlines)
        self.title = trimmed.isEmpty
            ? (live ? "Live session" : "Session")
            : trimmed
    }

    var body: some View {
        ScrollViewReader { proxy in
            ZStack(alignment: .bottom) {
                transcript(proxy: proxy)
                if !isFollowingLatest {
                    jumpToLatestPill(proxy: proxy)
                        .padding(.bottom, 12)
                        .transition(.move(edge: .bottom).combined(with: .opacity))
                }
            }
            .animation(.default, value: isFollowingLatest)
            // A scalar revision avoids deep equality checks over every transcript
            // row (including the growing live-tail string) for each streamed delta.
            .onChange(of: model.transcriptRevision, initial: true) { _, _ in
                requestScrollToLatest(proxy: proxy)
            }
            .onChange(of: transcriptViewportHeight) { _, _ in
                requestScrollToLatest(proxy: proxy)
            }
            .onChange(of: composerFocused) { _, _ in
                requestScrollToLatest(proxy: proxy)
            }
        }
        .navigationTitle(title)
        .navigationBarTitleDisplayMode(.inline)
        // The transcript scrolls the full height of the screen, so without an
        // opaque bar its text bleeds through behind the status bar and title.
        .toolbarBackground(.visible, for: .navigationBar)
        .toolbar { titleToolbar }
        .toolbar { backlogShortcut }
        .toolbar { actionMenu }
        .navigationDestination(item: $commitTarget) { target in
            DiffView(
                title: "Commit \(target.shortSha)",
                content: .commit(project: project, sha: target.sha))
        }
        .safeAreaInset(edge: .bottom) { bottomChrome }
        // Manual keyboard avoidance (see KeyboardObserver): the automatic
        // keyboard safe area under a bottom `safeAreaInset` can get stuck after
        // sheet dismissals/navigation races (open SwiftUI bug, FB13296535),
        // stranding the input bar mid-screen with no keyboard beneath it. Opt
        // the whole screen out of the keyboard safe area and let `bottomChrome`
        // pad itself by the observed keyboard overlap instead.
        .ignoresSafeArea(.keyboard, edges: .bottom)
        .sheet(isPresented: $showSettings) {
            SessionSettingsView(
                client: client, sessionID: sessionID, coordinator: model.coordinatorModel)
        }
        .sheet(isPresented: $showSessionUsage) {
            SessionUsageSheet(
                client: client,
                project: project,
                sessionID: sessionID,
                currentContextTokensEstimate: model.currentContextTokensEstimate)
        }
        .sheet(isPresented: $showQuestionSheet) {
            if let pending = model.pendingQuestion {
                QuestionSheet(
                    pending: pending,
                    onAnswerSingle: { optionIndex, text in
                        if optionIndex >= 0 { await model.answer(optionIndex: optionIndex) }
                        else { await model.answer(text: text) }
                        noteAnswered()
                    },
                    onAnswerBatch: { answers in
                        await model.answerBatch(answers)
                        noteAnswered()
                    }
                )
                // Tie the sheet's identity to the gate: if `pendingQuestion`
                // changes shape while the sheet is open (e.g. a reopened session's
                // resumed agent asks a differently-sized batch), a new `rowID`
                // rebuilds QuestionSheet with correctly-sized @State instead of
                // reusing stale `texts`/`selected` arrays and trapping on an
                // out-of-range index.
                .id(pending.rowID)
            }
        }
        // Present/dismiss the sheet as the pending gate opens and clears — the
        // event stream is the source of truth (answering here or elsewhere emits
        // `question_answered`, which clears `pendingQuestion`).
        .onChange(of: model.pendingQuestion?.rowID) { _, rowID in
            showQuestionSheet = (rowID != nil)
        }
        .alert(
            "Action failed",
            isPresented: Binding(
                get: { model.actionError != nil },
                set: { if !$0 { model.actionError = nil } }
            ),
            presenting: model.actionError
        ) { _ in
            Button("OK", role: .cancel) { model.actionError = nil }
        } message: { message in
            Text(message)
        }
        .confirmationDialog(
            "Stop this session?",
            isPresented: $showStopConfirm,
            titleVisibility: .visible
        ) {
            Button("Stop session", role: .destructive) {
                Task { await model.stopSession() }
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("This hard-terminates the agent — there is no resume.")
        }
        .task { model.start() }
        .onDisappear {
            // Leaving the transcript is the moment the user has "read" it: record
            // the newest event they were shown, so later agent activity — a turn
            // that lands, or the session finishing while the phone is away —
            // shows up as unread on the list.
            markRead()
            model.stop()
        }
        .onChange(of: scenePhase) { _, phase in
            if phase == .active {
                model.reconnect()
            } else {
                // Backgrounding may be the last thing that happens to this view;
                // don't leave what is on screen counted as unread.
                markRead()
            }
        }
    }

    /// Record everything folded so far as seen for this session.
    private func markRead() {
        app.readMarks.markRead(
            sessionID: sessionID, through: model.lastEventTimestamp)
    }

    // MARK: - Bottom chrome (banner + input bar)

    @ViewBuilder
    private var bottomChrome: some View {
        VStack(spacing: 0) {
            if model.mode == .live {
                pendingQuestionBanner
                phaseBanner
            } else {
                banner(
                    "Reopen this session to continue the conversation",
                    systemImage: "clock.arrow.circlepath",
                    tint: .secondary
                )
            }
            inputBar
        }
        // Ride the keyboard by measured overlap (KeyboardObserver) rather than
        // the automatic keyboard safe area — see `.ignoresSafeArea(.keyboard)`
        // above. Padding sits *inside* the bar background so the material
        // covers the gap while the keyboard animates.
        .padding(.bottom, keyboard.overlap)
        .background(.bar)
    }

    /// When a question is pending but the sheet was swipe-dismissed, offer a way
    /// back in (the transcript row also still shows it as waiting).
    @ViewBuilder
    private var pendingQuestionBanner: some View {
        if model.pendingQuestion != nil, !showQuestionSheet {
            banner(
                "A question is waiting",
                systemImage: "questionmark.bubble.fill",
                tint: .orange,
                action: ("Answer", { showQuestionSheet = true })
            )
        }
    }

    @ViewBuilder
    private var phaseBanner: some View {
        switch model.phase {
        case .paused:
            banner(
                "Paused — send a steer or Resume",
                systemImage: "pause.circle.fill",
                tint: .orange,
                action: ("Resume", { Task { await model.resumeSession() } })
            )
        case .idle:
            banner("Session idle", systemImage: "moon.zzz.fill", tint: .secondary)
        case .error(let message, let retryable):
            let retryAction: (title: String, run: () -> Void)? =
                retryable ? ("Retry", { Task { await model.retry() } }) : nil
            banner(
                message.isEmpty ? "Session error" : "Error: \(message)",
                systemImage: "exclamationmark.triangle.fill",
                tint: .red,
                action: retryAction
            )
        case .stopped:
            banner("Session stopped", systemImage: "stop.circle.fill", tint: .secondary)
        case .running:
            EmptyView()
        }
    }

    private func banner(
        _ text: String,
        systemImage: String,
        tint: Color,
        action: (title: String, run: () -> Void)? = nil
    ) -> some View {
        HStack(spacing: 8) {
            Image(systemName: systemImage).foregroundStyle(tint)
            Text(text).font(.caption).foregroundStyle(.secondary)
            Spacer()
            if let action {
                Button(action.title, action: action.run)
                    .font(.caption.weight(.semibold))
                    .buttonStyle(.bordered)
                    .controlSize(.small)
            }
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 6)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(tint.opacity(0.08))
    }

    private var inputBar: some View {
        VStack(alignment: .leading, spacing: 6) {
            PictureStrip(pictures: $pictures)
            HStack(spacing: 8) {
                PicturePickerButton(pictures: $pictures, isLoading: $loadingPictures) { message in
                    model.actionError = message
                }
                ComposerTextField(
                    placeholder: "Message…",
                    text: $draft,
                    focused: $composerFocused,
                    maxLines: 5,
                    autocorrectionDisabled: suppressAutocorrect,
                    onSubmit: send,
                    onPasteImages: { images in
                        pictures = PictureComposer.load(
                            pasted: images, current: pictures
                        ) { message in
                            model.actionError = message
                        }
                    }
                )
                Button(action: send) {
                    Image(systemName: "arrow.up.circle.fill")
                        .font(.title2)
                }
                .disabled(
                    loadingPictures ||
                    (draft.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty && pictures.isEmpty)
                )
            }
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 8)
    }

    private func send() {
        let text = draft
        let images = pictures.map(\.image)
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || !images.isEmpty else { return }
        draft = ""
        pictures = []
        // Clearing the binding is not enough on its own: if the keyboard still
        // holds an uncommitted autocorrection (the user tapped send without
        // accepting or dismissing the suggestion), UIKit commits it *after* this
        // action and writes the corrected text straight back into the freshly
        // emptied field — the message goes out but the composer keeps showing it.
        // Dropping autocorrection for one runloop turn makes UIKit throw that
        // pending correction away, and the deferred re-clear mops up any
        // write-back that still lands before the pulse takes effect.
        suppressAutocorrect = true
        Task { @MainActor in
            draft = ""
            suppressAutocorrect = false
        }
        Task { await model.send(text: text, images: images) }
    }

    /// Tell the rest of the app this session's question is dealt with, so the
    /// inbox and drawer badges stop nagging before the next list refresh.
    /// Harmless if the answer failed — the next refresh restores the truth.
    @MainActor
    private func noteAnswered() {
        app.noteQuestionAnswered(sessionID: sessionID)
    }

    private func transcript(proxy: ScrollViewProxy) -> some View {
        ScrollView {
            // Keep transcript rows eagerly mounted. A LazyVStack can lose its
            // estimated content geometry when the last row changes height many
            // times per second (the streaming tail) while ScrollViewReader also
            // keeps that row pinned. The resulting stale offset presents as an
            // empty transcript until a manual scroll forces another layout pass.
            // Session rows already collapse heavy tool/thinking details, so the
            // predictable geometry is worth the modest eager-layout cost here.
            VStack(alignment: .leading, spacing: 10) {
                if model.durableRows.isEmpty, model.liveTails.isEmpty, model.state == .loading {
                    ProgressView().frame(maxWidth: .infinity).padding(.top, 40)
                }
                // Keep immutable history separate from rapidly-changing tails.
                // Building one combined array every 100ms made SwiftUI diff the
                // entire transcript for every snapshot.
                ForEach(model.durableRows) { row in
                    TranscriptRowView(
                        row: row,
                        onOpenCommit: { sha in
                            commitTarget = CommitDiffTarget(sha: sha)
                        },
                        loadPicture: { attachmentID in
                            guard !attachmentID.isEmpty,
                                  let image = try? await client.getSessionAttachment(
                                    project: project,
                                    sessionId: sessionID,
                                    attachmentId: attachmentID
                                  ) else { return nil }
                            return image.data
                        }
                    )
                    .equatable()
                    .id(row.id)
                }
                ForEach(model.liveTails) { liveTail in
                    // Each actor owns a stable subtree. Equatable rendering lets
                    // one subagent append without re-running the unchanged tails;
                    // the changed row still receives every snapshot for TextKit.
                    TranscriptRowView(row: liveTail, model: model.coordinatorModel)
                        .equatable()
                        .id(liveTail.id)
                }
                if model.liveTails.isEmpty, model.isAwaitingAgentActivity {
                    workingRow
                        .id("agent-working")
                }
                // A small marker row tells us geometrically when the latest
                // content is visible. With this eager VStack the marker remains
                // mounted while offscreen, so lifecycle callbacks cannot answer
                // that question reliably.
                Color.clear
                    .frame(height: 1)
                    .id(Self.bottomAnchor)
                    .background {
                        GeometryReader { geometry in
                            Color.clear.preference(
                                key: TranscriptBottomPreferenceKey.self,
                                value: geometry.frame(
                                    in: .named(Self.transcriptCoordinateSpace)).maxY)
                        }
                    }
            }
            .padding()
            // Content growth below leaves this top edge fixed while unpinned;
            // user scrolling changes it. That lets the reconciler distinguish a
            // deliberate scroll away from streaming layout growth.
            .background {
                GeometryReader { geometry in
                    Color.clear.preference(
                        key: TranscriptTopPreferenceKey.self,
                        value: geometry.frame(
                            in: .named(Self.transcriptCoordinateSpace)).minY)
                }
            }
        }
        .coordinateSpace(name: Self.transcriptCoordinateSpace)
        .onPreferenceChange(TranscriptBottomPreferenceKey.self) { bottomY in
            let tolerance: CGFloat = 8
            let now = Date()
            let dragAge = now.timeIntervalSince(dragActivity.last)
            // Only a currently active raw drag may stop follow here, so content
            // growth after release cannot masquerade as user scrollback. Bound the
            // flag by recency in case ScrollView swallows `onEnded`; the top-edge
            // handler intentionally uses recency alone to include deceleration.
            let dragging = isDraggingTranscript && dragAge < Self.dragActivityStalePeriod
            isLatestVisible = bottomY <= transcriptViewportHeight + tolerance
            if isLatestVisible {
                // Preserve that the user reached the live edge even if streaming
                // growth moves it away before drag reconciliation goes quiet.
                dragActivity.sawLiveEdge = true
            }
            // Only a recent user drag can opt out of follow mode. Content growth
            // while pinned can briefly move the marker below the viewport before
            // the explicit scroll request settles, and must not look like scrollback.
            if dragging, !isLatestVisible {
                stopFollowingLatest()
            } else if isLatestVisible || dragActivity.sawLiveEdge,
                      !isFollowingLatest, !dragging,
                      dragAge >= Self.dragQuietPeriod {
                // Reaching the live edge by scrolling is equivalent to tapping the
                // pill. If growth moved it again, restore the pin immediately.
                isFollowingLatest = true
                if !isLatestVisible {
                    requestScrollToLatest(proxy: proxy)
                }
            } else if !isLatestVisible, isFollowingLatest, !dragging {
                // A scroll can land before late text or keyboard layout finishes.
                // Coalesce a corrective non-animated pin rather than waiting for
                // the next transcript event to trigger another request.
                requestScrollToLatest(proxy: proxy)
            }
        }
        .onPreferenceChange(TranscriptTopPreferenceKey.self) { topY in
            let previousTopY = dragActivity.lastTopY
            let moved = !previousTopY.isNaN && abs(topY - previousTopY) > 0.5
            dragActivity.lastTopY = topY
            let dragAge = Date().timeIntervalSince(dragActivity.last)
            let dragging = dragAge < Self.dragActivityStalePeriod
            // Offset movement during a recent drag is user scrolling; unlike pure
            // growth below, it revokes a previously observed live-edge intent.
            if moved, dragging, !isLatestVisible {
                dragActivity.sawLiveEdge = false
            }
        }
        .simultaneousGesture(
            DragGesture(minimumDistance: 4)
                .onChanged { value in
                    dragActivity.last = Date()
                    // Schedule from activity, not onEnded: ScrollView can swallow
                    // onEnded, and an idle transcript may produce no later geometry
                    // preference change to clear the wedged drag state.
                    if !dragActivity.watchdogScheduled {
                        dragActivity.watchdogScheduled = true
                        Task { @MainActor in
                            defer { dragActivity.watchdogScheduled = false }
                            while true {
                                let elapsed = Date().timeIntervalSince(dragActivity.last)
                                guard elapsed < Self.dragActivityStalePeriod else { break }
                                let remaining = Self.dragActivityStalePeriod - elapsed
                                do {
                                    try await Task.sleep(
                                        nanoseconds: UInt64(remaining * 1_000_000_000))
                                } catch {
                                    return
                                }
                            }
                            isDraggingTranscript = false
                            if isLatestVisible || dragActivity.sawLiveEdge,
                               !isFollowingLatest {
                                isFollowingLatest = true
                                if !isLatestVisible {
                                    requestScrollToLatest(proxy: proxy)
                                }
                            }
                        }
                    }
                    if !isDraggingTranscript { isDraggingTranscript = true }
                    // At gesture recognition time the geometry preference can lag
                    // the finger by one layout pass. A downward swipe is explicitly
                    // toward older content, so it must win even before that pass.
                    if !isLatestVisible || value.translation.height > 0 {
                        dragActivity.sawLiveEdge = false
                        stopFollowingLatest()
                    }
                }
                .onEnded { value in
                    // Deceleration continues after this callback. Follow mode was
                    // already disabled as soon as the drag moved off the live edge.
                    isDraggingTranscript = false
                    dragActivity.last = Date()
                    // Even if the marker is or recently was within tolerance at
                    // release, do not re-pin against a downward fling toward older
                    // content.
                    if value.predictedEndTranslation.height <= 0,
                       isLatestVisible || dragActivity.sawLiveEdge,
                       !isFollowingLatest {
                        isFollowingLatest = true
                        requestScrollToLatest(proxy: proxy)
                    }
                    // Rubber-band and deceleration can settle at the live edge after
                    // the last geometry preference change. Reconcile once more after
                    // they have gone quiet so an idle transcript can resume too.
                    Task { @MainActor in
                        try? await Task.sleep(nanoseconds: 450_000_000)
                        guard !isFollowingLatest,
                              isLatestVisible || dragActivity.sawLiveEdge,
                              !isDraggingTranscript else { return }
                        isFollowingLatest = true
                        if !isLatestVisible {
                            requestScrollToLatest(proxy: proxy)
                        }
                    }
                }
        )
        .background {
            GeometryReader { geometry in
                Color.clear
                    .onAppear { transcriptViewportHeight = geometry.size.height }
                    .onChange(of: geometry.size.height) { _, height in
                        transcriptViewportHeight = height
                    }
            }
        }
        // Do not use `.defaultScrollAnchor(.bottom)` here. SwiftUI also consults
        // that anchor on content-size changes, which moves the viewport whenever
        // the live tail grows even while the user is reading scrollback. Initial
        // and subsequent live-edge positioning are both handled explicitly by
        // `requestScrollToLatest` while follow mode is enabled.
    }

    /// Immediate acknowledgement after StartSession/SendInput, shown until the
    /// event stream produces the first meaningful piece of agent activity. Names
    /// the model when the log has told us which one is working.
    private var workingRow: some View {
        HStack(spacing: 10) {
            ProgressView()
                .controlSize(.small)
            Text(workingLabel)
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 10)
        .background(Color(.secondarySystemBackground), in: RoundedRectangle(cornerRadius: 14))
        .frame(maxWidth: .infinity, alignment: .leading)
        .accessibilityElement(children: .combine)
        .accessibilityLabel(workingLabel)
    }

    private var workingLabel: String {
        model.coordinatorModel.isEmpty
            ? "Agent is working…"
            : "\(model.coordinatorModel) is working…"
    }

    private func stopFollowingLatest() {
        guard isFollowingLatest else { return }
        isFollowingLatest = false
        // Invalidate a post-layout or keyboard-settle request that was queued
        // while the transcript was still following the live edge.
        scrollToken.value &+= 1
    }

    private func requestScrollToLatest(proxy: ScrollViewProxy) {
        guard isFollowingLatest else { return }
        scrollToken.value &+= 1
        let request = scrollToken.value
        Task { @MainActor in
            // Let LazyVStack, the keyboard safe area, and the composer all
            // finish the current layout pass. A newer request supersedes us.
            await Task.yield()
            guard request == scrollToken.value, isFollowingLatest else { return }
            proxy.scrollTo(Self.bottomAnchor, anchor: .bottom)
            // Keyboard presentation is animated over several layout passes;
            // settle once more after it reaches its final safe-area height.
            if composerFocused {
                try? await Task.sleep(nanoseconds: 300_000_000)
                guard request == scrollToken.value, isFollowingLatest else { return }
                proxy.scrollTo(Self.bottomAnchor, anchor: .bottom)
            }
        }
    }

    private func jumpToLatestPill(proxy: ScrollViewProxy) -> some View {
        Button {
            isFollowingLatest = true
            proxy.scrollTo(Self.bottomAnchor, anchor: .bottom)
        } label: {
            Label("Jump to latest", systemImage: "arrow.down")
                .font(.subheadline.weight(.semibold))
                .padding(.horizontal, 14)
                .padding(.vertical, 8)
                .background(.thinMaterial, in: Capsule())
                .overlay(Capsule().strokeBorder(.quaternary))
        }
        .buttonStyle(.plain)
    }

    /// A two-line inline title: the session's name over its project and live
    /// state. An inline `navigationTitle` alone can only show one line, and
    /// "which project is this?" is the question a cross-project feed makes
    /// constant. Folding the connection state in here also frees a toolbar slot
    /// for the backlog shortcut.
    @ToolbarContentBuilder
    private var titleToolbar: some ToolbarContent {
        ToolbarItem(placement: .principal) {
            VStack(spacing: 0) {
                Text(title)
                    .font(.headline)
                    .lineLimit(1)
                    // Tail, not middle: these titles are derived from the
                    // opening prompt, so the front of the string is the part
                    // that identifies the session.
                    .truncationMode(.tail)
                HStack(spacing: 4) {
                    if !project.isEmpty {
                        Text(project)
                    }
                    // Which model is doing the work. Folded from the event log,
                    // so a per-session model override (or a mid-session role
                    // change) is reflected rather than the global default.
                    if !model.coordinatorModel.isEmpty {
                        if !project.isEmpty { Text("·") }
                        Text(model.coordinatorModel)
                    }
                    connectionState
                }
                .font(.caption2)
                .foregroundStyle(.secondary)
                .lineLimit(1)
            }
            .frame(maxWidth: 250)
            .accessibilityElement(children: .combine)
        }
    }

    /// The stream's state, rendered inline under the title rather than as its
    /// own toolbar button.
    @ViewBuilder
    private var connectionState: some View {
        switch model.state {
        case .streaming:
            HStack(spacing: 3) {
                Circle().fill(Color.green).frame(width: 5, height: 5)
                Text("live")
            }
        case .reconnecting:
            Text("· reconnecting…")
        case .loading:
            Text("· loading…")
        case .failed:
            HStack(spacing: 3) {
                Image(systemName: "exclamationmark.triangle.fill")
                Text("offline")
            }
            .foregroundStyle(.orange)
        case .idle, .finished:
            EmptyView()
        }
    }

    /// The backlog is the other half of "what is this agent doing", so it stays
    /// one tap away from a session rather than only reachable from the home
    /// screen's drawer. Routed through ``HomeRouter`` (not a bare
    /// `NavigationLink`) so the jump replaces the stack — one Back from the
    /// backlog returns to Recent, not back through this session.
    @ToolbarContentBuilder
    private var backlogShortcut: some ToolbarContent {
        ToolbarItem(placement: .topBarTrailing) {
            Button {
                router.open(.backlog(project: project))
            } label: {
                Label("Backlog", systemImage: "checklist")
            }
        }
    }

    /// One overflow menu rather than a row of glyphs: settings, the other
    /// project destinations, and the interrupt / resume / stop controls.
    /// Shown for persisted transcripts too — the
    /// project destinations and the per-session usage sheet are just as
    /// useful on a finished session; only the live controls (settings,
    /// interrupt / resume / stop) are gated on `mode == .live`.
    @ToolbarContentBuilder
    private var actionMenu: some ToolbarContent {
        ToolbarItem(placement: .topBarTrailing) {
            Menu {
                if model.mode == .live {
                    Button {
                        showSettings = true
                    } label: {
                        Label("Session settings", systemImage: "gearshape")
                    }
                }
                Button {
                    showSessionUsage = true
                } label: {
                    Label("Session usage", systemImage: "sum")
                }
                Button {
                    router.open(.workLoop(project: project))
                } label: {
                    Label("Work loop", systemImage: "arrow.triangle.2.circlepath")
                }
                Button {
                    router.open(.workstreams(project: project))
                } label: {
                    Label("Workstreams", systemImage: "arrow.triangle.branch")
                }
                Button {
                    router.open(.usage(project: project))
                } label: {
                    Label("Usage", systemImage: "chart.bar")
                }
                Button {
                    router.open(.memory(project: project))
                } label: {
                    Label("Memory", systemImage: "brain")
                }
                if model.mode == .live {
                    Divider()
                    Button {
                        Task { await model.interrupt() }
                    } label: {
                        Label("Interrupt", systemImage: "pause.circle")
                    }
                    Button {
                        Task { await model.resumeSession() }
                    } label: {
                        Label("Resume", systemImage: "play.circle")
                    }
                    Divider()
                    Button(role: .destructive) {
                        showStopConfirm = true
                    } label: {
                        Label("Stop…", systemImage: "stop.circle")
                    }
                }
            } label: {
                Label("Session actions", systemImage: "ellipsis.circle")
            }
        }
    }
}

/// Carries the transcript tail's vertical position out of its scroll content so
/// follow mode can distinguish a user reading scrollback from a tail that merely
/// moved during live layout.
private struct TranscriptBottomPreferenceKey: PreferenceKey {
    static let defaultValue = CGFloat.greatestFiniteMagnitude
    static func reduce(value: inout CGFloat, nextValue: () -> CGFloat) {
        value = nextValue()
    }
}

/// Carries the transcript content's top edge so drag-driven viewport movement can
/// be distinguished from a streaming tail growing below a stationary viewport.
private struct TranscriptTopPreferenceKey: PreferenceKey {
    static let defaultValue = CGFloat.nan
    static func reduce(value: inout CGFloat, nextValue: () -> CGFloat) {
        value = nextValue()
    }
}

/// Renders a single ``TranscriptRow``. Bubbles for messages; collapsed,
/// tappable disclosure rows for thinking and tool calls; compact system rows.
private struct TranscriptRowView: View, Equatable {
    let row: TranscriptRow
    /// The logical model currently producing turns, shown beside the coordinator's
    /// streaming indicator. Only supplied for live tails; durable rows leave it
    /// empty. It participates in ``==`` so a role change refreshes the label.
    var model: String = ""
    /// Called with the commit sha when a `commit_made` row is tapped.
    var onOpenCommit: (String) -> Void = { _ in }
    /// Lazily retrieves a retained user picture. Returning nil renders the
    /// metadata fallback instead of a broken thumbnail.
    var loadPicture: @Sendable (String) async -> Data? = { _ in nil }

    /// The callbacks are stable for a transcript row's lifetime; row payload and
    /// the optional live model label are the only inputs that should invalidate
    /// its subtree. This keeps old MarkdownText rows from being reparsed whenever
    /// a live tail changes.
    static func == (lhs: Self, rhs: Self) -> Bool {
        lhs.row == rhs.row && lhs.model == rhs.model
    }

    var body: some View {
        if row.actorEmoji.isEmpty {
            rowContent
        } else {
            VStack(alignment: .leading, spacing: 4) {
                Text("\(row.actorEmoji) \(row.actor)")
                    .font(.caption2.weight(.medium))
                    .foregroundStyle(.secondary)
                    .accessibilityLabel("Subagent \(row.actor)")
                rowContent
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    @ViewBuilder
    private var rowContent: some View {
        switch row.kind {
        case .userMessage(let text, let pictures):
            userBubble(text: text, pictures: pictures)
        case .modelMessage(let text):
            // The plant prefix already carries the subagent label; coordinator
            // rows retain the existing textual actor heading inside the bubble.
            bubble(text: text, isUser: false, actor: row.actorEmoji.isEmpty ? row.actor : "")
        case .finalReport(let text):
            finalReport(text)
        case .thinking(let text):
            ExpandableRow(
                title: "Thinking",
                systemImage: "brain",
                tint: .purple,
                preview: ToolPreview.oneLine(text, limit: 70),
                detail: text,
                detailIsAside: true
            )
        case .tool(let name, let status, let args, let output):
            ToolRowView(name: name, status: status, args: args, output: output)
        case .question(let prompt, let options, let answer):
            QuestionRowView(prompt: prompt, options: options, answer: answer)
        case .system(let text):
            systemRow(text)
        case .commit(let text, let sha):
            commitRow(text, sha: sha)
        case .liveTail(let text):
            liveTail(
                text,
                append: row.liveAppend,
                appendBaseUTF8: row.liveAppendBaseUTF8
            )
        }
    }

    private func userBubble(text: String, pictures: [TranscriptRow.Picture]) -> some View {
        HStack {
            Spacer(minLength: 40)
            VStack(alignment: .trailing, spacing: 8) {
                if !pictures.isEmpty {
                    LazyVGrid(
                        columns: pictures.count == 1
                            ? [GridItem(.flexible())]
                            : [GridItem(.flexible()), GridItem(.flexible())],
                        spacing: 6
                    ) {
                        ForEach(Array(pictures.enumerated()), id: \.offset) { _, picture in
                            TranscriptPicture(picture: picture, loadPicture: loadPicture)
                        }
                    }
                    .frame(maxWidth: pictures.count == 1 ? 260 : 300)
                }
                if !text.isEmpty {
                    Text(text)
                        .textSelection(.enabled)
                        .padding(.horizontal, 12)
                        .padding(.vertical, 8)
                        .background(Color.accentColor.opacity(0.85), in: RoundedRectangle(cornerRadius: 14))
                        .foregroundStyle(.white)
                }
            }
        }
    }

    private func bubble(text: String, isUser: Bool, actor: String = "") -> some View {
        HStack {
            if isUser { Spacer(minLength: 40) }
            VStack(alignment: isUser ? .trailing : .leading, spacing: 2) {
                if !isUser, !actor.isEmpty {
                    Text(actor).font(.caption2).foregroundStyle(.secondary)
                }
                Group {
                    if isUser {
                        // User messages stay plain text — they were typed, not
                        // authored in markdown.
                        Text(text.isEmpty ? " " : text)
                    } else {
                        // Agent messages render as markdown (headings, lists,
                        // inline styles, fenced code blocks).
                        MarkdownText(text: text.isEmpty ? " " : text)
                    }
                }
                .textSelection(.enabled)
                .padding(.horizontal, 12)
                .padding(.vertical, 8)
                .background(
                    isUser ? Color.accentColor.opacity(0.85) : Color(.secondarySystemBackground),
                    in: RoundedRectangle(cornerRadius: 14)
                )
                .foregroundStyle(isUser ? .white : .primary)
            }
            if !isUser { Spacer(minLength: 40) }
        }
    }

    /// The finish message is the primary result of a session, not a lifecycle
    /// footnote: keep it always expanded, render its Markdown structure, and give
    /// it a distinct success card that remains easy to find in a long transcript.
    private func finalReport(_ text: String) -> some View {
        VStack(alignment: .leading, spacing: 10) {
            Label("Finished", systemImage: "checkmark.circle.fill")
                .font(.headline)
                .foregroundStyle(.green)
            MarkdownText(text: text)
                .textSelection(.enabled)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(14)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.green.opacity(0.09), in: RoundedRectangle(cornerRadius: 14))
        .overlay {
            RoundedRectangle(cornerRadius: 14)
                .stroke(Color.green.opacity(0.28), lineWidth: 1)
        }
        .accessibilityElement(children: .contain)
        .accessibilityLabel("Session finished")
    }

    private func systemRow(_ text: String) -> some View {
        HStack(spacing: 6) {
            Image(systemName: "circle.fill").font(.system(size: 4)).foregroundStyle(.tertiary)
            Text(text)
                .font(.caption)
                .foregroundStyle(.secondary)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    /// A commit row: like a system row, but tappable to drill into the commit's
    /// diff when a sha is present. Without a sha it degrades to a plain row.
    @ViewBuilder
    private func commitRow(_ text: String, sha: String) -> some View {
        if sha.isEmpty {
            systemRow(text)
        } else {
            Button {
                onOpenCommit(sha)
            } label: {
                HStack(spacing: 6) {
                    Image(systemName: "arrow.triangle.branch")
                        .font(.caption2)
                        .foregroundStyle(.blue)
                    Text(text)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .frame(maxWidth: .infinity, alignment: .leading)
                    Image(systemName: "chevron.right")
                        .font(.caption2)
                        .foregroundStyle(.tertiary)
                }
            }
            .buttonStyle(.plain)
        }
    }

    private var streamingLabel: String {
        if !row.actorEmoji.isEmpty { return "streaming" }
        let actor = row.actor.trimmingCharacters(in: .whitespacesAndNewlines)
        if !actor.isEmpty, actor != "coordinator" {
            return "\(actor) · streaming"
        }
        return model.isEmpty ? "streaming" : "\(model) · streaming"
    }

    private func liveTail(
        _ text: String,
        append: String?,
        appendBaseUTF8: Int?
    ) -> some View {
        HStack {
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 4) {
                    ProgressView().scaleEffect(0.6)
                    Text(streamingLabel)
                        .font(.caption2).foregroundStyle(.secondary)
                }
                // Unlike SwiftUI.Text, this keeps one TextKit storage/layout tree
                // alive and appends the new suffix for ordinary growing snapshots.
                // Replacing an ever-longer Text at 10 Hz repeatedly shaped and laid
                // out the full response, producing quadratic-feeling slowdown.
                IncrementalStreamingText(
                    text: text,
                    append: append,
                    appendBaseUTF8: appendBaseUTF8
                )
                .padding(.horizontal, 12)
                    .padding(.vertical, 8)
                    .background(Color(.secondarySystemBackground), in: RoundedRectangle(cornerRadius: 14))
                    .foregroundStyle(.primary)
            }
            Spacer(minLength: 40)
        }
    }
}

/// One lazily-loaded picture inside a user transcript row. The placeholder is
/// intentionally durable: old logs and reclaimed payloads still communicate
/// that the original message contained a picture.
private struct TranscriptPicture: View {
    let picture: TranscriptRow.Picture
    let loadPicture: @Sendable (String) async -> Data?
    @State private var data: Data?
    @State private var finishedLoading = false

    var body: some View {
        Group {
            if let data, let image = UIImage(data: data) {
                Image(uiImage: image)
                    .resizable()
                    .scaledToFit()
                    .frame(maxHeight: 280)
            } else {
                VStack(spacing: 6) {
                    if !finishedLoading && !picture.attachmentID.isEmpty {
                        ProgressView()
                    } else {
                        Image(systemName: "photo")
                            .font(.title2)
                    }
                    Text("Picture attached")
                        .font(.caption)
                    if !picture.filename.isEmpty {
                        Text(picture.filename)
                            .font(.caption2)
                            .lineLimit(1)
                    }
                }
                .foregroundStyle(.secondary)
                .frame(maxWidth: .infinity, minHeight: 100)
            }
        }
        .padding(4)
        .background(Color(.secondarySystemBackground), in: RoundedRectangle(cornerRadius: 14))
        .clipShape(RoundedRectangle(cornerRadius: 14))
        .task(id: picture.attachmentID) {
            guard !picture.attachmentID.isEmpty else {
                finishedLoading = true
                return
            }
            data = await loadPicture(picture.attachmentID)
            finishedLoading = true
        }
        .accessibilityLabel(picture.filename.isEmpty ? "Picture attached" : "Picture attached, \(picture.filename)")
    }
}

/// A non-scrolling, selectable TextKit view optimized for snapshot-style model
/// output. Normal snapshots extend the previous text, so mutate NSTextStorage by
/// only the suffix and let TextKit incrementally lay out the addition. A retry or
/// other non-prefix replacement falls back to replacing the complete value.
private struct IncrementalStreamingText: UIViewRepresentable {
    let text: String
    let append: String?
    let appendBaseUTF8: Int?

    final class Coordinator {
        var renderedText = ""
        var renderedUTF8Count = 0
        var font: UIFont?
    }

    func makeCoordinator() -> Coordinator { Coordinator() }

    func makeUIView(context: Context) -> UITextView {
        let view = UITextView()
        view.backgroundColor = .clear
        view.isEditable = false
        view.isSelectable = true
        view.isScrollEnabled = false
        view.textContainerInset = .zero
        view.textContainer.lineFragmentPadding = 0
        view.setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
        view.setContentHuggingPriority(.required, for: .vertical)
        return view
    }

    func updateUIView(_ view: UITextView, context: Context) {
        let font = UIFont.preferredFont(forTextStyle: .body)
        let foreground = UIColor.label
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: foreground,
        ]
        let coordinator = context.coordinator
        var nextUTF8Count = coordinator.renderedUTF8Count

        if coordinator.font != font {
            // Dynamic Type/style changes are rare and legitimately require a
            // complete relayout; streamed snapshots normally stay on append path.
            view.attributedText = NSAttributedString(string: text, attributes: attributes)
            nextUTF8Count = text.utf8.count
        } else if let append,
                  let appendBaseUTF8,
                  appendBaseUTF8 == coordinator.renderedUTF8Count {
            // Fast path from a daemon-provided verified base offset: no growing
            // prefix/count scan and no reconstruction of the accumulated string.
            if !append.isEmpty {
                view.textStorage.append(NSAttributedString(string: append, attributes: attributes))
            }
            nextUTF8Count = appendBaseUTF8 + append.utf8.count
        } else if text.hasPrefix(coordinator.renderedText) {
            // Compatibility path for older daemons that only send snapshots.
            let suffix = text.dropFirst(coordinator.renderedText.count)
            if !suffix.isEmpty {
                view.textStorage.append(NSAttributedString(string: String(suffix), attributes: attributes))
            }
            nextUTF8Count = text.utf8.count
        } else if text != coordinator.renderedText {
            // Retry/reset, lossy hint gap, or another non-prefix replacement.
            view.attributedText = NSAttributedString(string: text, attributes: attributes)
            nextUTF8Count = text.utf8.count
        }

        coordinator.renderedText = text
        coordinator.renderedUTF8Count = nextUTF8Count
        coordinator.font = font
    }

    func sizeThatFits(
        _ proposal: ProposedViewSize,
        uiView: UITextView,
        context: Context
    ) -> CGSize? {
        guard let width = proposal.width else { return nil }
        let fitted = uiView.sizeThatFits(
            CGSize(width: width, height: .greatestFiniteMagnitude))
        return CGSize(width: width, height: fitted.height)
    }
}

/// A collapsed one-liner that expands to reveal detail text on tap.
private struct ExpandableRow: View {
    let title: String
    let systemImage: String
    var tint: Color = .secondary
    /// A one-line hint of the body, shown while collapsed. Without it a stack of
    /// "Thinking" rows says nothing about what the agent was actually weighing.
    var preview: String = ""
    let detail: String
    /// Render the body as a quiet aside (dimmed + italic) rather
    /// than as prose competing with the model's actual reply.
    var detailIsAside = false

    @State private var expanded = false

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Button {
                withAnimation(.snappy) { expanded.toggle() }
            } label: {
                HStack(spacing: 6) {
                    Image(systemName: systemImage)
                        .font(.caption)
                        .foregroundStyle(tint)
                    Text(title)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    if !preview.isEmpty, !expanded {
                        Text(preview)
                            .font(.caption)
                            .foregroundStyle(.tertiary)
                            .lineLimit(1)
                            .truncationMode(.tail)
                    }
                    Spacer(minLength: 4)
                    Image(systemName: expanded ? "chevron.up" : "chevron.down")
                        .font(.caption2).foregroundStyle(.tertiary)
                }
            }
            .buttonStyle(.plain)

            if expanded {
                Group {
                    if detailIsAside {
                        Text(detail)
                            .font(.footnote.italic())
                            .foregroundStyle(.secondary)
                    } else {
                        Text(detail)
                            .font(.callout)
                    }
                }
                .textSelection(.enabled)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(10)
                .background(Color(.tertiarySystemBackground), in: RoundedRectangle(cornerRadius: 10))
            }
        }
    }
}

/// A tool call collapsed to `icon + name + what it acted on`, expandable to the
/// full args and output. The argument preview is what makes a long transcript
/// scannable — a column of bare "Bash ✓" rows carries no information.
private struct ToolRowView: View {
    let name: String
    let status: TranscriptRow.ToolStatus
    let args: String
    let output: String

    @State private var expanded = false

    private var preview: String { ToolPreview.summary(tool: name, args: args) }

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Button {
                withAnimation(.snappy) { expanded.toggle() }
            } label: {
                HStack(spacing: 6) {
                    Image(systemName: ToolPreview.symbol(for: name))
                        .font(.caption)
                        .foregroundStyle(.blue)
                        .frame(width: 16)
                    Text(name)
                        .font(.caption.monospaced())
                        .foregroundStyle(.primary)
                        .layoutPriority(1)
                    if !preview.isEmpty {
                        Text(preview)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .lineLimit(1)
                            .truncationMode(.tail)
                    }
                    Spacer(minLength: 4)
                    statusBadge
                    Image(systemName: expanded ? "chevron.up" : "chevron.down")
                        .font(.caption2).foregroundStyle(.tertiary)
                }
            }
            .buttonStyle(.plain)

            if expanded {
                VStack(alignment: .leading, spacing: 8) {
                    if !args.isEmpty { detailBlock(label: "args", text: args) }
                    if !output.isEmpty { detailBlock(label: "output", text: output) }
                }
            }
        }
        .accessibilityElement(children: .combine)
        .accessibilityLabel(preview.isEmpty ? name : "\(name), \(preview)")
    }

    private var statusBadge: some View {
        Group {
            switch status {
            case .running:
                ProgressView().scaleEffect(0.6)
            case .ok:
                Image(systemName: "checkmark.circle.fill").foregroundStyle(.green)
            case .error:
                Image(systemName: "xmark.circle.fill").foregroundStyle(.red)
            }
        }
        .font(.caption2)
    }

    private func detailBlock(label: String, text: String) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(label).font(.caption2).foregroundStyle(.secondary)
            Text(text)
                .font(.caption.monospaced())
                .textSelection(.enabled)
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(8)
                .background(Color(.tertiarySystemBackground), in: RoundedRectangle(cornerRadius: 8))
        }
    }
}

/// A pending or resolved `ask_user` question row.
private struct QuestionRowView: View {
    let prompt: String
    let options: [String]
    let answer: String?

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 6) {
                Image(systemName: "questionmark.bubble").foregroundStyle(.orange)
                Text(prompt).font(.callout.weight(.medium))
            }
            if !options.isEmpty {
                ForEach(Array(options.enumerated()), id: \.offset) { _, option in
                    Text("• \(option)").font(.caption).foregroundStyle(.secondary)
                }
            }
            if let answer {
                // A non-nil answer means the gate is closed, even if the text
                // is empty (an option-only or blank batch slot) — never keep
                // telling the user to answer a question they answered.
                Text(answer.isEmpty ? "Answered" : "Answered: \(answer)")
                    .font(.caption)
                    .foregroundStyle(.green)
            } else {
                Text("Waiting for an answer")
                    .font(.caption2)
                    .foregroundStyle(.orange)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(10)
        .background(Color.orange.opacity(0.08), in: RoundedRectangle(cornerRadius: 10))
        .overlay(RoundedRectangle(cornerRadius: 10).strokeBorder(Color.orange.opacity(0.3)))
    }
}

/// The answer sheet for a pending `ask_user` gate. A single question offers its
/// suggested options as buttons plus a free-text field (`AnswerQuestion`). A
/// batch renders one section per question and submits positionally
/// (`AnswerQuestions`, `answers[i]`). The sheet auto-dismisses when the gate
/// clears (answered here or from another client) via the parent's `onChange`.
private struct QuestionSheet: View {
    let pending: SessionProjection.PendingQuestion
    /// (optionIndex, text): optionIndex >= 0 selects an option, -1 sends text.
    /// `@MainActor` because these callbacks touch the session/app view models.
    let onAnswerSingle: @MainActor (Int, String) async -> Void
    /// Positional batch answers.
    let onAnswerBatch: @MainActor ([(text: String, optionIndex: Int)]) async -> Void

    @Environment(\.dismiss) private var dismiss
    /// Per-question free-text drafts.
    @State private var texts: [String]
    /// Per-question selected option index (-1 = none).
    @State private var selected: [Int]

    init(
        pending: SessionProjection.PendingQuestion,
        onAnswerSingle: @escaping @MainActor (Int, String) async -> Void,
        onAnswerBatch: @escaping @MainActor ([(text: String, optionIndex: Int)]) async -> Void
    ) {
        self.pending = pending
        self.onAnswerSingle = onAnswerSingle
        self.onAnswerBatch = onAnswerBatch
        _texts = State(initialValue: Array(repeating: "", count: pending.questions.count))
        _selected = State(initialValue: Array(repeating: -1, count: pending.questions.count))
    }

    var body: some View {
        NavigationStack {
            ScrollViewReader { proxy in
                Form {
                    ForEach(Array(pending.questions.enumerated()), id: \.offset) { index, question in
                        Section {
                            // The question is the point of this sheet: render it
                            // as full-size prose, not a small-caps section header
                            // that truncates a multi-sentence, self-contained ask.
                            VStack(alignment: .leading, spacing: 4) {
                                if pending.isBatch {
                                    Text("Question \(index + 1) of \(pending.questions.count)")
                                        .font(.caption2.weight(.semibold))
                                        .foregroundStyle(.secondary)
                                }
                                MarkdownText(text: question.prompt)
                                    .font(.callout)
                            }
                            .padding(.vertical, 2)
                            .listRowBackground(Color.clear)

                            ForEach(Array(question.options.enumerated()), id: \.offset) { optIdx, option in
                                optionRow(index: index, optIdx: optIdx, option: option, proxy: proxy)
                            }
                            TextField(
                                question.options.isEmpty ? "Type an answer…" : "Or type your own…",
                                text: binding(index), axis: .vertical)
                                .lineLimit(1...4)
                                .onChange(of: text(at: index)) { _, newValue in
                                    // Typing overrides a picked option.
                                    if !newValue.isEmpty { setSelected(-1, at: index) }
                                }
                            if !pending.isBatch {
                                singleSendSection
                            }
                        }
                        .id(Self.anchor(forQuestion: index))
                    }

                    if pending.isBatch {
                        Section {
                            Button {
                                submitBatch()
                            } label: {
                                HStack {
                                    Spacer()
                                    Text("Submit answers").fontWeight(.semibold)
                                    Spacer()
                                }
                            }
                            .disabled(!allAnswered)
                        } footer: {
                            if !allAnswered {
                                Text("Answer every question to submit.")
                            }
                        }
                        .id(Self.submitAnchor)
                        .listRowBackground(allAnswered ? Color.accentColor : Color(.tertiarySystemFill))
                        .foregroundStyle(allAnswered ? Color.white : Color.secondary)
                    }
                }
            }
            .navigationTitle(pending.isBatch ? "Answer questions" : "The agent is asking")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                if pending.isBatch {
                    ToolbarItem(placement: .confirmationAction) {
                        Button("Submit") { submitBatch() }
                            .disabled(!allAnswered)
                    }
                }
            }
        }
    }

    /// Scroll anchors, so answering one question can carry the user to the next
    /// one (and to the submit button after the last).
    private static func anchor(forQuestion index: Int) -> String { "question-\(index)" }
    private static let submitAnchor = "submit"

    private func optionRow(
        index: Int, optIdx: Int, option: String, proxy: ScrollViewProxy
    ) -> some View {
        Button {
            if pending.isBatch {
                setSelected(optIdx, at: index)
                setText("", at: index)
                advance(from: index, proxy: proxy)
            } else {
                // Single question: an option tap answers immediately.
                Task {
                    await onAnswerSingle(optIdx, "")
                    dismiss()
                }
            }
        } label: {
            HStack(spacing: 10) {
                Image(systemName: selectedValue(at: index) == optIdx
                    ? "largecircle.fill.circle" : "circle")
                    .foregroundStyle(selectedValue(at: index) == optIdx ? Color.accentColor : .secondary)
                Text(option)
                    .foregroundStyle(.primary)
                    .multilineTextAlignment(.leading)
                Spacer(minLength: 0)
            }
        }
    }

    /// After answering question `index`, bring the next unanswered question (or
    /// the submit button) into view. Scanning for the next *unanswered* question
    /// keeps revisiting an earlier answer from bouncing the user back down.
    private func advance(from index: Int, proxy: ScrollViewProxy) {
        let next = pending.questions.indices.first { candidate in
            candidate > index && !isAnswered(candidate)
        }
        let target = next.map(Self.anchor(forQuestion:)) ?? Self.submitAnchor
        withAnimation(.snappy) {
            proxy.scrollTo(target, anchor: .top)
        }
    }

    // Bounds-safe accessors for the per-question `@State` arrays. These arrays
    // are seeded to `pending.questions.count` in `init` and the `.id(rowID)` on
    // the sheet rebuilds this view when the gate changes, but guarding here means
    // a transient shape desync can never trap on an out-of-range subscript.
    private func text(at index: Int) -> String {
        texts.indices.contains(index) ? texts[index] : ""
    }

    private func setText(_ value: String, at index: Int) {
        guard texts.indices.contains(index) else { return }
        texts[index] = value
    }

    private func selectedValue(at index: Int) -> Int {
        selected.indices.contains(index) ? selected[index] : -1
    }

    private func setSelected(_ value: Int, at index: Int) {
        guard selected.indices.contains(index) else { return }
        selected[index] = value
    }

    /// A binding to a per-question text draft, with a trailing send button for
    /// the single-question case.
    private func binding(_ index: Int) -> Binding<String> {
        Binding(get: { text(at: index) }, set: { setText($0, at: index) })
    }

    /// For a single question, provide an inline send action for free text.
    private var singleSendSection: some View {
        Button("Send") {
            Task {
                await onAnswerSingle(-1, text(at: 0))
                dismiss()
            }
        }
        .disabled(text(at: 0).trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
    }

    /// Whether question `index` has an answer (a picked option or typed text).
    private func isAnswered(_ index: Int) -> Bool {
        if selectedValue(at: index) >= 0 { return true }
        return !text(at: index).trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private var allAnswered: Bool {
        pending.questions.indices.allSatisfy(isAnswered)
    }

    private func submitBatch() {
        let answers: [(text: String, optionIndex: Int)] = pending.questions.indices.map { i in
            let sel = selectedValue(at: i)
            if sel >= 0 { return (text: "", optionIndex: sel) }
            return (text: text(at: i), optionIndex: -1)
        }
        Task {
            await onAnswerBatch(answers)
            dismiss()
        }
    }
}

/// A commit to drill into via the diff viewer, from a tapped `commit_made` row.
/// `Identifiable` drives `navigationDestination(item:)`.
private struct CommitDiffTarget: Identifiable, Hashable {
    let sha: String
    var id: String { sha }
    /// A short display sha for the nav title (first 8 chars).
    var shortSha: String { String(sha.prefix(8)) }
}
