// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ycc/v1/ycc.proto

package yccv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/whyrusleeping/ycc/proto/ycc/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "ycc.v1.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceListModesProcedure is the fully-qualified name of the SessionService's ListModes
	// RPC.
	SessionServiceListModesProcedure = "/ycc.v1.SessionService/ListModes"
	// SessionServiceStartSessionProcedure is the fully-qualified name of the SessionService's
	// StartSession RPC.
	SessionServiceStartSessionProcedure = "/ycc.v1.SessionService/StartSession"
	// SessionServiceListSessionsProcedure is the fully-qualified name of the SessionService's
	// ListSessions RPC.
	SessionServiceListSessionsProcedure = "/ycc.v1.SessionService/ListSessions"
	// SessionServiceListSessionHistoryProcedure is the fully-qualified name of the SessionService's
	// ListSessionHistory RPC.
	SessionServiceListSessionHistoryProcedure = "/ycc.v1.SessionService/ListSessionHistory"
	// SessionServiceGetSessionTranscriptProcedure is the fully-qualified name of the SessionService's
	// GetSessionTranscript RPC.
	SessionServiceGetSessionTranscriptProcedure = "/ycc.v1.SessionService/GetSessionTranscript"
	// SessionServiceGetCommitDiffProcedure is the fully-qualified name of the SessionService's
	// GetCommitDiff RPC.
	SessionServiceGetCommitDiffProcedure = "/ycc.v1.SessionService/GetCommitDiff"
	// SessionServiceSubscribeProcedure is the fully-qualified name of the SessionService's Subscribe
	// RPC.
	SessionServiceSubscribeProcedure = "/ycc.v1.SessionService/Subscribe"
	// SessionServiceSendInputProcedure is the fully-qualified name of the SessionService's SendInput
	// RPC.
	SessionServiceSendInputProcedure = "/ycc.v1.SessionService/SendInput"
	// SessionServiceAnswerQuestionProcedure is the fully-qualified name of the SessionService's
	// AnswerQuestion RPC.
	SessionServiceAnswerQuestionProcedure = "/ycc.v1.SessionService/AnswerQuestion"
	// SessionServiceAnswerQuestionsProcedure is the fully-qualified name of the SessionService's
	// AnswerQuestions RPC.
	SessionServiceAnswerQuestionsProcedure = "/ycc.v1.SessionService/AnswerQuestions"
	// SessionServiceInterruptProcedure is the fully-qualified name of the SessionService's Interrupt
	// RPC.
	SessionServiceInterruptProcedure = "/ycc.v1.SessionService/Interrupt"
	// SessionServiceResumeProcedure is the fully-qualified name of the SessionService's Resume RPC.
	SessionServiceResumeProcedure = "/ycc.v1.SessionService/Resume"
	// SessionServiceStopSessionProcedure is the fully-qualified name of the SessionService's
	// StopSession RPC.
	SessionServiceStopSessionProcedure = "/ycc.v1.SessionService/StopSession"
	// SessionServiceResumeSessionProcedure is the fully-qualified name of the SessionService's
	// ResumeSession RPC.
	SessionServiceResumeSessionProcedure = "/ycc.v1.SessionService/ResumeSession"
	// SessionServiceListProjectsProcedure is the fully-qualified name of the SessionService's
	// ListProjects RPC.
	SessionServiceListProjectsProcedure = "/ycc.v1.SessionService/ListProjects"
	// SessionServiceAddProjectProcedure is the fully-qualified name of the SessionService's AddProject
	// RPC.
	SessionServiceAddProjectProcedure = "/ycc.v1.SessionService/AddProject"
	// SessionServiceRemoveProjectProcedure is the fully-qualified name of the SessionService's
	// RemoveProject RPC.
	SessionServiceRemoveProjectProcedure = "/ycc.v1.SessionService/RemoveProject"
	// SessionServiceListModelsProcedure is the fully-qualified name of the SessionService's ListModels
	// RPC.
	SessionServiceListModelsProcedure = "/ycc.v1.SessionService/ListModels"
	// SessionServiceSetInteractionLevelProcedure is the fully-qualified name of the SessionService's
	// SetInteractionLevel RPC.
	SessionServiceSetInteractionLevelProcedure = "/ycc.v1.SessionService/SetInteractionLevel"
	// SessionServiceSetRoleConfigProcedure is the fully-qualified name of the SessionService's
	// SetRoleConfig RPC.
	SessionServiceSetRoleConfigProcedure = "/ycc.v1.SessionService/SetRoleConfig"
	// SessionServiceSetThinkingProcedure is the fully-qualified name of the SessionService's
	// SetThinking RPC.
	SessionServiceSetThinkingProcedure = "/ycc.v1.SessionService/SetThinking"
	// SessionServiceUpsertModelProcedure is the fully-qualified name of the SessionService's
	// UpsertModel RPC.
	SessionServiceUpsertModelProcedure = "/ycc.v1.SessionService/UpsertModel"
	// SessionServiceRemoveModelProcedure is the fully-qualified name of the SessionService's
	// RemoveModel RPC.
	SessionServiceRemoveModelProcedure = "/ycc.v1.SessionService/RemoveModel"
	// SessionServiceGetModelConfigProcedure is the fully-qualified name of the SessionService's
	// GetModelConfig RPC.
	SessionServiceGetModelConfigProcedure = "/ycc.v1.SessionService/GetModelConfig"
	// SessionServiceDiscoverModelsProcedure is the fully-qualified name of the SessionService's
	// DiscoverModels RPC.
	SessionServiceDiscoverModelsProcedure = "/ycc.v1.SessionService/DiscoverModels"
	// SessionServiceListBacklogProcedure is the fully-qualified name of the SessionService's
	// ListBacklog RPC.
	SessionServiceListBacklogProcedure = "/ycc.v1.SessionService/ListBacklog"
	// SessionServiceGetTaskProcedure is the fully-qualified name of the SessionService's GetTask RPC.
	SessionServiceGetTaskProcedure = "/ycc.v1.SessionService/GetTask"
	// SessionServiceUpdateTaskProcedure is the fully-qualified name of the SessionService's UpdateTask
	// RPC.
	SessionServiceUpdateTaskProcedure = "/ycc.v1.SessionService/UpdateTask"
	// SessionServiceListPlansProcedure is the fully-qualified name of the SessionService's ListPlans
	// RPC.
	SessionServiceListPlansProcedure = "/ycc.v1.SessionService/ListPlans"
	// SessionServiceGetPlanProcedure is the fully-qualified name of the SessionService's GetPlan RPC.
	SessionServiceGetPlanProcedure = "/ycc.v1.SessionService/GetPlan"
	// SessionServiceCaptureBacklogItemProcedure is the fully-qualified name of the SessionService's
	// CaptureBacklogItem RPC.
	SessionServiceCaptureBacklogItemProcedure = "/ycc.v1.SessionService/CaptureBacklogItem"
	// SessionServiceGetUsageProcedure is the fully-qualified name of the SessionService's GetUsage RPC.
	SessionServiceGetUsageProcedure = "/ycc.v1.SessionService/GetUsage"
	// SessionServiceGetBudgetProcedure is the fully-qualified name of the SessionService's GetBudget
	// RPC.
	SessionServiceGetBudgetProcedure = "/ycc.v1.SessionService/GetBudget"
	// SessionServiceSpawnWorkstreamProcedure is the fully-qualified name of the SessionService's
	// SpawnWorkstream RPC.
	SessionServiceSpawnWorkstreamProcedure = "/ycc.v1.SessionService/SpawnWorkstream"
	// SessionServiceListWorkstreamsProcedure is the fully-qualified name of the SessionService's
	// ListWorkstreams RPC.
	SessionServiceListWorkstreamsProcedure = "/ycc.v1.SessionService/ListWorkstreams"
	// SessionServicePreviewMergeProcedure is the fully-qualified name of the SessionService's
	// PreviewMerge RPC.
	SessionServicePreviewMergeProcedure = "/ycc.v1.SessionService/PreviewMerge"
	// SessionServiceMergeWorkstreamProcedure is the fully-qualified name of the SessionService's
	// MergeWorkstream RPC.
	SessionServiceMergeWorkstreamProcedure = "/ycc.v1.SessionService/MergeWorkstream"
	// SessionServiceDiscardWorkstreamProcedure is the fully-qualified name of the SessionService's
	// DiscardWorkstream RPC.
	SessionServiceDiscardWorkstreamProcedure = "/ycc.v1.SessionService/DiscardWorkstream"
)

// SessionServiceClient is a client for the ycc.v1.SessionService service.
type SessionServiceClient interface {
	ListModes(context.Context, *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error)
	StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	// ListSessionHistory enumerates all sessions for a project (live + persisted
	// on-disk logs), most-recent first (spec §18.6). ListSessions stays live-only.
	ListSessionHistory(context.Context, *connect.Request[v1.ListSessionHistoryRequest]) (*connect.Response[v1.ListSessionHistoryResponse], error)
	// GetSessionTranscript returns a session's full event log (live or persisted)
	// for the read-only transcript drill-in (spec §18.6).
	GetSessionTranscript(context.Context, *connect.Request[v1.GetSessionTranscriptRequest]) (*connect.Response[v1.GetSessionTranscriptResponse], error)
	// GetCommitDiff returns a commit's `git show` diff so the transcript can drill
	// into what an agent committed from a commit_made row (task 0140, spec §18.6).
	GetCommitDiff(context.Context, *connect.Request[v1.GetCommitDiffRequest]) (*connect.Response[v1.GetCommitDiffResponse], error)
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.Event], error)
	SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error)
	AnswerQuestion(context.Context, *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error)
	// AnswerQuestions replies to a batch of questions posed in one ask_user call.
	AnswerQuestions(context.Context, *connect.Request[v1.AnswerQuestionsRequest]) (*connect.Response[v1.AnswerQuestionsResponse], error)
	// Interrupt & steer (spec §18.7): gracefully pause a running session at its
	// next safe checkpoint, then continue the same loop (optionally after a
	// steered SendInput correction). Distinct from the hard Stop/terminate.
	Interrupt(context.Context, *connect.Request[v1.InterruptRequest]) (*connect.Response[v1.InterruptResponse], error)
	Resume(context.Context, *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error)
	// StopSession hard-terminates a session: cancels its agent loop, closes its
	// event log, and removes it from the daemon (no resume). Distinct from
	// Interrupt's graceful pause (spec §12, §18.7).
	StopSession(context.Context, *connect.Request[v1.StopSessionRequest]) (*connect.Response[v1.StopSessionResponse], error)
	// ResumeSession re-opens a persisted session on its existing event log
	// (reconstructs loop history; "resume = replay", spec §4.5/§18.6). Idempotent
	// if the session is already live.
	ResumeSession(context.Context, *connect.Request[v1.ResumeSessionRequest]) (*connect.Response[v1.ResumeSessionResponse], error)
	// Projects — persistent multi-project daemon (spec §3.1).
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	AddProject(context.Context, *connect.Request[v1.AddProjectRequest]) (*connect.Response[v1.AddProjectResponse], error)
	RemoveProject(context.Context, *connect.Request[v1.RemoveProjectRequest]) (*connect.Response[v1.RemoveProjectResponse], error)
	// Settings overlay (spec §18.2): enumerate models and change a session's
	// interaction level / per-role model assignment mid-flight.
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	SetInteractionLevel(context.Context, *connect.Request[v1.SetInteractionLevelRequest]) (*connect.Response[v1.SetInteractionLevelResponse], error)
	SetRoleConfig(context.Context, *connect.Request[v1.SetRoleConfigRequest]) (*connect.Response[v1.SetRoleConfigResponse], error)
	SetThinking(context.Context, *connect.Request[v1.SetThinkingRequest]) (*connect.Response[v1.SetThinkingResponse], error)
	// Model backends (spec §18.2): add/edit/remove a logical model backend at
	// runtime; optionally persisted to ycc.toml.
	UpsertModel(context.Context, *connect.Request[v1.UpsertModelRequest]) (*connect.Response[v1.UpsertModelResponse], error)
	RemoveModel(context.Context, *connect.Request[v1.RemoveModelRequest]) (*connect.Response[v1.RemoveModelResponse], error)
	GetModelConfig(context.Context, *connect.Request[v1.GetModelConfigRequest]) (*connect.Response[v1.GetModelConfigResponse], error)
	DiscoverModels(context.Context, *connect.Request[v1.DiscoverModelsRequest]) (*connect.Response[v1.DiscoverModelsResponse], error)
	// Backlog browser (spec §18.5): read-only access to the durable backlog.
	ListBacklog(context.Context, *connect.Request[v1.ListBacklogRequest]) (*connect.Response[v1.ListBacklogResponse], error)
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	// UpdateTask grooms a backlog task in place (spec §18.5, task 0099): change
	// status/priority/title, or (no mutation fields) refresh + regenerate the index.
	UpdateTask(context.Context, *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error)
	// Plan library (reusable runbooks, task 0020/0077): read-only access to the
	// in-repo plans/*.md so clients can browse and view saved plans.
	ListPlans(context.Context, *connect.Request[v1.ListPlansRequest]) (*connect.Response[v1.ListPlansResponse], error)
	GetPlan(context.Context, *connect.Request[v1.GetPlanRequest]) (*connect.Response[v1.GetPlanResponse], error)
	// Quick-add backlog capture (spec §18.2, task 0016): run a lightweight,
	// off-stream capture agent that turns a natural-language description into a
	// backlog task without disturbing the running session. May ask ONE clarifying
	// question, carried back via prior_question/prior_answer.
	//
	// Streams the capture agent's action log (the same Event stream as Subscribe)
	// so the client can show live progress, ending with a terminal
	// `capture_result` event whose data_json carries {task_id,title,question} on
	// success (or {error} on failure).
	CaptureBacklogItem(context.Context, *connect.Request[v1.CaptureBacklogItemRequest]) (*connect.ServerStreamForClient[v1.Event], error)
	// Usage/cost breakdown (spec §20): aggregated, priced token usage by task ×
	// model × day so clients can render the cost breakdown.
	GetUsage(context.Context, *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error)
	// Spend guard (task 0137, spec §20.6): return the configured budget caps so the
	// TUI work-loop driver can enforce the per-loop-run cap client-side.
	GetBudget(context.Context, *connect.Request[v1.GetBudgetRequest]) (*connect.Response[v1.GetBudgetResponse], error)
	// Parallel workstreams (docs/design/parallel-workstreams.md §6, §8): spawn a
	// worktree+session, list them, preview/merge a branch back to base with the
	// conflict-aware review gate, or discard one. Subscribe(session_id) is reused
	// verbatim for per-workstream event streaming (the session_id rides inside
	// WorkstreamInfo).
	SpawnWorkstream(context.Context, *connect.Request[v1.SpawnWorkstreamRequest]) (*connect.Response[v1.SpawnWorkstreamResponse], error)
	ListWorkstreams(context.Context, *connect.Request[v1.ListWorkstreamsRequest]) (*connect.Response[v1.ListWorkstreamsResponse], error)
	PreviewMerge(context.Context, *connect.Request[v1.PreviewMergeRequest]) (*connect.Response[v1.PreviewMergeResponse], error)
	MergeWorkstream(context.Context, *connect.Request[v1.MergeWorkstreamRequest]) (*connect.Response[v1.MergeWorkstreamResponse], error)
	DiscardWorkstream(context.Context, *connect.Request[v1.DiscardWorkstreamRequest]) (*connect.Response[v1.DiscardWorkstreamResponse], error)
}

// NewSessionServiceClient constructs a client for the ycc.v1.SessionService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := v1.File_ycc_v1_ycc_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		listModes: connect.NewClient[v1.ListModesRequest, v1.ListModesResponse](
			httpClient,
			baseURL+SessionServiceListModesProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListModes")),
			connect.WithClientOptions(opts...),
		),
		startSession: connect.NewClient[v1.StartSessionRequest, v1.StartSessionResponse](
			httpClient,
			baseURL+SessionServiceStartSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+SessionServiceListSessionsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		listSessionHistory: connect.NewClient[v1.ListSessionHistoryRequest, v1.ListSessionHistoryResponse](
			httpClient,
			baseURL+SessionServiceListSessionHistoryProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListSessionHistory")),
			connect.WithClientOptions(opts...),
		),
		getSessionTranscript: connect.NewClient[v1.GetSessionTranscriptRequest, v1.GetSessionTranscriptResponse](
			httpClient,
			baseURL+SessionServiceGetSessionTranscriptProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetSessionTranscript")),
			connect.WithClientOptions(opts...),
		),
		getCommitDiff: connect.NewClient[v1.GetCommitDiffRequest, v1.GetCommitDiffResponse](
			httpClient,
			baseURL+SessionServiceGetCommitDiffProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetCommitDiff")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[v1.SubscribeRequest, v1.Event](
			httpClient,
			baseURL+SessionServiceSubscribeProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		sendInput: connect.NewClient[v1.SendInputRequest, v1.SendInputResponse](
			httpClient,
			baseURL+SessionServiceSendInputProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SendInput")),
			connect.WithClientOptions(opts...),
		),
		answerQuestion: connect.NewClient[v1.AnswerQuestionRequest, v1.AnswerQuestionResponse](
			httpClient,
			baseURL+SessionServiceAnswerQuestionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("AnswerQuestion")),
			connect.WithClientOptions(opts...),
		),
		answerQuestions: connect.NewClient[v1.AnswerQuestionsRequest, v1.AnswerQuestionsResponse](
			httpClient,
			baseURL+SessionServiceAnswerQuestionsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("AnswerQuestions")),
			connect.WithClientOptions(opts...),
		),
		interrupt: connect.NewClient[v1.InterruptRequest, v1.InterruptResponse](
			httpClient,
			baseURL+SessionServiceInterruptProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Interrupt")),
			connect.WithClientOptions(opts...),
		),
		resume: connect.NewClient[v1.ResumeRequest, v1.ResumeResponse](
			httpClient,
			baseURL+SessionServiceResumeProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Resume")),
			connect.WithClientOptions(opts...),
		),
		stopSession: connect.NewClient[v1.StopSessionRequest, v1.StopSessionResponse](
			httpClient,
			baseURL+SessionServiceStopSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("StopSession")),
			connect.WithClientOptions(opts...),
		),
		resumeSession: connect.NewClient[v1.ResumeSessionRequest, v1.ResumeSessionResponse](
			httpClient,
			baseURL+SessionServiceResumeSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ResumeSession")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+SessionServiceListProjectsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		addProject: connect.NewClient[v1.AddProjectRequest, v1.AddProjectResponse](
			httpClient,
			baseURL+SessionServiceAddProjectProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("AddProject")),
			connect.WithClientOptions(opts...),
		),
		removeProject: connect.NewClient[v1.RemoveProjectRequest, v1.RemoveProjectResponse](
			httpClient,
			baseURL+SessionServiceRemoveProjectProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("RemoveProject")),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+SessionServiceListModelsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		setInteractionLevel: connect.NewClient[v1.SetInteractionLevelRequest, v1.SetInteractionLevelResponse](
			httpClient,
			baseURL+SessionServiceSetInteractionLevelProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SetInteractionLevel")),
			connect.WithClientOptions(opts...),
		),
		setRoleConfig: connect.NewClient[v1.SetRoleConfigRequest, v1.SetRoleConfigResponse](
			httpClient,
			baseURL+SessionServiceSetRoleConfigProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SetRoleConfig")),
			connect.WithClientOptions(opts...),
		),
		setThinking: connect.NewClient[v1.SetThinkingRequest, v1.SetThinkingResponse](
			httpClient,
			baseURL+SessionServiceSetThinkingProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SetThinking")),
			connect.WithClientOptions(opts...),
		),
		upsertModel: connect.NewClient[v1.UpsertModelRequest, v1.UpsertModelResponse](
			httpClient,
			baseURL+SessionServiceUpsertModelProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("UpsertModel")),
			connect.WithClientOptions(opts...),
		),
		removeModel: connect.NewClient[v1.RemoveModelRequest, v1.RemoveModelResponse](
			httpClient,
			baseURL+SessionServiceRemoveModelProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("RemoveModel")),
			connect.WithClientOptions(opts...),
		),
		getModelConfig: connect.NewClient[v1.GetModelConfigRequest, v1.GetModelConfigResponse](
			httpClient,
			baseURL+SessionServiceGetModelConfigProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetModelConfig")),
			connect.WithClientOptions(opts...),
		),
		discoverModels: connect.NewClient[v1.DiscoverModelsRequest, v1.DiscoverModelsResponse](
			httpClient,
			baseURL+SessionServiceDiscoverModelsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("DiscoverModels")),
			connect.WithClientOptions(opts...),
		),
		listBacklog: connect.NewClient[v1.ListBacklogRequest, v1.ListBacklogResponse](
			httpClient,
			baseURL+SessionServiceListBacklogProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListBacklog")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v1.GetTaskRequest, v1.GetTaskResponse](
			httpClient,
			baseURL+SessionServiceGetTaskProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		updateTask: connect.NewClient[v1.UpdateTaskRequest, v1.UpdateTaskResponse](
			httpClient,
			baseURL+SessionServiceUpdateTaskProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("UpdateTask")),
			connect.WithClientOptions(opts...),
		),
		listPlans: connect.NewClient[v1.ListPlansRequest, v1.ListPlansResponse](
			httpClient,
			baseURL+SessionServiceListPlansProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListPlans")),
			connect.WithClientOptions(opts...),
		),
		getPlan: connect.NewClient[v1.GetPlanRequest, v1.GetPlanResponse](
			httpClient,
			baseURL+SessionServiceGetPlanProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetPlan")),
			connect.WithClientOptions(opts...),
		),
		captureBacklogItem: connect.NewClient[v1.CaptureBacklogItemRequest, v1.Event](
			httpClient,
			baseURL+SessionServiceCaptureBacklogItemProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("CaptureBacklogItem")),
			connect.WithClientOptions(opts...),
		),
		getUsage: connect.NewClient[v1.GetUsageRequest, v1.GetUsageResponse](
			httpClient,
			baseURL+SessionServiceGetUsageProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetUsage")),
			connect.WithClientOptions(opts...),
		),
		getBudget: connect.NewClient[v1.GetBudgetRequest, v1.GetBudgetResponse](
			httpClient,
			baseURL+SessionServiceGetBudgetProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetBudget")),
			connect.WithClientOptions(opts...),
		),
		spawnWorkstream: connect.NewClient[v1.SpawnWorkstreamRequest, v1.SpawnWorkstreamResponse](
			httpClient,
			baseURL+SessionServiceSpawnWorkstreamProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SpawnWorkstream")),
			connect.WithClientOptions(opts...),
		),
		listWorkstreams: connect.NewClient[v1.ListWorkstreamsRequest, v1.ListWorkstreamsResponse](
			httpClient,
			baseURL+SessionServiceListWorkstreamsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListWorkstreams")),
			connect.WithClientOptions(opts...),
		),
		previewMerge: connect.NewClient[v1.PreviewMergeRequest, v1.PreviewMergeResponse](
			httpClient,
			baseURL+SessionServicePreviewMergeProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("PreviewMerge")),
			connect.WithClientOptions(opts...),
		),
		mergeWorkstream: connect.NewClient[v1.MergeWorkstreamRequest, v1.MergeWorkstreamResponse](
			httpClient,
			baseURL+SessionServiceMergeWorkstreamProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("MergeWorkstream")),
			connect.WithClientOptions(opts...),
		),
		discardWorkstream: connect.NewClient[v1.DiscardWorkstreamRequest, v1.DiscardWorkstreamResponse](
			httpClient,
			baseURL+SessionServiceDiscardWorkstreamProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("DiscardWorkstream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	listModes            *connect.Client[v1.ListModesRequest, v1.ListModesResponse]
	startSession         *connect.Client[v1.StartSessionRequest, v1.StartSessionResponse]
	listSessions         *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	listSessionHistory   *connect.Client[v1.ListSessionHistoryRequest, v1.ListSessionHistoryResponse]
	getSessionTranscript *connect.Client[v1.GetSessionTranscriptRequest, v1.GetSessionTranscriptResponse]
	getCommitDiff        *connect.Client[v1.GetCommitDiffRequest, v1.GetCommitDiffResponse]
	subscribe            *connect.Client[v1.SubscribeRequest, v1.Event]
	sendInput            *connect.Client[v1.SendInputRequest, v1.SendInputResponse]
	answerQuestion       *connect.Client[v1.AnswerQuestionRequest, v1.AnswerQuestionResponse]
	answerQuestions      *connect.Client[v1.AnswerQuestionsRequest, v1.AnswerQuestionsResponse]
	interrupt            *connect.Client[v1.InterruptRequest, v1.InterruptResponse]
	resume               *connect.Client[v1.ResumeRequest, v1.ResumeResponse]
	stopSession          *connect.Client[v1.StopSessionRequest, v1.StopSessionResponse]
	resumeSession        *connect.Client[v1.ResumeSessionRequest, v1.ResumeSessionResponse]
	listProjects         *connect.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
	addProject           *connect.Client[v1.AddProjectRequest, v1.AddProjectResponse]
	removeProject        *connect.Client[v1.RemoveProjectRequest, v1.RemoveProjectResponse]
	listModels           *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	setInteractionLevel  *connect.Client[v1.SetInteractionLevelRequest, v1.SetInteractionLevelResponse]
	setRoleConfig        *connect.Client[v1.SetRoleConfigRequest, v1.SetRoleConfigResponse]
	setThinking          *connect.Client[v1.SetThinkingRequest, v1.SetThinkingResponse]
	upsertModel          *connect.Client[v1.UpsertModelRequest, v1.UpsertModelResponse]
	removeModel          *connect.Client[v1.RemoveModelRequest, v1.RemoveModelResponse]
	getModelConfig       *connect.Client[v1.GetModelConfigRequest, v1.GetModelConfigResponse]
	discoverModels       *connect.Client[v1.DiscoverModelsRequest, v1.DiscoverModelsResponse]
	listBacklog          *connect.Client[v1.ListBacklogRequest, v1.ListBacklogResponse]
	getTask              *connect.Client[v1.GetTaskRequest, v1.GetTaskResponse]
	updateTask           *connect.Client[v1.UpdateTaskRequest, v1.UpdateTaskResponse]
	listPlans            *connect.Client[v1.ListPlansRequest, v1.ListPlansResponse]
	getPlan              *connect.Client[v1.GetPlanRequest, v1.GetPlanResponse]
	captureBacklogItem   *connect.Client[v1.CaptureBacklogItemRequest, v1.Event]
	getUsage             *connect.Client[v1.GetUsageRequest, v1.GetUsageResponse]
	getBudget            *connect.Client[v1.GetBudgetRequest, v1.GetBudgetResponse]
	spawnWorkstream      *connect.Client[v1.SpawnWorkstreamRequest, v1.SpawnWorkstreamResponse]
	listWorkstreams      *connect.Client[v1.ListWorkstreamsRequest, v1.ListWorkstreamsResponse]
	previewMerge         *connect.Client[v1.PreviewMergeRequest, v1.PreviewMergeResponse]
	mergeWorkstream      *connect.Client[v1.MergeWorkstreamRequest, v1.MergeWorkstreamResponse]
	discardWorkstream    *connect.Client[v1.DiscardWorkstreamRequest, v1.DiscardWorkstreamResponse]
}

// ListModes calls ycc.v1.SessionService.ListModes.
func (c *sessionServiceClient) ListModes(ctx context.Context, req *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error) {
	return c.listModes.CallUnary(ctx, req)
}

// StartSession calls ycc.v1.SessionService.StartSession.
func (c *sessionServiceClient) StartSession(ctx context.Context, req *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error) {
	return c.startSession.CallUnary(ctx, req)
}

// ListSessions calls ycc.v1.SessionService.ListSessions.
func (c *sessionServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// ListSessionHistory calls ycc.v1.SessionService.ListSessionHistory.
func (c *sessionServiceClient) ListSessionHistory(ctx context.Context, req *connect.Request[v1.ListSessionHistoryRequest]) (*connect.Response[v1.ListSessionHistoryResponse], error) {
	return c.listSessionHistory.CallUnary(ctx, req)
}

// GetSessionTranscript calls ycc.v1.SessionService.GetSessionTranscript.
func (c *sessionServiceClient) GetSessionTranscript(ctx context.Context, req *connect.Request[v1.GetSessionTranscriptRequest]) (*connect.Response[v1.GetSessionTranscriptResponse], error) {
	return c.getSessionTranscript.CallUnary(ctx, req)
}

// GetCommitDiff calls ycc.v1.SessionService.GetCommitDiff.
func (c *sessionServiceClient) GetCommitDiff(ctx context.Context, req *connect.Request[v1.GetCommitDiffRequest]) (*connect.Response[v1.GetCommitDiffResponse], error) {
	return c.getCommitDiff.CallUnary(ctx, req)
}

// Subscribe calls ycc.v1.SessionService.Subscribe.
func (c *sessionServiceClient) Subscribe(ctx context.Context, req *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.Event], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// SendInput calls ycc.v1.SessionService.SendInput.
func (c *sessionServiceClient) SendInput(ctx context.Context, req *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error) {
	return c.sendInput.CallUnary(ctx, req)
}

// AnswerQuestion calls ycc.v1.SessionService.AnswerQuestion.
func (c *sessionServiceClient) AnswerQuestion(ctx context.Context, req *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error) {
	return c.answerQuestion.CallUnary(ctx, req)
}

// AnswerQuestions calls ycc.v1.SessionService.AnswerQuestions.
func (c *sessionServiceClient) AnswerQuestions(ctx context.Context, req *connect.Request[v1.AnswerQuestionsRequest]) (*connect.Response[v1.AnswerQuestionsResponse], error) {
	return c.answerQuestions.CallUnary(ctx, req)
}

// Interrupt calls ycc.v1.SessionService.Interrupt.
func (c *sessionServiceClient) Interrupt(ctx context.Context, req *connect.Request[v1.InterruptRequest]) (*connect.Response[v1.InterruptResponse], error) {
	return c.interrupt.CallUnary(ctx, req)
}

// Resume calls ycc.v1.SessionService.Resume.
func (c *sessionServiceClient) Resume(ctx context.Context, req *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error) {
	return c.resume.CallUnary(ctx, req)
}

// StopSession calls ycc.v1.SessionService.StopSession.
func (c *sessionServiceClient) StopSession(ctx context.Context, req *connect.Request[v1.StopSessionRequest]) (*connect.Response[v1.StopSessionResponse], error) {
	return c.stopSession.CallUnary(ctx, req)
}

// ResumeSession calls ycc.v1.SessionService.ResumeSession.
func (c *sessionServiceClient) ResumeSession(ctx context.Context, req *connect.Request[v1.ResumeSessionRequest]) (*connect.Response[v1.ResumeSessionResponse], error) {
	return c.resumeSession.CallUnary(ctx, req)
}

// ListProjects calls ycc.v1.SessionService.ListProjects.
func (c *sessionServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// AddProject calls ycc.v1.SessionService.AddProject.
func (c *sessionServiceClient) AddProject(ctx context.Context, req *connect.Request[v1.AddProjectRequest]) (*connect.Response[v1.AddProjectResponse], error) {
	return c.addProject.CallUnary(ctx, req)
}

// RemoveProject calls ycc.v1.SessionService.RemoveProject.
func (c *sessionServiceClient) RemoveProject(ctx context.Context, req *connect.Request[v1.RemoveProjectRequest]) (*connect.Response[v1.RemoveProjectResponse], error) {
	return c.removeProject.CallUnary(ctx, req)
}

// ListModels calls ycc.v1.SessionService.ListModels.
func (c *sessionServiceClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// SetInteractionLevel calls ycc.v1.SessionService.SetInteractionLevel.
func (c *sessionServiceClient) SetInteractionLevel(ctx context.Context, req *connect.Request[v1.SetInteractionLevelRequest]) (*connect.Response[v1.SetInteractionLevelResponse], error) {
	return c.setInteractionLevel.CallUnary(ctx, req)
}

// SetRoleConfig calls ycc.v1.SessionService.SetRoleConfig.
func (c *sessionServiceClient) SetRoleConfig(ctx context.Context, req *connect.Request[v1.SetRoleConfigRequest]) (*connect.Response[v1.SetRoleConfigResponse], error) {
	return c.setRoleConfig.CallUnary(ctx, req)
}

// SetThinking calls ycc.v1.SessionService.SetThinking.
func (c *sessionServiceClient) SetThinking(ctx context.Context, req *connect.Request[v1.SetThinkingRequest]) (*connect.Response[v1.SetThinkingResponse], error) {
	return c.setThinking.CallUnary(ctx, req)
}

// UpsertModel calls ycc.v1.SessionService.UpsertModel.
func (c *sessionServiceClient) UpsertModel(ctx context.Context, req *connect.Request[v1.UpsertModelRequest]) (*connect.Response[v1.UpsertModelResponse], error) {
	return c.upsertModel.CallUnary(ctx, req)
}

// RemoveModel calls ycc.v1.SessionService.RemoveModel.
func (c *sessionServiceClient) RemoveModel(ctx context.Context, req *connect.Request[v1.RemoveModelRequest]) (*connect.Response[v1.RemoveModelResponse], error) {
	return c.removeModel.CallUnary(ctx, req)
}

// GetModelConfig calls ycc.v1.SessionService.GetModelConfig.
func (c *sessionServiceClient) GetModelConfig(ctx context.Context, req *connect.Request[v1.GetModelConfigRequest]) (*connect.Response[v1.GetModelConfigResponse], error) {
	return c.getModelConfig.CallUnary(ctx, req)
}

// DiscoverModels calls ycc.v1.SessionService.DiscoverModels.
func (c *sessionServiceClient) DiscoverModels(ctx context.Context, req *connect.Request[v1.DiscoverModelsRequest]) (*connect.Response[v1.DiscoverModelsResponse], error) {
	return c.discoverModels.CallUnary(ctx, req)
}

// ListBacklog calls ycc.v1.SessionService.ListBacklog.
func (c *sessionServiceClient) ListBacklog(ctx context.Context, req *connect.Request[v1.ListBacklogRequest]) (*connect.Response[v1.ListBacklogResponse], error) {
	return c.listBacklog.CallUnary(ctx, req)
}

// GetTask calls ycc.v1.SessionService.GetTask.
func (c *sessionServiceClient) GetTask(ctx context.Context, req *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// UpdateTask calls ycc.v1.SessionService.UpdateTask.
func (c *sessionServiceClient) UpdateTask(ctx context.Context, req *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error) {
	return c.updateTask.CallUnary(ctx, req)
}

// ListPlans calls ycc.v1.SessionService.ListPlans.
func (c *sessionServiceClient) ListPlans(ctx context.Context, req *connect.Request[v1.ListPlansRequest]) (*connect.Response[v1.ListPlansResponse], error) {
	return c.listPlans.CallUnary(ctx, req)
}

// GetPlan calls ycc.v1.SessionService.GetPlan.
func (c *sessionServiceClient) GetPlan(ctx context.Context, req *connect.Request[v1.GetPlanRequest]) (*connect.Response[v1.GetPlanResponse], error) {
	return c.getPlan.CallUnary(ctx, req)
}

// CaptureBacklogItem calls ycc.v1.SessionService.CaptureBacklogItem.
func (c *sessionServiceClient) CaptureBacklogItem(ctx context.Context, req *connect.Request[v1.CaptureBacklogItemRequest]) (*connect.ServerStreamForClient[v1.Event], error) {
	return c.captureBacklogItem.CallServerStream(ctx, req)
}

// GetUsage calls ycc.v1.SessionService.GetUsage.
func (c *sessionServiceClient) GetUsage(ctx context.Context, req *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error) {
	return c.getUsage.CallUnary(ctx, req)
}

// GetBudget calls ycc.v1.SessionService.GetBudget.
func (c *sessionServiceClient) GetBudget(ctx context.Context, req *connect.Request[v1.GetBudgetRequest]) (*connect.Response[v1.GetBudgetResponse], error) {
	return c.getBudget.CallUnary(ctx, req)
}

// SpawnWorkstream calls ycc.v1.SessionService.SpawnWorkstream.
func (c *sessionServiceClient) SpawnWorkstream(ctx context.Context, req *connect.Request[v1.SpawnWorkstreamRequest]) (*connect.Response[v1.SpawnWorkstreamResponse], error) {
	return c.spawnWorkstream.CallUnary(ctx, req)
}

// ListWorkstreams calls ycc.v1.SessionService.ListWorkstreams.
func (c *sessionServiceClient) ListWorkstreams(ctx context.Context, req *connect.Request[v1.ListWorkstreamsRequest]) (*connect.Response[v1.ListWorkstreamsResponse], error) {
	return c.listWorkstreams.CallUnary(ctx, req)
}

// PreviewMerge calls ycc.v1.SessionService.PreviewMerge.
func (c *sessionServiceClient) PreviewMerge(ctx context.Context, req *connect.Request[v1.PreviewMergeRequest]) (*connect.Response[v1.PreviewMergeResponse], error) {
	return c.previewMerge.CallUnary(ctx, req)
}

// MergeWorkstream calls ycc.v1.SessionService.MergeWorkstream.
func (c *sessionServiceClient) MergeWorkstream(ctx context.Context, req *connect.Request[v1.MergeWorkstreamRequest]) (*connect.Response[v1.MergeWorkstreamResponse], error) {
	return c.mergeWorkstream.CallUnary(ctx, req)
}

// DiscardWorkstream calls ycc.v1.SessionService.DiscardWorkstream.
func (c *sessionServiceClient) DiscardWorkstream(ctx context.Context, req *connect.Request[v1.DiscardWorkstreamRequest]) (*connect.Response[v1.DiscardWorkstreamResponse], error) {
	return c.discardWorkstream.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the ycc.v1.SessionService service.
type SessionServiceHandler interface {
	ListModes(context.Context, *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error)
	StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	// ListSessionHistory enumerates all sessions for a project (live + persisted
	// on-disk logs), most-recent first (spec §18.6). ListSessions stays live-only.
	ListSessionHistory(context.Context, *connect.Request[v1.ListSessionHistoryRequest]) (*connect.Response[v1.ListSessionHistoryResponse], error)
	// GetSessionTranscript returns a session's full event log (live or persisted)
	// for the read-only transcript drill-in (spec §18.6).
	GetSessionTranscript(context.Context, *connect.Request[v1.GetSessionTranscriptRequest]) (*connect.Response[v1.GetSessionTranscriptResponse], error)
	// GetCommitDiff returns a commit's `git show` diff so the transcript can drill
	// into what an agent committed from a commit_made row (task 0140, spec §18.6).
	GetCommitDiff(context.Context, *connect.Request[v1.GetCommitDiffRequest]) (*connect.Response[v1.GetCommitDiffResponse], error)
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.Event]) error
	SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error)
	AnswerQuestion(context.Context, *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error)
	// AnswerQuestions replies to a batch of questions posed in one ask_user call.
	AnswerQuestions(context.Context, *connect.Request[v1.AnswerQuestionsRequest]) (*connect.Response[v1.AnswerQuestionsResponse], error)
	// Interrupt & steer (spec §18.7): gracefully pause a running session at its
	// next safe checkpoint, then continue the same loop (optionally after a
	// steered SendInput correction). Distinct from the hard Stop/terminate.
	Interrupt(context.Context, *connect.Request[v1.InterruptRequest]) (*connect.Response[v1.InterruptResponse], error)
	Resume(context.Context, *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error)
	// StopSession hard-terminates a session: cancels its agent loop, closes its
	// event log, and removes it from the daemon (no resume). Distinct from
	// Interrupt's graceful pause (spec §12, §18.7).
	StopSession(context.Context, *connect.Request[v1.StopSessionRequest]) (*connect.Response[v1.StopSessionResponse], error)
	// ResumeSession re-opens a persisted session on its existing event log
	// (reconstructs loop history; "resume = replay", spec §4.5/§18.6). Idempotent
	// if the session is already live.
	ResumeSession(context.Context, *connect.Request[v1.ResumeSessionRequest]) (*connect.Response[v1.ResumeSessionResponse], error)
	// Projects — persistent multi-project daemon (spec §3.1).
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	AddProject(context.Context, *connect.Request[v1.AddProjectRequest]) (*connect.Response[v1.AddProjectResponse], error)
	RemoveProject(context.Context, *connect.Request[v1.RemoveProjectRequest]) (*connect.Response[v1.RemoveProjectResponse], error)
	// Settings overlay (spec §18.2): enumerate models and change a session's
	// interaction level / per-role model assignment mid-flight.
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	SetInteractionLevel(context.Context, *connect.Request[v1.SetInteractionLevelRequest]) (*connect.Response[v1.SetInteractionLevelResponse], error)
	SetRoleConfig(context.Context, *connect.Request[v1.SetRoleConfigRequest]) (*connect.Response[v1.SetRoleConfigResponse], error)
	SetThinking(context.Context, *connect.Request[v1.SetThinkingRequest]) (*connect.Response[v1.SetThinkingResponse], error)
	// Model backends (spec §18.2): add/edit/remove a logical model backend at
	// runtime; optionally persisted to ycc.toml.
	UpsertModel(context.Context, *connect.Request[v1.UpsertModelRequest]) (*connect.Response[v1.UpsertModelResponse], error)
	RemoveModel(context.Context, *connect.Request[v1.RemoveModelRequest]) (*connect.Response[v1.RemoveModelResponse], error)
	GetModelConfig(context.Context, *connect.Request[v1.GetModelConfigRequest]) (*connect.Response[v1.GetModelConfigResponse], error)
	DiscoverModels(context.Context, *connect.Request[v1.DiscoverModelsRequest]) (*connect.Response[v1.DiscoverModelsResponse], error)
	// Backlog browser (spec §18.5): read-only access to the durable backlog.
	ListBacklog(context.Context, *connect.Request[v1.ListBacklogRequest]) (*connect.Response[v1.ListBacklogResponse], error)
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
	// UpdateTask grooms a backlog task in place (spec §18.5, task 0099): change
	// status/priority/title, or (no mutation fields) refresh + regenerate the index.
	UpdateTask(context.Context, *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error)
	// Plan library (reusable runbooks, task 0020/0077): read-only access to the
	// in-repo plans/*.md so clients can browse and view saved plans.
	ListPlans(context.Context, *connect.Request[v1.ListPlansRequest]) (*connect.Response[v1.ListPlansResponse], error)
	GetPlan(context.Context, *connect.Request[v1.GetPlanRequest]) (*connect.Response[v1.GetPlanResponse], error)
	// Quick-add backlog capture (spec §18.2, task 0016): run a lightweight,
	// off-stream capture agent that turns a natural-language description into a
	// backlog task without disturbing the running session. May ask ONE clarifying
	// question, carried back via prior_question/prior_answer.
	//
	// Streams the capture agent's action log (the same Event stream as Subscribe)
	// so the client can show live progress, ending with a terminal
	// `capture_result` event whose data_json carries {task_id,title,question} on
	// success (or {error} on failure).
	CaptureBacklogItem(context.Context, *connect.Request[v1.CaptureBacklogItemRequest], *connect.ServerStream[v1.Event]) error
	// Usage/cost breakdown (spec §20): aggregated, priced token usage by task ×
	// model × day so clients can render the cost breakdown.
	GetUsage(context.Context, *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error)
	// Spend guard (task 0137, spec §20.6): return the configured budget caps so the
	// TUI work-loop driver can enforce the per-loop-run cap client-side.
	GetBudget(context.Context, *connect.Request[v1.GetBudgetRequest]) (*connect.Response[v1.GetBudgetResponse], error)
	// Parallel workstreams (docs/design/parallel-workstreams.md §6, §8): spawn a
	// worktree+session, list them, preview/merge a branch back to base with the
	// conflict-aware review gate, or discard one. Subscribe(session_id) is reused
	// verbatim for per-workstream event streaming (the session_id rides inside
	// WorkstreamInfo).
	SpawnWorkstream(context.Context, *connect.Request[v1.SpawnWorkstreamRequest]) (*connect.Response[v1.SpawnWorkstreamResponse], error)
	ListWorkstreams(context.Context, *connect.Request[v1.ListWorkstreamsRequest]) (*connect.Response[v1.ListWorkstreamsResponse], error)
	PreviewMerge(context.Context, *connect.Request[v1.PreviewMergeRequest]) (*connect.Response[v1.PreviewMergeResponse], error)
	MergeWorkstream(context.Context, *connect.Request[v1.MergeWorkstreamRequest]) (*connect.Response[v1.MergeWorkstreamResponse], error)
	DiscardWorkstream(context.Context, *connect.Request[v1.DiscardWorkstreamRequest]) (*connect.Response[v1.DiscardWorkstreamResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := v1.File_ycc_v1_ycc_proto.Services().ByName("SessionService").Methods()
	sessionServiceListModesHandler := connect.NewUnaryHandler(
		SessionServiceListModesProcedure,
		svc.ListModes,
		connect.WithSchema(sessionServiceMethods.ByName("ListModes")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceStartSessionHandler := connect.NewUnaryHandler(
		SessionServiceStartSessionProcedure,
		svc.StartSession,
		connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListSessionsHandler := connect.NewUnaryHandler(
		SessionServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListSessionHistoryHandler := connect.NewUnaryHandler(
		SessionServiceListSessionHistoryProcedure,
		svc.ListSessionHistory,
		connect.WithSchema(sessionServiceMethods.ByName("ListSessionHistory")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetSessionTranscriptHandler := connect.NewUnaryHandler(
		SessionServiceGetSessionTranscriptProcedure,
		svc.GetSessionTranscript,
		connect.WithSchema(sessionServiceMethods.ByName("GetSessionTranscript")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetCommitDiffHandler := connect.NewUnaryHandler(
		SessionServiceGetCommitDiffProcedure,
		svc.GetCommitDiff,
		connect.WithSchema(sessionServiceMethods.ByName("GetCommitDiff")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSubscribeHandler := connect.NewServerStreamHandler(
		SessionServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(sessionServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSendInputHandler := connect.NewUnaryHandler(
		SessionServiceSendInputProcedure,
		svc.SendInput,
		connect.WithSchema(sessionServiceMethods.ByName("SendInput")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceAnswerQuestionHandler := connect.NewUnaryHandler(
		SessionServiceAnswerQuestionProcedure,
		svc.AnswerQuestion,
		connect.WithSchema(sessionServiceMethods.ByName("AnswerQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceAnswerQuestionsHandler := connect.NewUnaryHandler(
		SessionServiceAnswerQuestionsProcedure,
		svc.AnswerQuestions,
		connect.WithSchema(sessionServiceMethods.ByName("AnswerQuestions")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceInterruptHandler := connect.NewUnaryHandler(
		SessionServiceInterruptProcedure,
		svc.Interrupt,
		connect.WithSchema(sessionServiceMethods.ByName("Interrupt")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceResumeHandler := connect.NewUnaryHandler(
		SessionServiceResumeProcedure,
		svc.Resume,
		connect.WithSchema(sessionServiceMethods.ByName("Resume")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceStopSessionHandler := connect.NewUnaryHandler(
		SessionServiceStopSessionProcedure,
		svc.StopSession,
		connect.WithSchema(sessionServiceMethods.ByName("StopSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceResumeSessionHandler := connect.NewUnaryHandler(
		SessionServiceResumeSessionProcedure,
		svc.ResumeSession,
		connect.WithSchema(sessionServiceMethods.ByName("ResumeSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListProjectsHandler := connect.NewUnaryHandler(
		SessionServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(sessionServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceAddProjectHandler := connect.NewUnaryHandler(
		SessionServiceAddProjectProcedure,
		svc.AddProject,
		connect.WithSchema(sessionServiceMethods.ByName("AddProject")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceRemoveProjectHandler := connect.NewUnaryHandler(
		SessionServiceRemoveProjectProcedure,
		svc.RemoveProject,
		connect.WithSchema(sessionServiceMethods.ByName("RemoveProject")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListModelsHandler := connect.NewUnaryHandler(
		SessionServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(sessionServiceMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSetInteractionLevelHandler := connect.NewUnaryHandler(
		SessionServiceSetInteractionLevelProcedure,
		svc.SetInteractionLevel,
		connect.WithSchema(sessionServiceMethods.ByName("SetInteractionLevel")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSetRoleConfigHandler := connect.NewUnaryHandler(
		SessionServiceSetRoleConfigProcedure,
		svc.SetRoleConfig,
		connect.WithSchema(sessionServiceMethods.ByName("SetRoleConfig")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSetThinkingHandler := connect.NewUnaryHandler(
		SessionServiceSetThinkingProcedure,
		svc.SetThinking,
		connect.WithSchema(sessionServiceMethods.ByName("SetThinking")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceUpsertModelHandler := connect.NewUnaryHandler(
		SessionServiceUpsertModelProcedure,
		svc.UpsertModel,
		connect.WithSchema(sessionServiceMethods.ByName("UpsertModel")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceRemoveModelHandler := connect.NewUnaryHandler(
		SessionServiceRemoveModelProcedure,
		svc.RemoveModel,
		connect.WithSchema(sessionServiceMethods.ByName("RemoveModel")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetModelConfigHandler := connect.NewUnaryHandler(
		SessionServiceGetModelConfigProcedure,
		svc.GetModelConfig,
		connect.WithSchema(sessionServiceMethods.ByName("GetModelConfig")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceDiscoverModelsHandler := connect.NewUnaryHandler(
		SessionServiceDiscoverModelsProcedure,
		svc.DiscoverModels,
		connect.WithSchema(sessionServiceMethods.ByName("DiscoverModels")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListBacklogHandler := connect.NewUnaryHandler(
		SessionServiceListBacklogProcedure,
		svc.ListBacklog,
		connect.WithSchema(sessionServiceMethods.ByName("ListBacklog")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetTaskHandler := connect.NewUnaryHandler(
		SessionServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(sessionServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceUpdateTaskHandler := connect.NewUnaryHandler(
		SessionServiceUpdateTaskProcedure,
		svc.UpdateTask,
		connect.WithSchema(sessionServiceMethods.ByName("UpdateTask")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListPlansHandler := connect.NewUnaryHandler(
		SessionServiceListPlansProcedure,
		svc.ListPlans,
		connect.WithSchema(sessionServiceMethods.ByName("ListPlans")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetPlanHandler := connect.NewUnaryHandler(
		SessionServiceGetPlanProcedure,
		svc.GetPlan,
		connect.WithSchema(sessionServiceMethods.ByName("GetPlan")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceCaptureBacklogItemHandler := connect.NewServerStreamHandler(
		SessionServiceCaptureBacklogItemProcedure,
		svc.CaptureBacklogItem,
		connect.WithSchema(sessionServiceMethods.ByName("CaptureBacklogItem")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetUsageHandler := connect.NewUnaryHandler(
		SessionServiceGetUsageProcedure,
		svc.GetUsage,
		connect.WithSchema(sessionServiceMethods.ByName("GetUsage")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetBudgetHandler := connect.NewUnaryHandler(
		SessionServiceGetBudgetProcedure,
		svc.GetBudget,
		connect.WithSchema(sessionServiceMethods.ByName("GetBudget")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSpawnWorkstreamHandler := connect.NewUnaryHandler(
		SessionServiceSpawnWorkstreamProcedure,
		svc.SpawnWorkstream,
		connect.WithSchema(sessionServiceMethods.ByName("SpawnWorkstream")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListWorkstreamsHandler := connect.NewUnaryHandler(
		SessionServiceListWorkstreamsProcedure,
		svc.ListWorkstreams,
		connect.WithSchema(sessionServiceMethods.ByName("ListWorkstreams")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServicePreviewMergeHandler := connect.NewUnaryHandler(
		SessionServicePreviewMergeProcedure,
		svc.PreviewMerge,
		connect.WithSchema(sessionServiceMethods.ByName("PreviewMerge")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceMergeWorkstreamHandler := connect.NewUnaryHandler(
		SessionServiceMergeWorkstreamProcedure,
		svc.MergeWorkstream,
		connect.WithSchema(sessionServiceMethods.ByName("MergeWorkstream")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceDiscardWorkstreamHandler := connect.NewUnaryHandler(
		SessionServiceDiscardWorkstreamProcedure,
		svc.DiscardWorkstream,
		connect.WithSchema(sessionServiceMethods.ByName("DiscardWorkstream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ycc.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceListModesProcedure:
			sessionServiceListModesHandler.ServeHTTP(w, r)
		case SessionServiceStartSessionProcedure:
			sessionServiceStartSessionHandler.ServeHTTP(w, r)
		case SessionServiceListSessionsProcedure:
			sessionServiceListSessionsHandler.ServeHTTP(w, r)
		case SessionServiceListSessionHistoryProcedure:
			sessionServiceListSessionHistoryHandler.ServeHTTP(w, r)
		case SessionServiceGetSessionTranscriptProcedure:
			sessionServiceGetSessionTranscriptHandler.ServeHTTP(w, r)
		case SessionServiceGetCommitDiffProcedure:
			sessionServiceGetCommitDiffHandler.ServeHTTP(w, r)
		case SessionServiceSubscribeProcedure:
			sessionServiceSubscribeHandler.ServeHTTP(w, r)
		case SessionServiceSendInputProcedure:
			sessionServiceSendInputHandler.ServeHTTP(w, r)
		case SessionServiceAnswerQuestionProcedure:
			sessionServiceAnswerQuestionHandler.ServeHTTP(w, r)
		case SessionServiceAnswerQuestionsProcedure:
			sessionServiceAnswerQuestionsHandler.ServeHTTP(w, r)
		case SessionServiceInterruptProcedure:
			sessionServiceInterruptHandler.ServeHTTP(w, r)
		case SessionServiceResumeProcedure:
			sessionServiceResumeHandler.ServeHTTP(w, r)
		case SessionServiceStopSessionProcedure:
			sessionServiceStopSessionHandler.ServeHTTP(w, r)
		case SessionServiceResumeSessionProcedure:
			sessionServiceResumeSessionHandler.ServeHTTP(w, r)
		case SessionServiceListProjectsProcedure:
			sessionServiceListProjectsHandler.ServeHTTP(w, r)
		case SessionServiceAddProjectProcedure:
			sessionServiceAddProjectHandler.ServeHTTP(w, r)
		case SessionServiceRemoveProjectProcedure:
			sessionServiceRemoveProjectHandler.ServeHTTP(w, r)
		case SessionServiceListModelsProcedure:
			sessionServiceListModelsHandler.ServeHTTP(w, r)
		case SessionServiceSetInteractionLevelProcedure:
			sessionServiceSetInteractionLevelHandler.ServeHTTP(w, r)
		case SessionServiceSetRoleConfigProcedure:
			sessionServiceSetRoleConfigHandler.ServeHTTP(w, r)
		case SessionServiceSetThinkingProcedure:
			sessionServiceSetThinkingHandler.ServeHTTP(w, r)
		case SessionServiceUpsertModelProcedure:
			sessionServiceUpsertModelHandler.ServeHTTP(w, r)
		case SessionServiceRemoveModelProcedure:
			sessionServiceRemoveModelHandler.ServeHTTP(w, r)
		case SessionServiceGetModelConfigProcedure:
			sessionServiceGetModelConfigHandler.ServeHTTP(w, r)
		case SessionServiceDiscoverModelsProcedure:
			sessionServiceDiscoverModelsHandler.ServeHTTP(w, r)
		case SessionServiceListBacklogProcedure:
			sessionServiceListBacklogHandler.ServeHTTP(w, r)
		case SessionServiceGetTaskProcedure:
			sessionServiceGetTaskHandler.ServeHTTP(w, r)
		case SessionServiceUpdateTaskProcedure:
			sessionServiceUpdateTaskHandler.ServeHTTP(w, r)
		case SessionServiceListPlansProcedure:
			sessionServiceListPlansHandler.ServeHTTP(w, r)
		case SessionServiceGetPlanProcedure:
			sessionServiceGetPlanHandler.ServeHTTP(w, r)
		case SessionServiceCaptureBacklogItemProcedure:
			sessionServiceCaptureBacklogItemHandler.ServeHTTP(w, r)
		case SessionServiceGetUsageProcedure:
			sessionServiceGetUsageHandler.ServeHTTP(w, r)
		case SessionServiceGetBudgetProcedure:
			sessionServiceGetBudgetHandler.ServeHTTP(w, r)
		case SessionServiceSpawnWorkstreamProcedure:
			sessionServiceSpawnWorkstreamHandler.ServeHTTP(w, r)
		case SessionServiceListWorkstreamsProcedure:
			sessionServiceListWorkstreamsHandler.ServeHTTP(w, r)
		case SessionServicePreviewMergeProcedure:
			sessionServicePreviewMergeHandler.ServeHTTP(w, r)
		case SessionServiceMergeWorkstreamProcedure:
			sessionServiceMergeWorkstreamHandler.ServeHTTP(w, r)
		case SessionServiceDiscardWorkstreamProcedure:
			sessionServiceDiscardWorkstreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) ListModes(context.Context, *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListModes is not implemented"))
}

func (UnimplementedSessionServiceHandler) StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.StartSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListSessions is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListSessionHistory(context.Context, *connect.Request[v1.ListSessionHistoryRequest]) (*connect.Response[v1.ListSessionHistoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListSessionHistory is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetSessionTranscript(context.Context, *connect.Request[v1.GetSessionTranscriptRequest]) (*connect.Response[v1.GetSessionTranscriptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.GetSessionTranscript is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetCommitDiff(context.Context, *connect.Request[v1.GetCommitDiffRequest]) (*connect.Response[v1.GetCommitDiffResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.GetCommitDiff is not implemented"))
}

func (UnimplementedSessionServiceHandler) Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.Event]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.Subscribe is not implemented"))
}

func (UnimplementedSessionServiceHandler) SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SendInput is not implemented"))
}

func (UnimplementedSessionServiceHandler) AnswerQuestion(context.Context, *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.AnswerQuestion is not implemented"))
}

func (UnimplementedSessionServiceHandler) AnswerQuestions(context.Context, *connect.Request[v1.AnswerQuestionsRequest]) (*connect.Response[v1.AnswerQuestionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.AnswerQuestions is not implemented"))
}

func (UnimplementedSessionServiceHandler) Interrupt(context.Context, *connect.Request[v1.InterruptRequest]) (*connect.Response[v1.InterruptResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.Interrupt is not implemented"))
}

func (UnimplementedSessionServiceHandler) Resume(context.Context, *connect.Request[v1.ResumeRequest]) (*connect.Response[v1.ResumeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.Resume is not implemented"))
}

func (UnimplementedSessionServiceHandler) StopSession(context.Context, *connect.Request[v1.StopSessionRequest]) (*connect.Response[v1.StopSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.StopSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) ResumeSession(context.Context, *connect.Request[v1.ResumeSessionRequest]) (*connect.Response[v1.ResumeSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ResumeSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListProjects is not implemented"))
}

func (UnimplementedSessionServiceHandler) AddProject(context.Context, *connect.Request[v1.AddProjectRequest]) (*connect.Response[v1.AddProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.AddProject is not implemented"))
}

func (UnimplementedSessionServiceHandler) RemoveProject(context.Context, *connect.Request[v1.RemoveProjectRequest]) (*connect.Response[v1.RemoveProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.RemoveProject is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListModels is not implemented"))
}

func (UnimplementedSessionServiceHandler) SetInteractionLevel(context.Context, *connect.Request[v1.SetInteractionLevelRequest]) (*connect.Response[v1.SetInteractionLevelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SetInteractionLevel is not implemented"))
}

func (UnimplementedSessionServiceHandler) SetRoleConfig(context.Context, *connect.Request[v1.SetRoleConfigRequest]) (*connect.Response[v1.SetRoleConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SetRoleConfig is not implemented"))
}

func (UnimplementedSessionServiceHandler) SetThinking(context.Context, *connect.Request[v1.SetThinkingRequest]) (*connect.Response[v1.SetThinkingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SetThinking is not implemented"))
}

func (UnimplementedSessionServiceHandler) UpsertModel(context.Context, *connect.Request[v1.UpsertModelRequest]) (*connect.Response[v1.UpsertModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.UpsertModel is not implemented"))
}

func (UnimplementedSessionServiceHandler) RemoveModel(context.Context, *connect.Request[v1.RemoveModelRequest]) (*connect.Response[v1.RemoveModelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.RemoveModel is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetModelConfig(context.Context, *connect.Request[v1.GetModelConfigRequest]) (*connect.Response[v1.GetModelConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.GetModelConfig is not implemented"))
}

func (UnimplementedSessionServiceHandler) DiscoverModels(context.Context, *connect.Request[v1.DiscoverModelsRequest]) (*connect.Response[v1.DiscoverModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.DiscoverModels is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListBacklog(context.Context, *connect.Request[v1.ListBacklogRequest]) (*connect.Response[v1.ListBacklogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListBacklog is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.GetTask is not implemented"))
}

func (UnimplementedSessionServiceHandler) UpdateTask(context.Context, *connect.Request[v1.UpdateTaskRequest]) (*connect.Response[v1.UpdateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.UpdateTask is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListPlans(context.Context, *connect.Request[v1.ListPlansRequest]) (*connect.Response[v1.ListPlansResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListPlans is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetPlan(context.Context, *connect.Request[v1.GetPlanRequest]) (*connect.Response[v1.GetPlanResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.GetPlan is not implemented"))
}

func (UnimplementedSessionServiceHandler) CaptureBacklogItem(context.Context, *connect.Request[v1.CaptureBacklogItemRequest], *connect.ServerStream[v1.Event]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.CaptureBacklogItem is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetUsage(context.Context, *connect.Request[v1.GetUsageRequest]) (*connect.Response[v1.GetUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.GetUsage is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetBudget(context.Context, *connect.Request[v1.GetBudgetRequest]) (*connect.Response[v1.GetBudgetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.GetBudget is not implemented"))
}

func (UnimplementedSessionServiceHandler) SpawnWorkstream(context.Context, *connect.Request[v1.SpawnWorkstreamRequest]) (*connect.Response[v1.SpawnWorkstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SpawnWorkstream is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListWorkstreams(context.Context, *connect.Request[v1.ListWorkstreamsRequest]) (*connect.Response[v1.ListWorkstreamsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListWorkstreams is not implemented"))
}

func (UnimplementedSessionServiceHandler) PreviewMerge(context.Context, *connect.Request[v1.PreviewMergeRequest]) (*connect.Response[v1.PreviewMergeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.PreviewMerge is not implemented"))
}

func (UnimplementedSessionServiceHandler) MergeWorkstream(context.Context, *connect.Request[v1.MergeWorkstreamRequest]) (*connect.Response[v1.MergeWorkstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.MergeWorkstream is not implemented"))
}

func (UnimplementedSessionServiceHandler) DiscardWorkstream(context.Context, *connect.Request[v1.DiscardWorkstreamRequest]) (*connect.Response[v1.DiscardWorkstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.DiscardWorkstream is not implemented"))
}
