// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ycc/v1/ycc.proto

package yccv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/whyrusleeping/ycc/proto/ycc/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "ycc.v1.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceListModesProcedure is the fully-qualified name of the SessionService's ListModes
	// RPC.
	SessionServiceListModesProcedure = "/ycc.v1.SessionService/ListModes"
	// SessionServiceStartSessionProcedure is the fully-qualified name of the SessionService's
	// StartSession RPC.
	SessionServiceStartSessionProcedure = "/ycc.v1.SessionService/StartSession"
	// SessionServiceListSessionsProcedure is the fully-qualified name of the SessionService's
	// ListSessions RPC.
	SessionServiceListSessionsProcedure = "/ycc.v1.SessionService/ListSessions"
	// SessionServiceSubscribeProcedure is the fully-qualified name of the SessionService's Subscribe
	// RPC.
	SessionServiceSubscribeProcedure = "/ycc.v1.SessionService/Subscribe"
	// SessionServiceSendInputProcedure is the fully-qualified name of the SessionService's SendInput
	// RPC.
	SessionServiceSendInputProcedure = "/ycc.v1.SessionService/SendInput"
	// SessionServiceAnswerQuestionProcedure is the fully-qualified name of the SessionService's
	// AnswerQuestion RPC.
	SessionServiceAnswerQuestionProcedure = "/ycc.v1.SessionService/AnswerQuestion"
	// SessionServiceListProjectsProcedure is the fully-qualified name of the SessionService's
	// ListProjects RPC.
	SessionServiceListProjectsProcedure = "/ycc.v1.SessionService/ListProjects"
	// SessionServiceAddProjectProcedure is the fully-qualified name of the SessionService's AddProject
	// RPC.
	SessionServiceAddProjectProcedure = "/ycc.v1.SessionService/AddProject"
	// SessionServiceRemoveProjectProcedure is the fully-qualified name of the SessionService's
	// RemoveProject RPC.
	SessionServiceRemoveProjectProcedure = "/ycc.v1.SessionService/RemoveProject"
	// SessionServiceListModelsProcedure is the fully-qualified name of the SessionService's ListModels
	// RPC.
	SessionServiceListModelsProcedure = "/ycc.v1.SessionService/ListModels"
	// SessionServiceSetInteractionLevelProcedure is the fully-qualified name of the SessionService's
	// SetInteractionLevel RPC.
	SessionServiceSetInteractionLevelProcedure = "/ycc.v1.SessionService/SetInteractionLevel"
	// SessionServiceSetRoleConfigProcedure is the fully-qualified name of the SessionService's
	// SetRoleConfig RPC.
	SessionServiceSetRoleConfigProcedure = "/ycc.v1.SessionService/SetRoleConfig"
	// SessionServiceSetThinkingProcedure is the fully-qualified name of the SessionService's
	// SetThinking RPC.
	SessionServiceSetThinkingProcedure = "/ycc.v1.SessionService/SetThinking"
	// SessionServiceListBacklogProcedure is the fully-qualified name of the SessionService's
	// ListBacklog RPC.
	SessionServiceListBacklogProcedure = "/ycc.v1.SessionService/ListBacklog"
	// SessionServiceGetTaskProcedure is the fully-qualified name of the SessionService's GetTask RPC.
	SessionServiceGetTaskProcedure = "/ycc.v1.SessionService/GetTask"
)

// SessionServiceClient is a client for the ycc.v1.SessionService service.
type SessionServiceClient interface {
	ListModes(context.Context, *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error)
	StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.Event], error)
	SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error)
	AnswerQuestion(context.Context, *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error)
	// Projects — persistent multi-project daemon (spec §3.1).
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	AddProject(context.Context, *connect.Request[v1.AddProjectRequest]) (*connect.Response[v1.AddProjectResponse], error)
	RemoveProject(context.Context, *connect.Request[v1.RemoveProjectRequest]) (*connect.Response[v1.RemoveProjectResponse], error)
	// Settings overlay (spec §18.2): enumerate models and change a session's
	// interaction level / per-role model assignment mid-flight.
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	SetInteractionLevel(context.Context, *connect.Request[v1.SetInteractionLevelRequest]) (*connect.Response[v1.SetInteractionLevelResponse], error)
	SetRoleConfig(context.Context, *connect.Request[v1.SetRoleConfigRequest]) (*connect.Response[v1.SetRoleConfigResponse], error)
	SetThinking(context.Context, *connect.Request[v1.SetThinkingRequest]) (*connect.Response[v1.SetThinkingResponse], error)
	// Backlog browser (spec §18.5): read-only access to the durable backlog.
	ListBacklog(context.Context, *connect.Request[v1.ListBacklogRequest]) (*connect.Response[v1.ListBacklogResponse], error)
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
}

// NewSessionServiceClient constructs a client for the ycc.v1.SessionService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := v1.File_ycc_v1_ycc_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		listModes: connect.NewClient[v1.ListModesRequest, v1.ListModesResponse](
			httpClient,
			baseURL+SessionServiceListModesProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListModes")),
			connect.WithClientOptions(opts...),
		),
		startSession: connect.NewClient[v1.StartSessionRequest, v1.StartSessionResponse](
			httpClient,
			baseURL+SessionServiceStartSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+SessionServiceListSessionsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[v1.SubscribeRequest, v1.Event](
			httpClient,
			baseURL+SessionServiceSubscribeProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		sendInput: connect.NewClient[v1.SendInputRequest, v1.SendInputResponse](
			httpClient,
			baseURL+SessionServiceSendInputProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SendInput")),
			connect.WithClientOptions(opts...),
		),
		answerQuestion: connect.NewClient[v1.AnswerQuestionRequest, v1.AnswerQuestionResponse](
			httpClient,
			baseURL+SessionServiceAnswerQuestionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("AnswerQuestion")),
			connect.WithClientOptions(opts...),
		),
		listProjects: connect.NewClient[v1.ListProjectsRequest, v1.ListProjectsResponse](
			httpClient,
			baseURL+SessionServiceListProjectsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListProjects")),
			connect.WithClientOptions(opts...),
		),
		addProject: connect.NewClient[v1.AddProjectRequest, v1.AddProjectResponse](
			httpClient,
			baseURL+SessionServiceAddProjectProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("AddProject")),
			connect.WithClientOptions(opts...),
		),
		removeProject: connect.NewClient[v1.RemoveProjectRequest, v1.RemoveProjectResponse](
			httpClient,
			baseURL+SessionServiceRemoveProjectProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("RemoveProject")),
			connect.WithClientOptions(opts...),
		),
		listModels: connect.NewClient[v1.ListModelsRequest, v1.ListModelsResponse](
			httpClient,
			baseURL+SessionServiceListModelsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListModels")),
			connect.WithClientOptions(opts...),
		),
		setInteractionLevel: connect.NewClient[v1.SetInteractionLevelRequest, v1.SetInteractionLevelResponse](
			httpClient,
			baseURL+SessionServiceSetInteractionLevelProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SetInteractionLevel")),
			connect.WithClientOptions(opts...),
		),
		setRoleConfig: connect.NewClient[v1.SetRoleConfigRequest, v1.SetRoleConfigResponse](
			httpClient,
			baseURL+SessionServiceSetRoleConfigProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SetRoleConfig")),
			connect.WithClientOptions(opts...),
		),
		setThinking: connect.NewClient[v1.SetThinkingRequest, v1.SetThinkingResponse](
			httpClient,
			baseURL+SessionServiceSetThinkingProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SetThinking")),
			connect.WithClientOptions(opts...),
		),
		listBacklog: connect.NewClient[v1.ListBacklogRequest, v1.ListBacklogResponse](
			httpClient,
			baseURL+SessionServiceListBacklogProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListBacklog")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[v1.GetTaskRequest, v1.GetTaskResponse](
			httpClient,
			baseURL+SessionServiceGetTaskProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	listModes           *connect.Client[v1.ListModesRequest, v1.ListModesResponse]
	startSession        *connect.Client[v1.StartSessionRequest, v1.StartSessionResponse]
	listSessions        *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	subscribe           *connect.Client[v1.SubscribeRequest, v1.Event]
	sendInput           *connect.Client[v1.SendInputRequest, v1.SendInputResponse]
	answerQuestion      *connect.Client[v1.AnswerQuestionRequest, v1.AnswerQuestionResponse]
	listProjects        *connect.Client[v1.ListProjectsRequest, v1.ListProjectsResponse]
	addProject          *connect.Client[v1.AddProjectRequest, v1.AddProjectResponse]
	removeProject       *connect.Client[v1.RemoveProjectRequest, v1.RemoveProjectResponse]
	listModels          *connect.Client[v1.ListModelsRequest, v1.ListModelsResponse]
	setInteractionLevel *connect.Client[v1.SetInteractionLevelRequest, v1.SetInteractionLevelResponse]
	setRoleConfig       *connect.Client[v1.SetRoleConfigRequest, v1.SetRoleConfigResponse]
	setThinking         *connect.Client[v1.SetThinkingRequest, v1.SetThinkingResponse]
	listBacklog         *connect.Client[v1.ListBacklogRequest, v1.ListBacklogResponse]
	getTask             *connect.Client[v1.GetTaskRequest, v1.GetTaskResponse]
}

// ListModes calls ycc.v1.SessionService.ListModes.
func (c *sessionServiceClient) ListModes(ctx context.Context, req *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error) {
	return c.listModes.CallUnary(ctx, req)
}

// StartSession calls ycc.v1.SessionService.StartSession.
func (c *sessionServiceClient) StartSession(ctx context.Context, req *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error) {
	return c.startSession.CallUnary(ctx, req)
}

// ListSessions calls ycc.v1.SessionService.ListSessions.
func (c *sessionServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// Subscribe calls ycc.v1.SessionService.Subscribe.
func (c *sessionServiceClient) Subscribe(ctx context.Context, req *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.Event], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// SendInput calls ycc.v1.SessionService.SendInput.
func (c *sessionServiceClient) SendInput(ctx context.Context, req *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error) {
	return c.sendInput.CallUnary(ctx, req)
}

// AnswerQuestion calls ycc.v1.SessionService.AnswerQuestion.
func (c *sessionServiceClient) AnswerQuestion(ctx context.Context, req *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error) {
	return c.answerQuestion.CallUnary(ctx, req)
}

// ListProjects calls ycc.v1.SessionService.ListProjects.
func (c *sessionServiceClient) ListProjects(ctx context.Context, req *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return c.listProjects.CallUnary(ctx, req)
}

// AddProject calls ycc.v1.SessionService.AddProject.
func (c *sessionServiceClient) AddProject(ctx context.Context, req *connect.Request[v1.AddProjectRequest]) (*connect.Response[v1.AddProjectResponse], error) {
	return c.addProject.CallUnary(ctx, req)
}

// RemoveProject calls ycc.v1.SessionService.RemoveProject.
func (c *sessionServiceClient) RemoveProject(ctx context.Context, req *connect.Request[v1.RemoveProjectRequest]) (*connect.Response[v1.RemoveProjectResponse], error) {
	return c.removeProject.CallUnary(ctx, req)
}

// ListModels calls ycc.v1.SessionService.ListModels.
func (c *sessionServiceClient) ListModels(ctx context.Context, req *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return c.listModels.CallUnary(ctx, req)
}

// SetInteractionLevel calls ycc.v1.SessionService.SetInteractionLevel.
func (c *sessionServiceClient) SetInteractionLevel(ctx context.Context, req *connect.Request[v1.SetInteractionLevelRequest]) (*connect.Response[v1.SetInteractionLevelResponse], error) {
	return c.setInteractionLevel.CallUnary(ctx, req)
}

// SetRoleConfig calls ycc.v1.SessionService.SetRoleConfig.
func (c *sessionServiceClient) SetRoleConfig(ctx context.Context, req *connect.Request[v1.SetRoleConfigRequest]) (*connect.Response[v1.SetRoleConfigResponse], error) {
	return c.setRoleConfig.CallUnary(ctx, req)
}

// SetThinking calls ycc.v1.SessionService.SetThinking.
func (c *sessionServiceClient) SetThinking(ctx context.Context, req *connect.Request[v1.SetThinkingRequest]) (*connect.Response[v1.SetThinkingResponse], error) {
	return c.setThinking.CallUnary(ctx, req)
}

// ListBacklog calls ycc.v1.SessionService.ListBacklog.
func (c *sessionServiceClient) ListBacklog(ctx context.Context, req *connect.Request[v1.ListBacklogRequest]) (*connect.Response[v1.ListBacklogResponse], error) {
	return c.listBacklog.CallUnary(ctx, req)
}

// GetTask calls ycc.v1.SessionService.GetTask.
func (c *sessionServiceClient) GetTask(ctx context.Context, req *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the ycc.v1.SessionService service.
type SessionServiceHandler interface {
	ListModes(context.Context, *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error)
	StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.Event]) error
	SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error)
	AnswerQuestion(context.Context, *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error)
	// Projects — persistent multi-project daemon (spec §3.1).
	ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error)
	AddProject(context.Context, *connect.Request[v1.AddProjectRequest]) (*connect.Response[v1.AddProjectResponse], error)
	RemoveProject(context.Context, *connect.Request[v1.RemoveProjectRequest]) (*connect.Response[v1.RemoveProjectResponse], error)
	// Settings overlay (spec §18.2): enumerate models and change a session's
	// interaction level / per-role model assignment mid-flight.
	ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error)
	SetInteractionLevel(context.Context, *connect.Request[v1.SetInteractionLevelRequest]) (*connect.Response[v1.SetInteractionLevelResponse], error)
	SetRoleConfig(context.Context, *connect.Request[v1.SetRoleConfigRequest]) (*connect.Response[v1.SetRoleConfigResponse], error)
	SetThinking(context.Context, *connect.Request[v1.SetThinkingRequest]) (*connect.Response[v1.SetThinkingResponse], error)
	// Backlog browser (spec §18.5): read-only access to the durable backlog.
	ListBacklog(context.Context, *connect.Request[v1.ListBacklogRequest]) (*connect.Response[v1.ListBacklogResponse], error)
	GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := v1.File_ycc_v1_ycc_proto.Services().ByName("SessionService").Methods()
	sessionServiceListModesHandler := connect.NewUnaryHandler(
		SessionServiceListModesProcedure,
		svc.ListModes,
		connect.WithSchema(sessionServiceMethods.ByName("ListModes")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceStartSessionHandler := connect.NewUnaryHandler(
		SessionServiceStartSessionProcedure,
		svc.StartSession,
		connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListSessionsHandler := connect.NewUnaryHandler(
		SessionServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSubscribeHandler := connect.NewServerStreamHandler(
		SessionServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(sessionServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSendInputHandler := connect.NewUnaryHandler(
		SessionServiceSendInputProcedure,
		svc.SendInput,
		connect.WithSchema(sessionServiceMethods.ByName("SendInput")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceAnswerQuestionHandler := connect.NewUnaryHandler(
		SessionServiceAnswerQuestionProcedure,
		svc.AnswerQuestion,
		connect.WithSchema(sessionServiceMethods.ByName("AnswerQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListProjectsHandler := connect.NewUnaryHandler(
		SessionServiceListProjectsProcedure,
		svc.ListProjects,
		connect.WithSchema(sessionServiceMethods.ByName("ListProjects")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceAddProjectHandler := connect.NewUnaryHandler(
		SessionServiceAddProjectProcedure,
		svc.AddProject,
		connect.WithSchema(sessionServiceMethods.ByName("AddProject")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceRemoveProjectHandler := connect.NewUnaryHandler(
		SessionServiceRemoveProjectProcedure,
		svc.RemoveProject,
		connect.WithSchema(sessionServiceMethods.ByName("RemoveProject")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListModelsHandler := connect.NewUnaryHandler(
		SessionServiceListModelsProcedure,
		svc.ListModels,
		connect.WithSchema(sessionServiceMethods.ByName("ListModels")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSetInteractionLevelHandler := connect.NewUnaryHandler(
		SessionServiceSetInteractionLevelProcedure,
		svc.SetInteractionLevel,
		connect.WithSchema(sessionServiceMethods.ByName("SetInteractionLevel")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSetRoleConfigHandler := connect.NewUnaryHandler(
		SessionServiceSetRoleConfigProcedure,
		svc.SetRoleConfig,
		connect.WithSchema(sessionServiceMethods.ByName("SetRoleConfig")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSetThinkingHandler := connect.NewUnaryHandler(
		SessionServiceSetThinkingProcedure,
		svc.SetThinking,
		connect.WithSchema(sessionServiceMethods.ByName("SetThinking")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListBacklogHandler := connect.NewUnaryHandler(
		SessionServiceListBacklogProcedure,
		svc.ListBacklog,
		connect.WithSchema(sessionServiceMethods.ByName("ListBacklog")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetTaskHandler := connect.NewUnaryHandler(
		SessionServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(sessionServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ycc.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceListModesProcedure:
			sessionServiceListModesHandler.ServeHTTP(w, r)
		case SessionServiceStartSessionProcedure:
			sessionServiceStartSessionHandler.ServeHTTP(w, r)
		case SessionServiceListSessionsProcedure:
			sessionServiceListSessionsHandler.ServeHTTP(w, r)
		case SessionServiceSubscribeProcedure:
			sessionServiceSubscribeHandler.ServeHTTP(w, r)
		case SessionServiceSendInputProcedure:
			sessionServiceSendInputHandler.ServeHTTP(w, r)
		case SessionServiceAnswerQuestionProcedure:
			sessionServiceAnswerQuestionHandler.ServeHTTP(w, r)
		case SessionServiceListProjectsProcedure:
			sessionServiceListProjectsHandler.ServeHTTP(w, r)
		case SessionServiceAddProjectProcedure:
			sessionServiceAddProjectHandler.ServeHTTP(w, r)
		case SessionServiceRemoveProjectProcedure:
			sessionServiceRemoveProjectHandler.ServeHTTP(w, r)
		case SessionServiceListModelsProcedure:
			sessionServiceListModelsHandler.ServeHTTP(w, r)
		case SessionServiceSetInteractionLevelProcedure:
			sessionServiceSetInteractionLevelHandler.ServeHTTP(w, r)
		case SessionServiceSetRoleConfigProcedure:
			sessionServiceSetRoleConfigHandler.ServeHTTP(w, r)
		case SessionServiceSetThinkingProcedure:
			sessionServiceSetThinkingHandler.ServeHTTP(w, r)
		case SessionServiceListBacklogProcedure:
			sessionServiceListBacklogHandler.ServeHTTP(w, r)
		case SessionServiceGetTaskProcedure:
			sessionServiceGetTaskHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) ListModes(context.Context, *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListModes is not implemented"))
}

func (UnimplementedSessionServiceHandler) StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.StartSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListSessions is not implemented"))
}

func (UnimplementedSessionServiceHandler) Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.Event]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.Subscribe is not implemented"))
}

func (UnimplementedSessionServiceHandler) SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SendInput is not implemented"))
}

func (UnimplementedSessionServiceHandler) AnswerQuestion(context.Context, *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.AnswerQuestion is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListProjects(context.Context, *connect.Request[v1.ListProjectsRequest]) (*connect.Response[v1.ListProjectsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListProjects is not implemented"))
}

func (UnimplementedSessionServiceHandler) AddProject(context.Context, *connect.Request[v1.AddProjectRequest]) (*connect.Response[v1.AddProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.AddProject is not implemented"))
}

func (UnimplementedSessionServiceHandler) RemoveProject(context.Context, *connect.Request[v1.RemoveProjectRequest]) (*connect.Response[v1.RemoveProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.RemoveProject is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListModels(context.Context, *connect.Request[v1.ListModelsRequest]) (*connect.Response[v1.ListModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListModels is not implemented"))
}

func (UnimplementedSessionServiceHandler) SetInteractionLevel(context.Context, *connect.Request[v1.SetInteractionLevelRequest]) (*connect.Response[v1.SetInteractionLevelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SetInteractionLevel is not implemented"))
}

func (UnimplementedSessionServiceHandler) SetRoleConfig(context.Context, *connect.Request[v1.SetRoleConfigRequest]) (*connect.Response[v1.SetRoleConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SetRoleConfig is not implemented"))
}

func (UnimplementedSessionServiceHandler) SetThinking(context.Context, *connect.Request[v1.SetThinkingRequest]) (*connect.Response[v1.SetThinkingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SetThinking is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListBacklog(context.Context, *connect.Request[v1.ListBacklogRequest]) (*connect.Response[v1.ListBacklogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListBacklog is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetTask(context.Context, *connect.Request[v1.GetTaskRequest]) (*connect.Response[v1.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.GetTask is not implemented"))
}
