// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ycc/v1/ycc.proto

package yccv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/whyrusleeping/ycc/proto/ycc/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "ycc.v1.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceListModesProcedure is the fully-qualified name of the SessionService's ListModes
	// RPC.
	SessionServiceListModesProcedure = "/ycc.v1.SessionService/ListModes"
	// SessionServiceStartSessionProcedure is the fully-qualified name of the SessionService's
	// StartSession RPC.
	SessionServiceStartSessionProcedure = "/ycc.v1.SessionService/StartSession"
	// SessionServiceListSessionsProcedure is the fully-qualified name of the SessionService's
	// ListSessions RPC.
	SessionServiceListSessionsProcedure = "/ycc.v1.SessionService/ListSessions"
	// SessionServiceSubscribeProcedure is the fully-qualified name of the SessionService's Subscribe
	// RPC.
	SessionServiceSubscribeProcedure = "/ycc.v1.SessionService/Subscribe"
	// SessionServiceSendInputProcedure is the fully-qualified name of the SessionService's SendInput
	// RPC.
	SessionServiceSendInputProcedure = "/ycc.v1.SessionService/SendInput"
	// SessionServiceAnswerQuestionProcedure is the fully-qualified name of the SessionService's
	// AnswerQuestion RPC.
	SessionServiceAnswerQuestionProcedure = "/ycc.v1.SessionService/AnswerQuestion"
)

// SessionServiceClient is a client for the ycc.v1.SessionService service.
type SessionServiceClient interface {
	ListModes(context.Context, *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error)
	StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.Event], error)
	SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error)
	AnswerQuestion(context.Context, *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error)
}

// NewSessionServiceClient constructs a client for the ycc.v1.SessionService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := v1.File_ycc_v1_ycc_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		listModes: connect.NewClient[v1.ListModesRequest, v1.ListModesResponse](
			httpClient,
			baseURL+SessionServiceListModesProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListModes")),
			connect.WithClientOptions(opts...),
		),
		startSession: connect.NewClient[v1.StartSessionRequest, v1.StartSessionResponse](
			httpClient,
			baseURL+SessionServiceStartSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+SessionServiceListSessionsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[v1.SubscribeRequest, v1.Event](
			httpClient,
			baseURL+SessionServiceSubscribeProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		sendInput: connect.NewClient[v1.SendInputRequest, v1.SendInputResponse](
			httpClient,
			baseURL+SessionServiceSendInputProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("SendInput")),
			connect.WithClientOptions(opts...),
		),
		answerQuestion: connect.NewClient[v1.AnswerQuestionRequest, v1.AnswerQuestionResponse](
			httpClient,
			baseURL+SessionServiceAnswerQuestionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("AnswerQuestion")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	listModes      *connect.Client[v1.ListModesRequest, v1.ListModesResponse]
	startSession   *connect.Client[v1.StartSessionRequest, v1.StartSessionResponse]
	listSessions   *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	subscribe      *connect.Client[v1.SubscribeRequest, v1.Event]
	sendInput      *connect.Client[v1.SendInputRequest, v1.SendInputResponse]
	answerQuestion *connect.Client[v1.AnswerQuestionRequest, v1.AnswerQuestionResponse]
}

// ListModes calls ycc.v1.SessionService.ListModes.
func (c *sessionServiceClient) ListModes(ctx context.Context, req *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error) {
	return c.listModes.CallUnary(ctx, req)
}

// StartSession calls ycc.v1.SessionService.StartSession.
func (c *sessionServiceClient) StartSession(ctx context.Context, req *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error) {
	return c.startSession.CallUnary(ctx, req)
}

// ListSessions calls ycc.v1.SessionService.ListSessions.
func (c *sessionServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// Subscribe calls ycc.v1.SessionService.Subscribe.
func (c *sessionServiceClient) Subscribe(ctx context.Context, req *connect.Request[v1.SubscribeRequest]) (*connect.ServerStreamForClient[v1.Event], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// SendInput calls ycc.v1.SessionService.SendInput.
func (c *sessionServiceClient) SendInput(ctx context.Context, req *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error) {
	return c.sendInput.CallUnary(ctx, req)
}

// AnswerQuestion calls ycc.v1.SessionService.AnswerQuestion.
func (c *sessionServiceClient) AnswerQuestion(ctx context.Context, req *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error) {
	return c.answerQuestion.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the ycc.v1.SessionService service.
type SessionServiceHandler interface {
	ListModes(context.Context, *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error)
	StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error)
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.Event]) error
	SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error)
	AnswerQuestion(context.Context, *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := v1.File_ycc_v1_ycc_proto.Services().ByName("SessionService").Methods()
	sessionServiceListModesHandler := connect.NewUnaryHandler(
		SessionServiceListModesProcedure,
		svc.ListModes,
		connect.WithSchema(sessionServiceMethods.ByName("ListModes")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceStartSessionHandler := connect.NewUnaryHandler(
		SessionServiceStartSessionProcedure,
		svc.StartSession,
		connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListSessionsHandler := connect.NewUnaryHandler(
		SessionServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSubscribeHandler := connect.NewServerStreamHandler(
		SessionServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(sessionServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceSendInputHandler := connect.NewUnaryHandler(
		SessionServiceSendInputProcedure,
		svc.SendInput,
		connect.WithSchema(sessionServiceMethods.ByName("SendInput")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceAnswerQuestionHandler := connect.NewUnaryHandler(
		SessionServiceAnswerQuestionProcedure,
		svc.AnswerQuestion,
		connect.WithSchema(sessionServiceMethods.ByName("AnswerQuestion")),
		connect.WithHandlerOptions(opts...),
	)
	return "/ycc.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceListModesProcedure:
			sessionServiceListModesHandler.ServeHTTP(w, r)
		case SessionServiceStartSessionProcedure:
			sessionServiceStartSessionHandler.ServeHTTP(w, r)
		case SessionServiceListSessionsProcedure:
			sessionServiceListSessionsHandler.ServeHTTP(w, r)
		case SessionServiceSubscribeProcedure:
			sessionServiceSubscribeHandler.ServeHTTP(w, r)
		case SessionServiceSendInputProcedure:
			sessionServiceSendInputHandler.ServeHTTP(w, r)
		case SessionServiceAnswerQuestionProcedure:
			sessionServiceAnswerQuestionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) ListModes(context.Context, *connect.Request[v1.ListModesRequest]) (*connect.Response[v1.ListModesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListModes is not implemented"))
}

func (UnimplementedSessionServiceHandler) StartSession(context.Context, *connect.Request[v1.StartSessionRequest]) (*connect.Response[v1.StartSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.StartSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.ListSessions is not implemented"))
}

func (UnimplementedSessionServiceHandler) Subscribe(context.Context, *connect.Request[v1.SubscribeRequest], *connect.ServerStream[v1.Event]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.Subscribe is not implemented"))
}

func (UnimplementedSessionServiceHandler) SendInput(context.Context, *connect.Request[v1.SendInputRequest]) (*connect.Response[v1.SendInputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.SendInput is not implemented"))
}

func (UnimplementedSessionServiceHandler) AnswerQuestion(context.Context, *connect.Request[v1.AnswerQuestionRequest]) (*connect.Response[v1.AnswerQuestionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("ycc.v1.SessionService.AnswerQuestion is not implemented"))
}
