// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ycc/v1/ycc.proto

package yccv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event mirrors internal/event.Event. Data is carried as a JSON string so the
// heterogeneous per-type payload needs no proto schema churn (and matches the
// on-disk JSONL exactly).
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts            string                 `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"` // RFC3339
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DataJson      string                 `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *Event) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type StartSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Workspace        string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`                                       // workspace dir; empty => daemon default
	Mode             string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`                                                 // e.g. "work"; M1 runs a single worker agent
	InteractionLevel string                 `protobuf:"bytes,3,opt,name=interaction_level,json=interactionLevel,proto3" json:"interaction_level,omitempty"` // interactive | judgement | autonomous
	Prompt           string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`                                             // initial task prompt
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *StartSessionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StartSessionRequest) GetInteractionLevel() string {
	if x != nil {
		return x.InteractionLevel
	}
	return ""
}

func (x *StartSessionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{2}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromSeq       int64                  `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"` // replay events with seq > from_seq, then stream live
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribeRequest) GetFromSeq() int64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type SendInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputRequest) Reset() {
	*x = SendInputRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputRequest) ProtoMessage() {}

func (x *SendInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputRequest.ProtoReflect.Descriptor instead.
func (*SendInputRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{4}
}

func (x *SendInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendInputRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputResponse) Reset() {
	*x = SendInputResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputResponse) ProtoMessage() {}

func (x *SendInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputResponse.ProtoReflect.Descriptor instead.
func (*SendInputResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{5}
}

type AnswerQuestionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text      string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// option_index selects a suggested option from the question's options list
	// (0-based) when >= 0; otherwise text is taken as a free-text answer.
	OptionIndex   int32 `protobuf:"varint,3,opt,name=option_index,json=optionIndex,proto3" json:"option_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionRequest) Reset() {
	*x = AnswerQuestionRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionRequest) ProtoMessage() {}

func (x *AnswerQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionRequest.ProtoReflect.Descriptor instead.
func (*AnswerQuestionRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{6}
}

func (x *AnswerQuestionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnswerQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnswerQuestionRequest) GetOptionIndex() int32 {
	if x != nil {
		return x.OptionIndex
	}
	return 0
}

type AnswerQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionResponse) Reset() {
	*x = AnswerQuestionResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionResponse) ProtoMessage() {}

func (x *AnswerQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionResponse.ProtoReflect.Descriptor instead.
func (*AnswerQuestionResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{7}
}

type ListModesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModesRequest) Reset() {
	*x = ListModesRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModesRequest) ProtoMessage() {}

func (x *ListModesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModesRequest.ProtoReflect.Descriptor instead.
func (*ListModesRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{8}
}

type Mode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mode) Reset() {
	*x = Mode{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mode) ProtoMessage() {}

func (x *Mode) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mode.ProtoReflect.Descriptor instead.
func (*Mode) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{9}
}

func (x *Mode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListModesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modes         []*Mode                `protobuf:"bytes,1,rep,name=modes,proto3" json:"modes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModesResponse) Reset() {
	*x = ListModesResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModesResponse) ProtoMessage() {}

func (x *ListModesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModesResponse.ProtoReflect.Descriptor instead.
func (*ListModesResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{10}
}

func (x *ListModesResponse) GetModes() []*Mode {
	if x != nil {
		return x.Modes
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{11}
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // running | idle | error
	Workspace     string                 `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{12}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionInfo) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{13}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_ycc_v1_ycc_proto protoreflect.FileDescriptor

const file_ycc_v1_ycc_proto_rawDesc = "" +
	"\n" +
	"\x10ycc/v1/ycc.proto\x12\x06ycc.v1\"p\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\tR\x02ts\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\tR\bdataJson\"\x8c\x01\n" +
	"\x13StartSessionRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12+\n" +
	"\x11interaction_level\x18\x03 \x01(\tR\x10interactionLevel\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\"5\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"L\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x03R\afromSeq\"E\n" +
	"\x10SendInputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x13\n" +
	"\x11SendInputResponse\"m\n" +
	"\x15AnswerQuestionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\foption_index\x18\x03 \x01(\x05R\voptionIndex\"\x18\n" +
	"\x16AnswerQuestionResponse\"\x12\n" +
	"\x10ListModesRequest\"R\n" +
	"\x04Mode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"7\n" +
	"\x11ListModesResponse\x12\"\n" +
	"\x05modes\x18\x01 \x03(\v2\f.ycc.v1.ModeR\x05modes\"\x15\n" +
	"\x13ListSessionsRequest\"v\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tworkspace\x18\x04 \x01(\tR\tworkspace\"G\n" +
	"\x14ListSessionsResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.ycc.v1.SessionInfoR\bsessions2\xb3\x03\n" +
	"\x0eSessionService\x12@\n" +
	"\tListModes\x12\x18.ycc.v1.ListModesRequest\x1a\x19.ycc.v1.ListModesResponse\x12I\n" +
	"\fStartSession\x12\x1b.ycc.v1.StartSessionRequest\x1a\x1c.ycc.v1.StartSessionResponse\x12I\n" +
	"\fListSessions\x12\x1b.ycc.v1.ListSessionsRequest\x1a\x1c.ycc.v1.ListSessionsResponse\x126\n" +
	"\tSubscribe\x12\x18.ycc.v1.SubscribeRequest\x1a\r.ycc.v1.Event0\x01\x12@\n" +
	"\tSendInput\x12\x18.ycc.v1.SendInputRequest\x1a\x19.ycc.v1.SendInputResponse\x12O\n" +
	"\x0eAnswerQuestion\x12\x1d.ycc.v1.AnswerQuestionRequest\x1a\x1e.ycc.v1.AnswerQuestionResponseB1Z/github.com/whyrusleeping/ycc/proto/ycc/v1;yccv1b\x06proto3"

var (
	file_ycc_v1_ycc_proto_rawDescOnce sync.Once
	file_ycc_v1_ycc_proto_rawDescData []byte
)

func file_ycc_v1_ycc_proto_rawDescGZIP() []byte {
	file_ycc_v1_ycc_proto_rawDescOnce.Do(func() {
		file_ycc_v1_ycc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ycc_v1_ycc_proto_rawDesc), len(file_ycc_v1_ycc_proto_rawDesc)))
	})
	return file_ycc_v1_ycc_proto_rawDescData
}

var file_ycc_v1_ycc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ycc_v1_ycc_proto_goTypes = []any{
	(*Event)(nil),                  // 0: ycc.v1.Event
	(*StartSessionRequest)(nil),    // 1: ycc.v1.StartSessionRequest
	(*StartSessionResponse)(nil),   // 2: ycc.v1.StartSessionResponse
	(*SubscribeRequest)(nil),       // 3: ycc.v1.SubscribeRequest
	(*SendInputRequest)(nil),       // 4: ycc.v1.SendInputRequest
	(*SendInputResponse)(nil),      // 5: ycc.v1.SendInputResponse
	(*AnswerQuestionRequest)(nil),  // 6: ycc.v1.AnswerQuestionRequest
	(*AnswerQuestionResponse)(nil), // 7: ycc.v1.AnswerQuestionResponse
	(*ListModesRequest)(nil),       // 8: ycc.v1.ListModesRequest
	(*Mode)(nil),                   // 9: ycc.v1.Mode
	(*ListModesResponse)(nil),      // 10: ycc.v1.ListModesResponse
	(*ListSessionsRequest)(nil),    // 11: ycc.v1.ListSessionsRequest
	(*SessionInfo)(nil),            // 12: ycc.v1.SessionInfo
	(*ListSessionsResponse)(nil),   // 13: ycc.v1.ListSessionsResponse
}
var file_ycc_v1_ycc_proto_depIdxs = []int32{
	9,  // 0: ycc.v1.ListModesResponse.modes:type_name -> ycc.v1.Mode
	12, // 1: ycc.v1.ListSessionsResponse.sessions:type_name -> ycc.v1.SessionInfo
	8,  // 2: ycc.v1.SessionService.ListModes:input_type -> ycc.v1.ListModesRequest
	1,  // 3: ycc.v1.SessionService.StartSession:input_type -> ycc.v1.StartSessionRequest
	11, // 4: ycc.v1.SessionService.ListSessions:input_type -> ycc.v1.ListSessionsRequest
	3,  // 5: ycc.v1.SessionService.Subscribe:input_type -> ycc.v1.SubscribeRequest
	4,  // 6: ycc.v1.SessionService.SendInput:input_type -> ycc.v1.SendInputRequest
	6,  // 7: ycc.v1.SessionService.AnswerQuestion:input_type -> ycc.v1.AnswerQuestionRequest
	10, // 8: ycc.v1.SessionService.ListModes:output_type -> ycc.v1.ListModesResponse
	2,  // 9: ycc.v1.SessionService.StartSession:output_type -> ycc.v1.StartSessionResponse
	13, // 10: ycc.v1.SessionService.ListSessions:output_type -> ycc.v1.ListSessionsResponse
	0,  // 11: ycc.v1.SessionService.Subscribe:output_type -> ycc.v1.Event
	5,  // 12: ycc.v1.SessionService.SendInput:output_type -> ycc.v1.SendInputResponse
	7,  // 13: ycc.v1.SessionService.AnswerQuestion:output_type -> ycc.v1.AnswerQuestionResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_ycc_v1_ycc_proto_init() }
func file_ycc_v1_ycc_proto_init() {
	if File_ycc_v1_ycc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ycc_v1_ycc_proto_rawDesc), len(file_ycc_v1_ycc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ycc_v1_ycc_proto_goTypes,
		DependencyIndexes: file_ycc_v1_ycc_proto_depIdxs,
		MessageInfos:      file_ycc_v1_ycc_proto_msgTypes,
	}.Build()
	File_ycc_v1_ycc_proto = out.File
	file_ycc_v1_ycc_proto_goTypes = nil
	file_ycc_v1_ycc_proto_depIdxs = nil
}
