// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ycc/v1/ycc.proto

package yccv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event mirrors internal/event.Event. Data is carried as a JSON string so the
// heterogeneous per-type payload needs no proto schema churn (and matches the
// on-disk JSONL exactly).
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts            string                 `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"` // RFC3339
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DataJson      string                 `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *Event) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type StartSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Workspace        string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`                                       // workspace dir; empty => daemon default
	Mode             string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`                                                 // e.g. "work"; M1 runs a single worker agent
	InteractionLevel string                 `protobuf:"bytes,3,opt,name=interaction_level,json=interactionLevel,proto3" json:"interaction_level,omitempty"` // interactive | judgement | autonomous
	Prompt           string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`                                             // initial task prompt
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *StartSessionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StartSessionRequest) GetInteractionLevel() string {
	if x != nil {
		return x.InteractionLevel
	}
	return ""
}

func (x *StartSessionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{2}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromSeq       int64                  `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"` // replay events with seq > from_seq, then stream live
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribeRequest) GetFromSeq() int64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type SendInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputRequest) Reset() {
	*x = SendInputRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputRequest) ProtoMessage() {}

func (x *SendInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputRequest.ProtoReflect.Descriptor instead.
func (*SendInputRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{4}
}

func (x *SendInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendInputRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputResponse) Reset() {
	*x = SendInputResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputResponse) ProtoMessage() {}

func (x *SendInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputResponse.ProtoReflect.Descriptor instead.
func (*SendInputResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{5}
}

type AnswerQuestionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text      string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// option_index selects a suggested option from the question's options list
	// (0-based) when >= 0; otherwise text is taken as a free-text answer.
	OptionIndex   int32 `protobuf:"varint,3,opt,name=option_index,json=optionIndex,proto3" json:"option_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionRequest) Reset() {
	*x = AnswerQuestionRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionRequest) ProtoMessage() {}

func (x *AnswerQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionRequest.ProtoReflect.Descriptor instead.
func (*AnswerQuestionRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{6}
}

func (x *AnswerQuestionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnswerQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnswerQuestionRequest) GetOptionIndex() int32 {
	if x != nil {
		return x.OptionIndex
	}
	return 0
}

type AnswerQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionResponse) Reset() {
	*x = AnswerQuestionResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionResponse) ProtoMessage() {}

func (x *AnswerQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionResponse.ProtoReflect.Descriptor instead.
func (*AnswerQuestionResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{7}
}

type ListModesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModesRequest) Reset() {
	*x = ListModesRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModesRequest) ProtoMessage() {}

func (x *ListModesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModesRequest.ProtoReflect.Descriptor instead.
func (*ListModesRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{8}
}

type Mode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mode) Reset() {
	*x = Mode{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mode) ProtoMessage() {}

func (x *Mode) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mode.ProtoReflect.Descriptor instead.
func (*Mode) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{9}
}

func (x *Mode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Preset is a home-menu entry that starts a session in `mode` with a tailored
// `opening_prompt`. The pm mode exposes the old spec/backlog/feature/bug framings
// this way — one mode, four opening prompts (spec §9).
type Preset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // menu key, distinct from the mode
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`                                        // session mode to start (e.g. "pm")
	OpeningPrompt string                 `protobuf:"bytes,5,opt,name=opening_prompt,json=openingPrompt,proto3" json:"opening_prompt,omitempty"` // verbatim first prompt seeded into the session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preset) Reset() {
	*x = Preset{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preset) ProtoMessage() {}

func (x *Preset) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preset.ProtoReflect.Descriptor instead.
func (*Preset) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{10}
}

func (x *Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Preset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Preset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Preset) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Preset) GetOpeningPrompt() string {
	if x != nil {
		return x.OpeningPrompt
	}
	return ""
}

type ListModesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modes         []*Mode                `protobuf:"bytes,1,rep,name=modes,proto3" json:"modes,omitempty"`
	Presets       []*Preset              `protobuf:"bytes,2,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModesResponse) Reset() {
	*x = ListModesResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModesResponse) ProtoMessage() {}

func (x *ListModesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModesResponse.ProtoReflect.Descriptor instead.
func (*ListModesResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{11}
}

func (x *ListModesResponse) GetModes() []*Mode {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *ListModesResponse) GetPresets() []*Preset {
	if x != nil {
		return x.Presets
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{12}
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // running | idle | error
	Workspace     string                 `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{13}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionInfo) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{14}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// ListModels enumerates the configured logical models (spec §13) so the settings
// overlay can populate the per-role pickers.
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{15}
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // logical name (e.g. "claude", "gpt")
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"` // anthropic | openai | ollama | ...
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`     // backend model id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{16}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ModelInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{17}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

// SetInteractionLevel changes a session's interaction level mid-flight (spec §11,
// §18.2). It takes effect at the next gate and is recorded in the event log.
type SetInteractionLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // interactive | judgement | autonomous
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInteractionLevelRequest) Reset() {
	*x = SetInteractionLevelRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInteractionLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInteractionLevelRequest) ProtoMessage() {}

func (x *SetInteractionLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInteractionLevelRequest.ProtoReflect.Descriptor instead.
func (*SetInteractionLevelRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{18}
}

func (x *SetInteractionLevelRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetInteractionLevelRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type SetInteractionLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInteractionLevelResponse) Reset() {
	*x = SetInteractionLevelResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInteractionLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInteractionLevelResponse) ProtoMessage() {}

func (x *SetInteractionLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInteractionLevelResponse.ProtoReflect.Descriptor instead.
func (*SetInteractionLevelResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{19}
}

// SetRoleConfig reassigns per-role logical models mid-session (spec §13, §18.2).
// Empty coordinator/implementer leaves that role unchanged; an empty reviewers
// list leaves reviewers unchanged.
type SetRoleConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Coordinator   string                 `protobuf:"bytes,2,opt,name=coordinator,proto3" json:"coordinator,omitempty"`
	Implementer   string                 `protobuf:"bytes,3,opt,name=implementer,proto3" json:"implementer,omitempty"`
	Reviewers     []string               `protobuf:"bytes,4,rep,name=reviewers,proto3" json:"reviewers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleConfigRequest) Reset() {
	*x = SetRoleConfigRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleConfigRequest) ProtoMessage() {}

func (x *SetRoleConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleConfigRequest.ProtoReflect.Descriptor instead.
func (*SetRoleConfigRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{20}
}

func (x *SetRoleConfigRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetRoleConfigRequest) GetCoordinator() string {
	if x != nil {
		return x.Coordinator
	}
	return ""
}

func (x *SetRoleConfigRequest) GetImplementer() string {
	if x != nil {
		return x.Implementer
	}
	return ""
}

func (x *SetRoleConfigRequest) GetReviewers() []string {
	if x != nil {
		return x.Reviewers
	}
	return nil
}

type SetRoleConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleConfigResponse) Reset() {
	*x = SetRoleConfigResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleConfigResponse) ProtoMessage() {}

func (x *SetRoleConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleConfigResponse.ProtoReflect.Descriptor instead.
func (*SetRoleConfigResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{21}
}

// SetThinking changes a session-wide thinking/effort level mid-session (spec
// §18.2). The override applies to every agent in the session (coordinator +
// spawned subagents) and takes precedence over the per-model config until
// changed. Levels: off | low | medium | high | xhigh | max.
type SetThinkingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // off | low | medium | high | xhigh | max
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetThinkingRequest) Reset() {
	*x = SetThinkingRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetThinkingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetThinkingRequest) ProtoMessage() {}

func (x *SetThinkingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetThinkingRequest.ProtoReflect.Descriptor instead.
func (*SetThinkingRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{22}
}

func (x *SetThinkingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetThinkingRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type SetThinkingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetThinkingResponse) Reset() {
	*x = SetThinkingResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetThinkingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetThinkingResponse) ProtoMessage() {}

func (x *SetThinkingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetThinkingResponse.ProtoReflect.Descriptor instead.
func (*SetThinkingResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{23}
}

var File_ycc_v1_ycc_proto protoreflect.FileDescriptor

const file_ycc_v1_ycc_proto_rawDesc = "" +
	"\n" +
	"\x10ycc/v1/ycc.proto\x12\x06ycc.v1\"p\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\tR\x02ts\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\tR\bdataJson\"\x8c\x01\n" +
	"\x13StartSessionRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12+\n" +
	"\x11interaction_level\x18\x03 \x01(\tR\x10interactionLevel\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\"5\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"L\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x03R\afromSeq\"E\n" +
	"\x10SendInputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x13\n" +
	"\x11SendInputResponse\"m\n" +
	"\x15AnswerQuestionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\foption_index\x18\x03 \x01(\x05R\voptionIndex\"\x18\n" +
	"\x16AnswerQuestionResponse\"\x12\n" +
	"\x10ListModesRequest\"R\n" +
	"\x04Mode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8f\x01\n" +
	"\x06Preset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12%\n" +
	"\x0eopening_prompt\x18\x05 \x01(\tR\ropeningPrompt\"a\n" +
	"\x11ListModesResponse\x12\"\n" +
	"\x05modes\x18\x01 \x03(\v2\f.ycc.v1.ModeR\x05modes\x12(\n" +
	"\apresets\x18\x02 \x03(\v2\x0e.ycc.v1.PresetR\apresets\"\x15\n" +
	"\x13ListSessionsRequest\"v\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tworkspace\x18\x04 \x01(\tR\tworkspace\"G\n" +
	"\x14ListSessionsResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.ycc.v1.SessionInfoR\bsessions\"\x13\n" +
	"\x11ListModelsRequest\"O\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"?\n" +
	"\x12ListModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.ycc.v1.ModelInfoR\x06models\"Q\n" +
	"\x1aSetInteractionLevelRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"\x1d\n" +
	"\x1bSetInteractionLevelResponse\"\x97\x01\n" +
	"\x14SetRoleConfigRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\vcoordinator\x18\x02 \x01(\tR\vcoordinator\x12 \n" +
	"\vimplementer\x18\x03 \x01(\tR\vimplementer\x12\x1c\n" +
	"\treviewers\x18\x04 \x03(\tR\treviewers\"\x17\n" +
	"\x15SetRoleConfigResponse\"I\n" +
	"\x12SetThinkingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"\x15\n" +
	"\x13SetThinkingResponse2\xee\x05\n" +
	"\x0eSessionService\x12@\n" +
	"\tListModes\x12\x18.ycc.v1.ListModesRequest\x1a\x19.ycc.v1.ListModesResponse\x12I\n" +
	"\fStartSession\x12\x1b.ycc.v1.StartSessionRequest\x1a\x1c.ycc.v1.StartSessionResponse\x12I\n" +
	"\fListSessions\x12\x1b.ycc.v1.ListSessionsRequest\x1a\x1c.ycc.v1.ListSessionsResponse\x126\n" +
	"\tSubscribe\x12\x18.ycc.v1.SubscribeRequest\x1a\r.ycc.v1.Event0\x01\x12@\n" +
	"\tSendInput\x12\x18.ycc.v1.SendInputRequest\x1a\x19.ycc.v1.SendInputResponse\x12O\n" +
	"\x0eAnswerQuestion\x12\x1d.ycc.v1.AnswerQuestionRequest\x1a\x1e.ycc.v1.AnswerQuestionResponse\x12C\n" +
	"\n" +
	"ListModels\x12\x19.ycc.v1.ListModelsRequest\x1a\x1a.ycc.v1.ListModelsResponse\x12^\n" +
	"\x13SetInteractionLevel\x12\".ycc.v1.SetInteractionLevelRequest\x1a#.ycc.v1.SetInteractionLevelResponse\x12L\n" +
	"\rSetRoleConfig\x12\x1c.ycc.v1.SetRoleConfigRequest\x1a\x1d.ycc.v1.SetRoleConfigResponse\x12F\n" +
	"\vSetThinking\x12\x1a.ycc.v1.SetThinkingRequest\x1a\x1b.ycc.v1.SetThinkingResponseB1Z/github.com/whyrusleeping/ycc/proto/ycc/v1;yccv1b\x06proto3"

var (
	file_ycc_v1_ycc_proto_rawDescOnce sync.Once
	file_ycc_v1_ycc_proto_rawDescData []byte
)

func file_ycc_v1_ycc_proto_rawDescGZIP() []byte {
	file_ycc_v1_ycc_proto_rawDescOnce.Do(func() {
		file_ycc_v1_ycc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ycc_v1_ycc_proto_rawDesc), len(file_ycc_v1_ycc_proto_rawDesc)))
	})
	return file_ycc_v1_ycc_proto_rawDescData
}

var file_ycc_v1_ycc_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_ycc_v1_ycc_proto_goTypes = []any{
	(*Event)(nil),                       // 0: ycc.v1.Event
	(*StartSessionRequest)(nil),         // 1: ycc.v1.StartSessionRequest
	(*StartSessionResponse)(nil),        // 2: ycc.v1.StartSessionResponse
	(*SubscribeRequest)(nil),            // 3: ycc.v1.SubscribeRequest
	(*SendInputRequest)(nil),            // 4: ycc.v1.SendInputRequest
	(*SendInputResponse)(nil),           // 5: ycc.v1.SendInputResponse
	(*AnswerQuestionRequest)(nil),       // 6: ycc.v1.AnswerQuestionRequest
	(*AnswerQuestionResponse)(nil),      // 7: ycc.v1.AnswerQuestionResponse
	(*ListModesRequest)(nil),            // 8: ycc.v1.ListModesRequest
	(*Mode)(nil),                        // 9: ycc.v1.Mode
	(*Preset)(nil),                      // 10: ycc.v1.Preset
	(*ListModesResponse)(nil),           // 11: ycc.v1.ListModesResponse
	(*ListSessionsRequest)(nil),         // 12: ycc.v1.ListSessionsRequest
	(*SessionInfo)(nil),                 // 13: ycc.v1.SessionInfo
	(*ListSessionsResponse)(nil),        // 14: ycc.v1.ListSessionsResponse
	(*ListModelsRequest)(nil),           // 15: ycc.v1.ListModelsRequest
	(*ModelInfo)(nil),                   // 16: ycc.v1.ModelInfo
	(*ListModelsResponse)(nil),          // 17: ycc.v1.ListModelsResponse
	(*SetInteractionLevelRequest)(nil),  // 18: ycc.v1.SetInteractionLevelRequest
	(*SetInteractionLevelResponse)(nil), // 19: ycc.v1.SetInteractionLevelResponse
	(*SetRoleConfigRequest)(nil),        // 20: ycc.v1.SetRoleConfigRequest
	(*SetRoleConfigResponse)(nil),       // 21: ycc.v1.SetRoleConfigResponse
	(*SetThinkingRequest)(nil),          // 22: ycc.v1.SetThinkingRequest
	(*SetThinkingResponse)(nil),         // 23: ycc.v1.SetThinkingResponse
}
var file_ycc_v1_ycc_proto_depIdxs = []int32{
	9,  // 0: ycc.v1.ListModesResponse.modes:type_name -> ycc.v1.Mode
	10, // 1: ycc.v1.ListModesResponse.presets:type_name -> ycc.v1.Preset
	13, // 2: ycc.v1.ListSessionsResponse.sessions:type_name -> ycc.v1.SessionInfo
	16, // 3: ycc.v1.ListModelsResponse.models:type_name -> ycc.v1.ModelInfo
	8,  // 4: ycc.v1.SessionService.ListModes:input_type -> ycc.v1.ListModesRequest
	1,  // 5: ycc.v1.SessionService.StartSession:input_type -> ycc.v1.StartSessionRequest
	12, // 6: ycc.v1.SessionService.ListSessions:input_type -> ycc.v1.ListSessionsRequest
	3,  // 7: ycc.v1.SessionService.Subscribe:input_type -> ycc.v1.SubscribeRequest
	4,  // 8: ycc.v1.SessionService.SendInput:input_type -> ycc.v1.SendInputRequest
	6,  // 9: ycc.v1.SessionService.AnswerQuestion:input_type -> ycc.v1.AnswerQuestionRequest
	15, // 10: ycc.v1.SessionService.ListModels:input_type -> ycc.v1.ListModelsRequest
	18, // 11: ycc.v1.SessionService.SetInteractionLevel:input_type -> ycc.v1.SetInteractionLevelRequest
	20, // 12: ycc.v1.SessionService.SetRoleConfig:input_type -> ycc.v1.SetRoleConfigRequest
	22, // 13: ycc.v1.SessionService.SetThinking:input_type -> ycc.v1.SetThinkingRequest
	11, // 14: ycc.v1.SessionService.ListModes:output_type -> ycc.v1.ListModesResponse
	2,  // 15: ycc.v1.SessionService.StartSession:output_type -> ycc.v1.StartSessionResponse
	14, // 16: ycc.v1.SessionService.ListSessions:output_type -> ycc.v1.ListSessionsResponse
	0,  // 17: ycc.v1.SessionService.Subscribe:output_type -> ycc.v1.Event
	5,  // 18: ycc.v1.SessionService.SendInput:output_type -> ycc.v1.SendInputResponse
	7,  // 19: ycc.v1.SessionService.AnswerQuestion:output_type -> ycc.v1.AnswerQuestionResponse
	17, // 20: ycc.v1.SessionService.ListModels:output_type -> ycc.v1.ListModelsResponse
	19, // 21: ycc.v1.SessionService.SetInteractionLevel:output_type -> ycc.v1.SetInteractionLevelResponse
	21, // 22: ycc.v1.SessionService.SetRoleConfig:output_type -> ycc.v1.SetRoleConfigResponse
	23, // 23: ycc.v1.SessionService.SetThinking:output_type -> ycc.v1.SetThinkingResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ycc_v1_ycc_proto_init() }
func file_ycc_v1_ycc_proto_init() {
	if File_ycc_v1_ycc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ycc_v1_ycc_proto_rawDesc), len(file_ycc_v1_ycc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ycc_v1_ycc_proto_goTypes,
		DependencyIndexes: file_ycc_v1_ycc_proto_depIdxs,
		MessageInfos:      file_ycc_v1_ycc_proto_msgTypes,
	}.Build()
	File_ycc_v1_ycc_proto = out.File
	file_ycc_v1_ycc_proto_goTypes = nil
	file_ycc_v1_ycc_proto_depIdxs = nil
}
