// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ycc/v1/ycc.proto

package yccv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event mirrors internal/event.Event. Data is carried as a JSON string so the
// heterogeneous per-type payload needs no proto schema churn (and matches the
// on-disk JSONL exactly).
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts            string                 `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"` // RFC3339
	Actor         string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	DataJson      string                 `protobuf:"bytes,5,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *Event) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type StartSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Workspace        string                 `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`                                       // workspace dir; empty => daemon default
	Mode             string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`                                                 // e.g. "work"; M1 runs a single worker agent
	InteractionLevel string                 `protobuf:"bytes,3,opt,name=interaction_level,json=interactionLevel,proto3" json:"interaction_level,omitempty"` // interactive | judgement | autonomous
	Prompt           string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`                                             // initial task prompt
	// project is an optional registered project name; when set it resolves to that
	// project's workspace (overriding `workspace`). Spec §3.1.
	Project       string `protobuf:"bytes,5,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionRequest) Reset() {
	*x = StartSessionRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionRequest) ProtoMessage() {}

func (x *StartSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionRequest.ProtoReflect.Descriptor instead.
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{1}
}

func (x *StartSessionRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *StartSessionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StartSessionRequest) GetInteractionLevel() string {
	if x != nil {
		return x.InteractionLevel
	}
	return ""
}

func (x *StartSessionRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *StartSessionRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type StartSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSessionResponse) Reset() {
	*x = StartSessionResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSessionResponse) ProtoMessage() {}

func (x *StartSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSessionResponse.ProtoReflect.Descriptor instead.
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{2}
}

func (x *StartSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Projects — persistent multi-project daemon (spec §3.1). A project is a named
// workspace; the daemon's registry maps name -> path in its state dir.
type ProjectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectInfo) Reset() {
	*x = ProjectInfo{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectInfo) ProtoMessage() {}

func (x *ProjectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectInfo.ProtoReflect.Descriptor instead.
func (*ProjectInfo) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{4}
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*ProjectInfo         `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectsResponse) GetProjects() []*ProjectInfo {
	if x != nil {
		return x.Projects
	}
	return nil
}

type AddProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // workspace dir to register
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // optional; derived from the dir basename when empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectRequest) Reset() {
	*x = AddProjectRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectRequest) ProtoMessage() {}

func (x *AddProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectRequest.ProtoReflect.Descriptor instead.
func (*AddProjectRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{6}
}

func (x *AddProjectRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AddProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *ProjectInfo           `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProjectResponse) Reset() {
	*x = AddProjectResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProjectResponse) ProtoMessage() {}

func (x *AddProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProjectResponse.ProtoReflect.Descriptor instead.
func (*AddProjectResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{7}
}

func (x *AddProjectResponse) GetProject() *ProjectInfo {
	if x != nil {
		return x.Project
	}
	return nil
}

type RemoveProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectRequest) Reset() {
	*x = RemoveProjectRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectRequest) ProtoMessage() {}

func (x *RemoveProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectRequest.ProtoReflect.Descriptor instead.
func (*RemoveProjectRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectResponse) Reset() {
	*x = RemoveProjectResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectResponse) ProtoMessage() {}

func (x *RemoveProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectResponse.ProtoReflect.Descriptor instead.
func (*RemoveProjectResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{9}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromSeq       int64                  `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"` // replay events with seq > from_seq, then stream live
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribeRequest) GetFromSeq() int64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

type SendInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputRequest) Reset() {
	*x = SendInputRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputRequest) ProtoMessage() {}

func (x *SendInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputRequest.ProtoReflect.Descriptor instead.
func (*SendInputRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{11}
}

func (x *SendInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendInputRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputResponse) Reset() {
	*x = SendInputResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputResponse) ProtoMessage() {}

func (x *SendInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputResponse.ProtoReflect.Descriptor instead.
func (*SendInputResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{12}
}

type AnswerQuestionRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Text      string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// option_index selects a suggested option from the question's options list
	// (0-based) when >= 0; otherwise text is taken as a free-text answer.
	OptionIndex   int32 `protobuf:"varint,3,opt,name=option_index,json=optionIndex,proto3" json:"option_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionRequest) Reset() {
	*x = AnswerQuestionRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionRequest) ProtoMessage() {}

func (x *AnswerQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionRequest.ProtoReflect.Descriptor instead.
func (*AnswerQuestionRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{13}
}

func (x *AnswerQuestionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnswerQuestionRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnswerQuestionRequest) GetOptionIndex() int32 {
	if x != nil {
		return x.OptionIndex
	}
	return 0
}

type AnswerQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerQuestionResponse) Reset() {
	*x = AnswerQuestionResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerQuestionResponse) ProtoMessage() {}

func (x *AnswerQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerQuestionResponse.ProtoReflect.Descriptor instead.
func (*AnswerQuestionResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{14}
}

type ListModesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModesRequest) Reset() {
	*x = ListModesRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModesRequest) ProtoMessage() {}

func (x *ListModesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModesRequest.ProtoReflect.Descriptor instead.
func (*ListModesRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{15}
}

type Mode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mode) Reset() {
	*x = Mode{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mode) ProtoMessage() {}

func (x *Mode) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mode.ProtoReflect.Descriptor instead.
func (*Mode) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{16}
}

func (x *Mode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Preset is a home-menu entry that starts a session in `mode` with a tailored
// `opening_prompt`. The pm mode exposes the old spec/backlog/feature/bug framings
// this way — one mode, four opening prompts (spec §9).
type Preset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // menu key, distinct from the mode
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`                                        // session mode to start (e.g. "pm")
	OpeningPrompt string                 `protobuf:"bytes,5,opt,name=opening_prompt,json=openingPrompt,proto3" json:"opening_prompt,omitempty"` // verbatim first prompt seeded into the session
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preset) Reset() {
	*x = Preset{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preset) ProtoMessage() {}

func (x *Preset) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preset.ProtoReflect.Descriptor instead.
func (*Preset) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{17}
}

func (x *Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Preset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Preset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Preset) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Preset) GetOpeningPrompt() string {
	if x != nil {
		return x.OpeningPrompt
	}
	return ""
}

type ListModesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modes         []*Mode                `protobuf:"bytes,1,rep,name=modes,proto3" json:"modes,omitempty"`
	Presets       []*Preset              `protobuf:"bytes,2,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModesResponse) Reset() {
	*x = ListModesResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModesResponse) ProtoMessage() {}

func (x *ListModesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModesResponse.ProtoReflect.Descriptor instead.
func (*ListModesResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{18}
}

func (x *ListModesResponse) GetModes() []*Mode {
	if x != nil {
		return x.Modes
	}
	return nil
}

func (x *ListModesResponse) GetPresets() []*Preset {
	if x != nil {
		return x.Presets
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"` // optional: filter to sessions in this project's workspace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{19}
}

func (x *ListSessionsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // running | idle | error
	Workspace     string                 `protobuf:"bytes,4,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{20}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SessionInfo) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{21}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// ListModels enumerates the configured logical models (spec §13) so the settings
// overlay can populate the per-role pickers.
type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{22}
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // logical name (e.g. "claude", "gpt")
	Backend       string                 `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"` // anthropic | openai | ollama | ...
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`     // backend model id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{23}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ModelInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{24}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

// SetInteractionLevel changes a session's interaction level mid-flight (spec §11,
// §18.2). It takes effect at the next gate and is recorded in the event log.
type SetInteractionLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // interactive | judgement | autonomous
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInteractionLevelRequest) Reset() {
	*x = SetInteractionLevelRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInteractionLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInteractionLevelRequest) ProtoMessage() {}

func (x *SetInteractionLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInteractionLevelRequest.ProtoReflect.Descriptor instead.
func (*SetInteractionLevelRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{25}
}

func (x *SetInteractionLevelRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetInteractionLevelRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type SetInteractionLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInteractionLevelResponse) Reset() {
	*x = SetInteractionLevelResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInteractionLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInteractionLevelResponse) ProtoMessage() {}

func (x *SetInteractionLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInteractionLevelResponse.ProtoReflect.Descriptor instead.
func (*SetInteractionLevelResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{26}
}

// SetRoleConfig reassigns per-role logical models mid-session (spec §13, §18.2).
// Empty coordinator/implementer leaves that role unchanged; an empty reviewers
// list leaves reviewers unchanged.
type SetRoleConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Coordinator   string                 `protobuf:"bytes,2,opt,name=coordinator,proto3" json:"coordinator,omitempty"`
	Implementer   string                 `protobuf:"bytes,3,opt,name=implementer,proto3" json:"implementer,omitempty"`
	Reviewers     []string               `protobuf:"bytes,4,rep,name=reviewers,proto3" json:"reviewers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleConfigRequest) Reset() {
	*x = SetRoleConfigRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleConfigRequest) ProtoMessage() {}

func (x *SetRoleConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleConfigRequest.ProtoReflect.Descriptor instead.
func (*SetRoleConfigRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{27}
}

func (x *SetRoleConfigRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetRoleConfigRequest) GetCoordinator() string {
	if x != nil {
		return x.Coordinator
	}
	return ""
}

func (x *SetRoleConfigRequest) GetImplementer() string {
	if x != nil {
		return x.Implementer
	}
	return ""
}

func (x *SetRoleConfigRequest) GetReviewers() []string {
	if x != nil {
		return x.Reviewers
	}
	return nil
}

type SetRoleConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoleConfigResponse) Reset() {
	*x = SetRoleConfigResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoleConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoleConfigResponse) ProtoMessage() {}

func (x *SetRoleConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoleConfigResponse.ProtoReflect.Descriptor instead.
func (*SetRoleConfigResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{28}
}

// SetThinking changes a session-wide thinking/effort level mid-session (spec
// §18.2). The override applies to every agent in the session (coordinator +
// spawned subagents) and takes precedence over the per-model config until
// changed. Levels: off | low | medium | high | xhigh | max.
type SetThinkingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // off | low | medium | high | xhigh | max
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetThinkingRequest) Reset() {
	*x = SetThinkingRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetThinkingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetThinkingRequest) ProtoMessage() {}

func (x *SetThinkingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetThinkingRequest.ProtoReflect.Descriptor instead.
func (*SetThinkingRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{29}
}

func (x *SetThinkingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SetThinkingRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type SetThinkingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetThinkingResponse) Reset() {
	*x = SetThinkingResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetThinkingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetThinkingResponse) ProtoMessage() {}

func (x *SetThinkingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetThinkingResponse.ProtoReflect.Descriptor instead.
func (*SetThinkingResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{30}
}

// Backlog browser (spec §18.5): read-only RPCs that expose the durable backlog
// (internal/docs Store) so clients can list and inspect tasks independent of any
// agent session.
type ListBacklogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"` // optional registered project; empty => daemon default workspace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBacklogRequest) Reset() {
	*x = ListBacklogRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBacklogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBacklogRequest) ProtoMessage() {}

func (x *ListBacklogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBacklogRequest.ProtoReflect.Descriptor instead.
func (*ListBacklogRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{31}
}

func (x *ListBacklogRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type BacklogTaskSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	DependsOn     []string               `protobuf:"bytes,5,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Ready         bool                   `protobuf:"varint,6,opt,name=ready,proto3" json:"ready,omitempty"`                         // true when no dependency is blocking
	BlockedBy     []string               `protobuf:"bytes,7,rep,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"` // ids of not-yet-done dependencies
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacklogTaskSummary) Reset() {
	*x = BacklogTaskSummary{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacklogTaskSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacklogTaskSummary) ProtoMessage() {}

func (x *BacklogTaskSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacklogTaskSummary.ProtoReflect.Descriptor instead.
func (*BacklogTaskSummary) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{32}
}

func (x *BacklogTaskSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BacklogTaskSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BacklogTaskSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BacklogTaskSummary) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *BacklogTaskSummary) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *BacklogTaskSummary) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *BacklogTaskSummary) GetBlockedBy() []string {
	if x != nil {
		return x.BlockedBy
	}
	return nil
}

type ListBacklogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*BacklogTaskSummary  `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBacklogResponse) Reset() {
	*x = ListBacklogResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBacklogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBacklogResponse) ProtoMessage() {}

func (x *ListBacklogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBacklogResponse.ProtoReflect.Descriptor instead.
func (*ListBacklogResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{33}
}

func (x *ListBacklogResponse) GetTasks() []*BacklogTaskSummary {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"` // optional registered project; empty => daemon default workspace
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{34}
}

func (x *GetTaskRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TaskDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	DependsOn     []string               `protobuf:"bytes,5,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	SpecRefs      []string               `protobuf:"bytes,6,rep,name=spec_refs,json=specRefs,proto3" json:"spec_refs,omitempty"`
	Created       string                 `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	Updated       string                 `protobuf:"bytes,8,opt,name=updated,proto3" json:"updated,omitempty"`
	Body          string                 `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"` // markdown: description, acceptance criteria, work log
	Ready         bool                   `protobuf:"varint,10,opt,name=ready,proto3" json:"ready,omitempty"`
	BlockedBy     []string               `protobuf:"bytes,11,rep,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDetail) Reset() {
	*x = TaskDetail{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDetail) ProtoMessage() {}

func (x *TaskDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDetail.ProtoReflect.Descriptor instead.
func (*TaskDetail) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{35}
}

func (x *TaskDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskDetail) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskDetail) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *TaskDetail) GetSpecRefs() []string {
	if x != nil {
		return x.SpecRefs
	}
	return nil
}

func (x *TaskDetail) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *TaskDetail) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *TaskDetail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *TaskDetail) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *TaskDetail) GetBlockedBy() []string {
	if x != nil {
		return x.BlockedBy
	}
	return nil
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *TaskDetail            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_ycc_v1_ycc_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ycc_v1_ycc_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_ycc_v1_ycc_proto_rawDescGZIP(), []int{36}
}

func (x *GetTaskResponse) GetTask() *TaskDetail {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_ycc_v1_ycc_proto protoreflect.FileDescriptor

const file_ycc_v1_ycc_proto_rawDesc = "" +
	"\n" +
	"\x10ycc/v1/ycc.proto\x12\x06ycc.v1\"p\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\tR\x02ts\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x05 \x01(\tR\bdataJson\"\xa6\x01\n" +
	"\x13StartSessionRequest\x12\x1c\n" +
	"\tworkspace\x18\x01 \x01(\tR\tworkspace\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12+\n" +
	"\x11interaction_level\x18\x03 \x01(\tR\x10interactionLevel\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x18\n" +
	"\aproject\x18\x05 \x01(\tR\aproject\"5\n" +
	"\x14StartSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"5\n" +
	"\vProjectInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x15\n" +
	"\x13ListProjectsRequest\"G\n" +
	"\x14ListProjectsResponse\x12/\n" +
	"\bprojects\x18\x01 \x03(\v2\x13.ycc.v1.ProjectInfoR\bprojects\";\n" +
	"\x11AddProjectRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"C\n" +
	"\x12AddProjectResponse\x12-\n" +
	"\aproject\x18\x01 \x01(\v2\x13.ycc.v1.ProjectInfoR\aproject\"*\n" +
	"\x14RemoveProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15RemoveProjectResponse\"L\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x03R\afromSeq\"E\n" +
	"\x10SendInputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x13\n" +
	"\x11SendInputResponse\"m\n" +
	"\x15AnswerQuestionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\foption_index\x18\x03 \x01(\x05R\voptionIndex\"\x18\n" +
	"\x16AnswerQuestionResponse\"\x12\n" +
	"\x10ListModesRequest\"R\n" +
	"\x04Mode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x8f\x01\n" +
	"\x06Preset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12%\n" +
	"\x0eopening_prompt\x18\x05 \x01(\tR\ropeningPrompt\"a\n" +
	"\x11ListModesResponse\x12\"\n" +
	"\x05modes\x18\x01 \x03(\v2\f.ycc.v1.ModeR\x05modes\x12(\n" +
	"\apresets\x18\x02 \x03(\v2\x0e.ycc.v1.PresetR\apresets\"/\n" +
	"\x13ListSessionsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"v\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\tworkspace\x18\x04 \x01(\tR\tworkspace\"G\n" +
	"\x14ListSessionsResponse\x12/\n" +
	"\bsessions\x18\x01 \x03(\v2\x13.ycc.v1.SessionInfoR\bsessions\"\x13\n" +
	"\x11ListModelsRequest\"O\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"?\n" +
	"\x12ListModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.ycc.v1.ModelInfoR\x06models\"Q\n" +
	"\x1aSetInteractionLevelRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"\x1d\n" +
	"\x1bSetInteractionLevelResponse\"\x97\x01\n" +
	"\x14SetRoleConfigRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\vcoordinator\x18\x02 \x01(\tR\vcoordinator\x12 \n" +
	"\vimplementer\x18\x03 \x01(\tR\vimplementer\x12\x1c\n" +
	"\treviewers\x18\x04 \x03(\tR\treviewers\"\x17\n" +
	"\x15SetRoleConfigResponse\"I\n" +
	"\x12SetThinkingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\"\x15\n" +
	"\x13SetThinkingResponse\".\n" +
	"\x12ListBacklogRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"\xc2\x01\n" +
	"\x12BacklogTaskSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x05 \x03(\tR\tdependsOn\x12\x14\n" +
	"\x05ready\x18\x06 \x01(\bR\x05ready\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\a \x03(\tR\tblockedBy\"G\n" +
	"\x13ListBacklogResponse\x120\n" +
	"\x05tasks\x18\x01 \x03(\v2\x1a.ycc.v1.BacklogTaskSummaryR\x05tasks\":\n" +
	"\x0eGetTaskRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x9f\x02\n" +
	"\n" +
	"TaskDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x05 \x03(\tR\tdependsOn\x12\x1b\n" +
	"\tspec_refs\x18\x06 \x03(\tR\bspecRefs\x12\x18\n" +
	"\acreated\x18\a \x01(\tR\acreated\x12\x18\n" +
	"\aupdated\x18\b \x01(\tR\aupdated\x12\x12\n" +
	"\x04body\x18\t \x01(\tR\x04body\x12\x14\n" +
	"\x05ready\x18\n" +
	" \x01(\bR\x05ready\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\v \x03(\tR\tblockedBy\"9\n" +
	"\x0fGetTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.ycc.v1.TaskDetailR\x04task2\xd0\b\n" +
	"\x0eSessionService\x12@\n" +
	"\tListModes\x12\x18.ycc.v1.ListModesRequest\x1a\x19.ycc.v1.ListModesResponse\x12I\n" +
	"\fStartSession\x12\x1b.ycc.v1.StartSessionRequest\x1a\x1c.ycc.v1.StartSessionResponse\x12I\n" +
	"\fListSessions\x12\x1b.ycc.v1.ListSessionsRequest\x1a\x1c.ycc.v1.ListSessionsResponse\x126\n" +
	"\tSubscribe\x12\x18.ycc.v1.SubscribeRequest\x1a\r.ycc.v1.Event0\x01\x12@\n" +
	"\tSendInput\x12\x18.ycc.v1.SendInputRequest\x1a\x19.ycc.v1.SendInputResponse\x12O\n" +
	"\x0eAnswerQuestion\x12\x1d.ycc.v1.AnswerQuestionRequest\x1a\x1e.ycc.v1.AnswerQuestionResponse\x12I\n" +
	"\fListProjects\x12\x1b.ycc.v1.ListProjectsRequest\x1a\x1c.ycc.v1.ListProjectsResponse\x12C\n" +
	"\n" +
	"AddProject\x12\x19.ycc.v1.AddProjectRequest\x1a\x1a.ycc.v1.AddProjectResponse\x12L\n" +
	"\rRemoveProject\x12\x1c.ycc.v1.RemoveProjectRequest\x1a\x1d.ycc.v1.RemoveProjectResponse\x12C\n" +
	"\n" +
	"ListModels\x12\x19.ycc.v1.ListModelsRequest\x1a\x1a.ycc.v1.ListModelsResponse\x12^\n" +
	"\x13SetInteractionLevel\x12\".ycc.v1.SetInteractionLevelRequest\x1a#.ycc.v1.SetInteractionLevelResponse\x12L\n" +
	"\rSetRoleConfig\x12\x1c.ycc.v1.SetRoleConfigRequest\x1a\x1d.ycc.v1.SetRoleConfigResponse\x12F\n" +
	"\vSetThinking\x12\x1a.ycc.v1.SetThinkingRequest\x1a\x1b.ycc.v1.SetThinkingResponse\x12F\n" +
	"\vListBacklog\x12\x1a.ycc.v1.ListBacklogRequest\x1a\x1b.ycc.v1.ListBacklogResponse\x12:\n" +
	"\aGetTask\x12\x16.ycc.v1.GetTaskRequest\x1a\x17.ycc.v1.GetTaskResponseB1Z/github.com/whyrusleeping/ycc/proto/ycc/v1;yccv1b\x06proto3"

var (
	file_ycc_v1_ycc_proto_rawDescOnce sync.Once
	file_ycc_v1_ycc_proto_rawDescData []byte
)

func file_ycc_v1_ycc_proto_rawDescGZIP() []byte {
	file_ycc_v1_ycc_proto_rawDescOnce.Do(func() {
		file_ycc_v1_ycc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ycc_v1_ycc_proto_rawDesc), len(file_ycc_v1_ycc_proto_rawDesc)))
	})
	return file_ycc_v1_ycc_proto_rawDescData
}

var file_ycc_v1_ycc_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_ycc_v1_ycc_proto_goTypes = []any{
	(*Event)(nil),                       // 0: ycc.v1.Event
	(*StartSessionRequest)(nil),         // 1: ycc.v1.StartSessionRequest
	(*StartSessionResponse)(nil),        // 2: ycc.v1.StartSessionResponse
	(*ProjectInfo)(nil),                 // 3: ycc.v1.ProjectInfo
	(*ListProjectsRequest)(nil),         // 4: ycc.v1.ListProjectsRequest
	(*ListProjectsResponse)(nil),        // 5: ycc.v1.ListProjectsResponse
	(*AddProjectRequest)(nil),           // 6: ycc.v1.AddProjectRequest
	(*AddProjectResponse)(nil),          // 7: ycc.v1.AddProjectResponse
	(*RemoveProjectRequest)(nil),        // 8: ycc.v1.RemoveProjectRequest
	(*RemoveProjectResponse)(nil),       // 9: ycc.v1.RemoveProjectResponse
	(*SubscribeRequest)(nil),            // 10: ycc.v1.SubscribeRequest
	(*SendInputRequest)(nil),            // 11: ycc.v1.SendInputRequest
	(*SendInputResponse)(nil),           // 12: ycc.v1.SendInputResponse
	(*AnswerQuestionRequest)(nil),       // 13: ycc.v1.AnswerQuestionRequest
	(*AnswerQuestionResponse)(nil),      // 14: ycc.v1.AnswerQuestionResponse
	(*ListModesRequest)(nil),            // 15: ycc.v1.ListModesRequest
	(*Mode)(nil),                        // 16: ycc.v1.Mode
	(*Preset)(nil),                      // 17: ycc.v1.Preset
	(*ListModesResponse)(nil),           // 18: ycc.v1.ListModesResponse
	(*ListSessionsRequest)(nil),         // 19: ycc.v1.ListSessionsRequest
	(*SessionInfo)(nil),                 // 20: ycc.v1.SessionInfo
	(*ListSessionsResponse)(nil),        // 21: ycc.v1.ListSessionsResponse
	(*ListModelsRequest)(nil),           // 22: ycc.v1.ListModelsRequest
	(*ModelInfo)(nil),                   // 23: ycc.v1.ModelInfo
	(*ListModelsResponse)(nil),          // 24: ycc.v1.ListModelsResponse
	(*SetInteractionLevelRequest)(nil),  // 25: ycc.v1.SetInteractionLevelRequest
	(*SetInteractionLevelResponse)(nil), // 26: ycc.v1.SetInteractionLevelResponse
	(*SetRoleConfigRequest)(nil),        // 27: ycc.v1.SetRoleConfigRequest
	(*SetRoleConfigResponse)(nil),       // 28: ycc.v1.SetRoleConfigResponse
	(*SetThinkingRequest)(nil),          // 29: ycc.v1.SetThinkingRequest
	(*SetThinkingResponse)(nil),         // 30: ycc.v1.SetThinkingResponse
	(*ListBacklogRequest)(nil),          // 31: ycc.v1.ListBacklogRequest
	(*BacklogTaskSummary)(nil),          // 32: ycc.v1.BacklogTaskSummary
	(*ListBacklogResponse)(nil),         // 33: ycc.v1.ListBacklogResponse
	(*GetTaskRequest)(nil),              // 34: ycc.v1.GetTaskRequest
	(*TaskDetail)(nil),                  // 35: ycc.v1.TaskDetail
	(*GetTaskResponse)(nil),             // 36: ycc.v1.GetTaskResponse
}
var file_ycc_v1_ycc_proto_depIdxs = []int32{
	3,  // 0: ycc.v1.ListProjectsResponse.projects:type_name -> ycc.v1.ProjectInfo
	3,  // 1: ycc.v1.AddProjectResponse.project:type_name -> ycc.v1.ProjectInfo
	16, // 2: ycc.v1.ListModesResponse.modes:type_name -> ycc.v1.Mode
	17, // 3: ycc.v1.ListModesResponse.presets:type_name -> ycc.v1.Preset
	20, // 4: ycc.v1.ListSessionsResponse.sessions:type_name -> ycc.v1.SessionInfo
	23, // 5: ycc.v1.ListModelsResponse.models:type_name -> ycc.v1.ModelInfo
	32, // 6: ycc.v1.ListBacklogResponse.tasks:type_name -> ycc.v1.BacklogTaskSummary
	35, // 7: ycc.v1.GetTaskResponse.task:type_name -> ycc.v1.TaskDetail
	15, // 8: ycc.v1.SessionService.ListModes:input_type -> ycc.v1.ListModesRequest
	1,  // 9: ycc.v1.SessionService.StartSession:input_type -> ycc.v1.StartSessionRequest
	19, // 10: ycc.v1.SessionService.ListSessions:input_type -> ycc.v1.ListSessionsRequest
	10, // 11: ycc.v1.SessionService.Subscribe:input_type -> ycc.v1.SubscribeRequest
	11, // 12: ycc.v1.SessionService.SendInput:input_type -> ycc.v1.SendInputRequest
	13, // 13: ycc.v1.SessionService.AnswerQuestion:input_type -> ycc.v1.AnswerQuestionRequest
	4,  // 14: ycc.v1.SessionService.ListProjects:input_type -> ycc.v1.ListProjectsRequest
	6,  // 15: ycc.v1.SessionService.AddProject:input_type -> ycc.v1.AddProjectRequest
	8,  // 16: ycc.v1.SessionService.RemoveProject:input_type -> ycc.v1.RemoveProjectRequest
	22, // 17: ycc.v1.SessionService.ListModels:input_type -> ycc.v1.ListModelsRequest
	25, // 18: ycc.v1.SessionService.SetInteractionLevel:input_type -> ycc.v1.SetInteractionLevelRequest
	27, // 19: ycc.v1.SessionService.SetRoleConfig:input_type -> ycc.v1.SetRoleConfigRequest
	29, // 20: ycc.v1.SessionService.SetThinking:input_type -> ycc.v1.SetThinkingRequest
	31, // 21: ycc.v1.SessionService.ListBacklog:input_type -> ycc.v1.ListBacklogRequest
	34, // 22: ycc.v1.SessionService.GetTask:input_type -> ycc.v1.GetTaskRequest
	18, // 23: ycc.v1.SessionService.ListModes:output_type -> ycc.v1.ListModesResponse
	2,  // 24: ycc.v1.SessionService.StartSession:output_type -> ycc.v1.StartSessionResponse
	21, // 25: ycc.v1.SessionService.ListSessions:output_type -> ycc.v1.ListSessionsResponse
	0,  // 26: ycc.v1.SessionService.Subscribe:output_type -> ycc.v1.Event
	12, // 27: ycc.v1.SessionService.SendInput:output_type -> ycc.v1.SendInputResponse
	14, // 28: ycc.v1.SessionService.AnswerQuestion:output_type -> ycc.v1.AnswerQuestionResponse
	5,  // 29: ycc.v1.SessionService.ListProjects:output_type -> ycc.v1.ListProjectsResponse
	7,  // 30: ycc.v1.SessionService.AddProject:output_type -> ycc.v1.AddProjectResponse
	9,  // 31: ycc.v1.SessionService.RemoveProject:output_type -> ycc.v1.RemoveProjectResponse
	24, // 32: ycc.v1.SessionService.ListModels:output_type -> ycc.v1.ListModelsResponse
	26, // 33: ycc.v1.SessionService.SetInteractionLevel:output_type -> ycc.v1.SetInteractionLevelResponse
	28, // 34: ycc.v1.SessionService.SetRoleConfig:output_type -> ycc.v1.SetRoleConfigResponse
	30, // 35: ycc.v1.SessionService.SetThinking:output_type -> ycc.v1.SetThinkingResponse
	33, // 36: ycc.v1.SessionService.ListBacklog:output_type -> ycc.v1.ListBacklogResponse
	36, // 37: ycc.v1.SessionService.GetTask:output_type -> ycc.v1.GetTaskResponse
	23, // [23:38] is the sub-list for method output_type
	8,  // [8:23] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ycc_v1_ycc_proto_init() }
func file_ycc_v1_ycc_proto_init() {
	if File_ycc_v1_ycc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ycc_v1_ycc_proto_rawDesc), len(file_ycc_v1_ycc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ycc_v1_ycc_proto_goTypes,
		DependencyIndexes: file_ycc_v1_ycc_proto_depIdxs,
		MessageInfos:      file_ycc_v1_ycc_proto_msgTypes,
	}.Build()
	File_ycc_v1_ycc_proto = out.File
	file_ycc_v1_ycc_proto_goTypes = nil
	file_ycc_v1_ycc_proto_depIdxs = nil
}
